### ISSUE TITLE
Support config 'backup-dir' can be changed

### ISSUE THREAD

**Issue by iushas** [apache/kvrocks#1007]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Support config 'backup-dir' can be changed,
now can't be modify 

```
127.0.0.1:6379> config set backup-dir /home/data/backup/db
(error) CONFIG SET 'backup-dir' error: Unsupported CONFIG parameter: backup-dir
```

### Solution

backup disk or filesystem may be damaged， wo need change the backupdir  to ensure backup process is normal

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
I'd like to submit a patch for this issue, but I have some problems
@git-hulk What's the expective behavior for `config set backup-dir ...` when:
1. Previous database is backing up?
2. Have previous backup?

Changing the `backup_dir` is easy, but it may tears using it. And previous `backup_dir` may having backup data. Should we purge old backup or rename dir when the dir is changed?

**Comment by git-hulk** [comment]
> I'd like to submit a patch for this issue, but I have some problems @git-hulk What's the expective behavior for `config set backup-dir ...` when:
> 
> 1. Previous database is backing up?
> 2. Have previous backup?
> 
> Changing the `backup_dir` is easy, but it may tears using it. And previous `backup_dir` may having backup data. Should we purge old backup or rename dir when the dir is changed?

@mapleFU Thank you! 

1. Previous database is backing up?

**The change can only affect the new coming backup request, the on going backup can be still i the old backup dir.**

3. Have previous backup?

**Yes, we can keep at most one backup**


4. And previous `backup_dir` may having backup data. Should we purge old backup or rename dir when the dir is changed?

**I think we can left the old backup data as it be and users can delete it manually if they want.**

**Comment by mapleFU** [comment]
Seems that after gothrough issue: 
https://github.com/redis/redis/issues/3594
and code for redis about `dbfilename` and `server.rdb_filename`, it may not purge the old files. I think we can make user drop it themselves.

Another problem is, when a previous task is running, should `config` waiting for it or just grab the `rdb` mutex to avoid the tear read and  change the config? And how can I testing it, do we have some hooks for testing in our code?

**Comment by git-hulk** [comment]
> when a previous task is running, should config waiting for it or just grab the rdb mutex to avoid the tear read and change the config? 

Yes, we have the backup mutex to prevent concurrent creating backup, can see: https://github.com/apache/incubator-kvrocks/blob/unstable/src/storage/storage.cc#L334

> And how can I testing it, do we have some hooks for testing in our code?

No test now, can test locally only if have no good way to add the test case.

**Comment by mapleFU** [comment]
@git-hulk Seems making `backup_dir_` guarded by `backup_mu_`, though `backup_mu_` is too coarse( `DestoryDB` and `rocksdb::Checkpoint::Create` in `backup_mu_` is heavy ).
I will add a patch for implement and testing `backup-dir`, and not change the scope of `backup_mu_`, you can assign this issue to me

**Comment by git-hulk** [comment]
@mapleFU assigned, thanks! 

> Seems making backup_dir_ guarded by backup_mu_, though backup_mu_ is too coarse( DestoryDB and rocksdb::Checkpoint::Create in backup_mu_ is heavy ).

Yes, but I think it can avoid the backup mutex by copying `backup_dir_` variable instead of the reference.
