### ISSUE TITLE
Missing Docker image for v2.1.0

### ISSUE THREAD

**Issue by kinoute** [apache/kvrocks#1010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

I am looking for the Docker image on the Hub for the version 2.1.0.

### Solution

Build, tag and push the image of the version v2.1.0 here https://hub.docker.com/r/kvrocks/kvrocks/tags

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
We only make a source release for 2.1.0 as it's the first Apache release and we're going through the process.

@git-hulk however, since there're quite a few users who want to use 2.1.0 via docker image, perhaps we can stage and vote for a docker image release specifically.

**Comment by git-hulk** [comment]
@tisonkun Yes, but I'm not clear about where to place the docker image, since seems the apache organization in DockerHub is out of seat: [About docker image release and license
](https://lists.apache.org/thread/hfg1h5yrz2bs1d20vq7lm669wcjsfcp1). I'm wondering if it's ok to release in Kvrocks organization after passing the voting process.

**Comment by tanruixiang** [comment]
> @tisonkun Yes, but I'm not clear about where to place the docker image, since seems the apache organization in DockerHub is out of seat: [About docker image release and license ](https://lists.apache.org/thread/hfg1h5yrz2bs1d20vq7lm669wcjsfcp1). I'm wondering if it's ok to release in Kvrocks organization after passing the voting process.

I noticed that doris is still updating images on dockerhub. Can we continue to update images on dockerhub like they do? Maybe we need some process to put kvrocks into apache organization in dockerhub.

https://hub.docker.com/r/apache/doris

**Comment by git-hulk** [comment]
@tanruixiang Yes, the best choice is to place in apache organization, but looks it's out of seat now.

**Comment by tisonkun** [comment]
@git-hulk Pulsar and Flink both use their own dockerhub entry to release images so I think it's OK for now.

You can also file a ticket on [the INFRA JIRA project](https://issues.apache.org/jira/projects/INFRA) to ask for permissions login the apache org and release the docker images there.

**Comment by git-hulk** [comment]
> @git-hulk Pulsar and Flink both use their own dockerhub entry to release images so I think it's OK for now.
> 
> You can also file a ticket on [the INFRA JIRA project](https://issues.apache.org/jira/projects/INFRA) to ask for permissions login the apache org and release the docker images there.

okay, thanks. Will do it today.

**Comment by tanruixiang** [comment]
> @tanruixiang Yes, the best choice is to place in apache organization, but looks it's out of seat now.

I understand now. I'm sorry I misunderstood your meaning before. I noticed that the `linkis` community who asked this question uses an alternative to the github registry.

https://github.com/orgs/apache/packages?repo_name=incubator-linkis

**Comment by PragmaTwice** [comment]
> > @tanruixiang Yes, the best choice is to place in apache organization, but looks it's out of seat now.
> 
> I understand now. I'm sorry I misunderstood your meaning before. I noticed that the `linkis` community who asked this question uses an alternative to the github registry.
> 
> https://github.com/orgs/apache/packages?repo_name=incubator-linkis

Sure, we can use github package registry, but I prefer dockerhub since
```sh
docker run -it apache/kvrocks # or kvrocks/kvrocks
```
is shorter than
```sh
docker run -it ghcr.io/apache/incubator-kvrocks
```
🤣
