### ISSUE TITLE
Flaky test "kill normal client"

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#1014]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

```
--- FAIL: TestIntrospection (3.80s)
    --- FAIL: TestIntrospection/Kill_normal_client (0.00s)
        introspection_test.go:120: 
            	Error Trace:	/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/introspection/introspection_test.go:120
            	Error:      	Not equal: 
            	            	expected: int(1)
            	            	actual  : int64(2)
            	Test:       	TestIntrospection/Kill_normal_client
```

https://github.com/apache/incubator-kvrocks/actions/runs/3286622831/jobs/5414949088

### Solution

Perhaps we should tolerate 1 or 2.

@vmihailenco is this behavior related to go-redis auto reconnecting?

cc @git-hulk 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Related test code:

```go
	t.Run("Kill normal client", func(t *testing.T) {
		defer func() { rdb = srv.NewClient() }()

		c := srv.NewClient()
		defer func() { require.NoError(t, c.Close()) }()
		r := c.Do(ctx, "CLIENT", "SETNAME", "normal")
		require.NoError(t, r.Err())
		require.Equal(t, "OK", r.Val())
		require.Regexp(t, ".*name=normal.*", rdb.ClientList(ctx).Val())

		require.EqualValues(t, 1, rdb.ClientKillByFilter(ctx, "skipme", "yes", "type", "normal").Val())
		require.EqualValues(t, 1, rdb.ClientKillByFilter(ctx, "skipme", "no", "type", "normal").Val())

		// reconnect
		require.NoError(t, rdb.Close())
		rdb = srv.NewClient()

		// now the client should no longer be listed
		require.Eventually(t, func() bool {
			r := rdb.ClientList(ctx).Val()
			return !strings.Contains(r, "normal")
		}, 5*time.Second, 100*time.Millisecond)
	})
```

**Comment by vmihailenco** [comment]
>@vmihailenco is this behavior related to go-redis auto reconnecting?

Probably not, but ClientKillByFilter with `"skipme", "no"` could be retried, but that is just a guess.

**Comment by tisonkun** [comment]
@vmihailenco Thanks for your information! @git-hulk is digging with network traffic now..

**Comment by git-hulk** [comment]
Yes, @vmihailenco is right, I can't find the reconnect behavior after being killed. And as mentioned in #1020, it may be caused by the duplicate count and killed in the Kvrocks server. Many thanks for your help.
