### ISSUE TITLE
Flaky Test TestSlotMigrateFromSlave

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#1016]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

```
--- FAIL: TestSlotMigrateFromSlave (2.36s)
    server.go:106: 
        	Error Trace:	/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/server.go:106
        	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/server.go:112
        	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/server.go:101
        	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:47
        	            				/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:65
        	Error:      	Received unexpected error:
        	            	signal: aborted (core dumped)
        	Test:       	TestSlotMigrateFromSlave
FAIL
```

### Solution

Perhaps we should upload server output on test failures? cc @PragmaTwice 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
https://github.com/apache/incubator-kvrocks/actions/runs/3288512905/jobs/5418990199

**Comment by git-hulk** [comment]
Looks crash after sending the terminate signal, but have no idea to reproduce it.

**Comment by git-hulk** [comment]
https://github.com/apache/incubator-kvrocks/actions/runs/3314140570/jobs/5474097740 Another flaky case

**Comment by tisonkun** [comment]
@git-hulk they're somehow different issues - not the exact failure cause, or not the exact test case:

```
--- FAIL: TestSlotMigrateDataType (85.48s)
    --- FAIL: TestSlotMigrateDataType/MIGRATE_-_Migrate_incremental_data_via_parsing_and_filtering_data_in_WAL (60.85s)
        slotmigrate_test.go:703: 
            	Error Trace:	/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:703
            	            				/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:625
            	Error:      	Condition never satisfied
            	Test:       	TestSlotMigrateDataType/MIGRATE_-_Migrate_incremental_data_via_parsing_and_filtering_data_in_WAL
FAIL
exit status 1
```

```
--- FAIL: TestPubSub (1.20s)
    server.go:106: 
        	Error Trace:	/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/pubsub/server.go:106
        	            				/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/pubsub/server.go:112
        	            				/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/pubsub/server.go:101
        	            				/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/pubsub/pubsub_test.go:369
        	Error:      	Received unexpected error:
        	            	signal: abort trap
        	Test:       	TestPubSub
FAIL
exit status 1
```

**Comment by git-hulk** [comment]
> @git-hulk they're somehow different issues - not the exact failure cause, or not the exact test case:
> 
> ```
> --- FAIL: TestSlotMigrateDataType (85.48s)
>     --- FAIL: TestSlotMigrateDataType/MIGRATE_-_Migrate_incremental_data_via_parsing_and_filtering_data_in_WAL (60.85s)
>         slotmigrate_test.go:703: 
>             	Error Trace:	/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:703
>             	            				/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/integration/slotmigrate/slotmigrate_test.go:625
>             	Error:      	Condition never satisfied
>             	Test:       	TestSlotMigrateDataType/MIGRATE_-_Migrate_incremental_data_via_parsing_and_filtering_data_in_WAL
> FAIL
> exit status 1
> ```
> 
> ```
> --- FAIL: TestPubSub (1.20s)
>     server.go:106: 
>         	Error Trace:	/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/pubsub/server.go:106
>         	            				/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/pubsub/server.go:112
>         	            				/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/pubsub/server.go:101
>         	            				/Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/pubsub/pubsub_test.go:369
>         	Error:      	Received unexpected error:
>         	            	signal: abort trap
>         	Test:       	TestPubSub
> FAIL
> exit status 1
> ```

Yes, for the `TestPusSub` test case, it should be the same with [TestSlotMigrateFromSlave](https://github.com/apache/incubator-kvrocks/issues/1016#top), there're core when exiting the server.

**Comment by tisonkun** [comment]
@git-hulk I'm thinking of uploading the log files if there's a test failure...Don't have a concrete plan yet, though.

**Comment by git-hulk** [comment]
I'm also thinking how to download the log file if it cored
