### ISSUE TITLE
Move docker image to  the Apache organization

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1019]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Currently, we're holding the Kvrocks docker image in the personal repo and Apache infra has created the repo for [Kvrocks](https://hub.docker.com/r/apache/kvrocks), so I think we can move the nightly docker image to the apache organization and then also release tag after knowing how to meet the apache requirements.

### Solution

Push to apache/kvrocks instead of kvrocks/kvrocks after building the docker image.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
cc @tisonkun @torwig @ShooterIT @caipengbo

**Comment by torwig** [comment]
Are there any drawbacks for end users if the image will be pushed to another repository?
Can we keep the `kvrocks` image in both repositories for some time? Or it is useless?

**Comment by git-hulk** [comment]
> Are there any drawbacks for end users if the image will be pushed to another repository? Can we keep the `kvrocks` image in both repositories for some time? Or it is useless?

Yes, agree we can keep both repositories for some time and the only drawback should be history images can't be seen in the new organization.

**Comment by ShooterIT** [comment]
+1.

I am not sure we could keep both repositories, since we have donated this  project into apache.

**Comment by git-hulk** [comment]
> +1.
> 
> I am not sure we could keep both repositories, since we have donated this project into apache.

😭 it will affect users whose using the old image if we can't keep the both for some time.

**Comment by tisonkun** [comment]
@git-hulk I think that we can host Apache releases in the apache org while leaving the previous ones as is.

Similar decisions: https://github.com/apache/pulsar-helm-chart/pull/301#discussion_r998937325

**Comment by git-hulk** [comment]
Thanks @tisonkun

**Comment by PragmaTwice** [comment]
I think we can firstly vote and release the docker image for kvrocks 2.1.0 in the apache org.

And leave a message in kvrocks/kvrocks like "move to apache/kvrocks for new stable versions".

**Comment by kinoute** [comment]
@PragmaTwice That would be great

**Comment by git-hulk** [comment]
@PragmaTwice Do you have time to drive this voting process recently?

**Comment by PragmaTwice** [comment]
> @PragmaTwice Do you have time to drive this voting process recently?

Sure. I will do it recently.

**Comment by git-hulk** [comment]
Cool, thanks~

**Comment by tisonkun** [comment]
I think this issue can be closed as completed now?

**Comment by git-hulk** [comment]
nightly image is still in kvrocks organization, will do it soon.
