### ISSUE TITLE
Proposal: New encoding with compatibility to old data

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1033]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

[The current encoding](https://kvrocks.apache.org/docs/Design/design-structure-on-rocksdb) of kvrocks has several notable problems:
1. The length of `size` field is 32 bits, which makes it impossible to store large collection exceeding `4Gi` (items);
2. The length of `expire` field is 32 bits, which means that kvrocks has the Y2038 problem, i.e. kvrocks will lose availability in 2038.

### Solution

Since currently the higher 4 bits of `flags` field are still unused, we will use one of them to distinguish between the old encoding and the new one, i.e. 
```
 0 0 0 0 <4-bit redis-type> -> old encoding
 1 0 0 0 <4-bit redis-type> -> new encoding
```

The new protocol uses fixed 64bit and varint encoding to represent `expire` and `size` field, and all other fields remain the same as before. In this way, the new protocol can be extended to 64bit (or even higher) to solve the above two problems without significantly increasing the space ~~(actually shrinking, because for small number, 4 bytes are not needed to storage).~~

In fact, I discussed this solution with @torwig in slack before, but only considered the `size` field and used fixed-length 64bit encoding. But now I think varint encoding might be a better fit. ~I do not know if the `version` field is suitable for varint encoding, so some advice might be needed.~

For example, the new hash metadata:
```
        +------------------+------------+-----------+-----------+
key =>  |  flags           |  expire    |  version  |  size     |
        |(1000 + 4bit type)| (64bit ms) |  (64bit)  | (64bit)   |
        +------------------+------------+-----------+-----------+
```

The old hash metadata just for compare:
```
        +------------------+------------+-----------+-----------+
key =>  |  flags           |  expire    |  version  |  size     |
        |(0000 + 4bit type)| (32bit sec)|  (64bit)  | (32bit)   |
        +------------------+------------+-----------+-----------+
```

Note that we store millisecond timestamp in the new `expire` field.

In implementation, we can read data with both old and new encoding, and **always write data by the new encoding**.

cc @git-hulk @torwig @ShooterIT @caipengbo 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Cool, thanks for @PragmaTwice great proposal 

For the `version` is always 64 bits now, so it's ok to use fixed bits.

**Comment by mapleFU** [comment]
I dislike the idea that using varint to store `expire`. The `varint` is sutable for "value tends to be small", maybe suitable for size, but using it as timestamp may be both harms cpu and storage.

32bits' size is ok in most cases.

**Comment by mapleFU** [comment]
Personally, I think it's even ok to extend `flags`:

```
if flags's MSB is 1, extent flag to 2bytes or more
flag represent expire and size's size
```

**Comment by PragmaTwice** [comment]
> I dislike the idea that using varint to store `expire`. The `varint` is sutable for "value tends to be small", maybe suitable for size, but using it as timestamp may be both harms cpu and storage.
> 
> 32bits' size is ok in most cases.

For a recently timestamp (~2022 AD), the value is about 2^31. If using varint encoding, the data will be about 5 bytes, which is less than 8 bytes.

Although I am open for this, it can be fixed 8 bytes. But I think the size field need to be varint encoded in the new encoding.

**Comment by mapleFU** [comment]
> Although I am open for this, it can be fixed 8 bytes. But I think the size field need to be varint encoded in the new encoding.

By the way, in most of cases, `meta` would not be the bottleneck of store and cpu. When it comes to `String`, changing it to varint would occupy more spaces and spend more time paring the value.

**Comment by PragmaTwice** [comment]
> > Although I am open for this, it can be fixed 8 bytes. But I think the size field need to be varint encoded in the new encoding.
> 
> By the way, in most of cases, `meta` would not be the bottleneck of store and cpu. When it comes to `String`, changing it to varint would occupy more spaces and spend more time paring the value.

I got your point. I will change `expire` field from varint to fixed 8bit.

**Comment by tisonkun** [comment]
This can be related to #983 that we're storing TTL in seconds now so that it cannot reflect more fine-grained precision.

**Comment by PragmaTwice** [comment]
The encoding description is now updated.

**Comment by torwig** [comment]
I like the updated encoding description (especially because I was asking about the size field but didn't have time to implement it).

**Comment by PragmaTwice** [comment]
> This can be related to #983 that we're storing TTL in seconds now so that it cannot reflect more fine-grained precision.

Good point. We can use millisecond timestamp in the new `expire` field.
