### ISSUE TITLE
rename commands don't work

### ISSUE THREAD

**Issue by iushas** [apache/kvrocks#1040]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.1.0

### Minimal reproduce step

1、add rename-command in kvrocks.conf
rename-command flushall                             dont_run_flushall_rudely
rename-command flushdb                             dont_run_flushdb_rudely
rename-command bgsave                              dont_run_bgsave_rudely
rename-command config                               dont_run_config_rudely
2、start kvrocks

3、exec dont_run_bgsave_rudely
127.0.0.1:6379> dont_run_bgsave_rudely
(error) ERR unknown command dont_run_bgsave_rudely

exec dont_run_config_rudely   can success

127.0.0.1:6379> config get rename-command
1) "rename-command"
2) "config                              dont_run_config_rudely"

as it shows in config info，only dont_run_config_rudely effects。

4、exec config rewrite
127.0.0.1:6379> dont_run_config_rudely rewrite
OK
127.0.0.1:6379> dont_run_config_rudely get rename-command
1) "rename-command"
2) "config                              dont_run_config_rudely"

but rename-commands in kvrocks.conf still are old contents.
root@redis-kvsenior01-290192:/home/redis/etc# grep rename /home/redis/data/conf/kvrocks.conf
# rename
# rename
rename-command flushall                             dont_run_flushall_rudely
rename-command flushdb                             dont_run_flushdb_rudely
rename-command bgsave                              dont_run_bgsave_rudely
...
rename-command config                              dont_run_config_rudely

### What did you expect to see?

all rename commands can work

### What did you see instead?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@iushas Thanks for your feedback!
