### ISSUE TITLE
When log-dir and backup-dir appear at the same time, log-dir does not take effect

### ISSUE THREAD

**Issue by manchurio** [apache/kvrocks#1059]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable branch.
This bug was introduced on October 24.
https://github.com/apache/incubator-kvrocks/blob/684bcc6ce7060ab507627b8299b8326e9ffbf133/src/config/config.cc#L357-L359

### Minimal reproduce step

There are two ways to reproduce

1. Using the command flags
./kvrocks --log-dir /data/log --backup-dir /data/backup

2. Use configuration files(kvrocks.conf)
backup-dir /data/kvrocks/backup
log-dir /data/log

### What did you expect to see?

Log appears in /data/log

### What did you see instead?

Log appears in /tmp

### Anything Else?

If backup-dir appears, It will trigger the execution of this line of code.
https://github.com/apache/incubator-kvrocks/blob/684bcc6ce7060ab507627b8299b8326e9ffbf133/src/config/config.cc#L357-L359

Just remove this line and the bug will be fixed.
Or we reinitialize glog,because macro LOG will  initialize a singleton object before setting the log location.

https://github.com/google/glog/blob/05fbc65278db1aa545ca5cb743c31bc717a48d0f/src/logging.cc#L930-L940

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
@manchurio I have tried to fix this via #1061 , would you like to have a try?
