### ISSUE TITLE
Doubt about the HRANGE command

### ISSUE THREAD

**Issue by ShooterIT** [apache/kvrocks#1082]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Currently, we implement HRANGE command, but i think the name is not suitable.

For zset, we have `ZRANGEBYLEX` which could get members with lexicographical ordering,
of course, `ZRANGE` has `BYLEX` option.
HRANGE also get fields with lexicographical ordering, so i think its name should be
`HRANGEBYLEX` aligned with `ZRANGEBYLEX`. If we use `HRANGE`, users may think it is
similar with `ZRANGE` which `start` and `stop` are the position in it.

What's more, i think the `min` and `max` arguments of `HRANGE` should start with
( or [, in order to specify if the range item is respectively exclusive or inclusive, also align
with `ZRANGEBYLEX`

### Solution

I suggest to change its name to `HRANGEBYLEX` and the `min` and `max` arguments of it
should start with `(` or `[` 

of course, we can implement `HRANGE` command with different options, but now, i think it
is not urgent since there is no demand of HRANGE(the same semantic of ZRANGE).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
This is an excellent proposition, from my side, I think the HRANGE command is similar to ZRANGE over ZRANGEBYLEX, so I regarded those parameters as `start` and `stop` when reviewing the PR. But I'm wondering if it's right to align them because ZSET is a sorted array and it makes sense to use the index as the start/stop but it's a bit confusing for HASH.

**Comment by PragmaTwice** [comment]
Good point, currently `ZRANGE` and `HRANGE` have different semantics (indexes v.s. elements) and argument types (integers v.s. strings), so I also think `ZRANGEBYLEX` is more concrete.

BTW cc @tanruixiang

**Comment by tanruixiang** [comment]
I also misunderstood `start` and `stop` when I first started implementing `HRANGE`.I'll add `hrange` and `hrangebylex` this weekend.

**Comment by tanruixiang** [comment]
> I also misunderstood `start` and `stop` when I first started implementing `HRANGE`.I'll add `hrange` and `hrangebylex` this weekend.

**Comment by git-hulk** [comment]
@tanruixiang Any update?

**Comment by tanruixiang** [comment]
> @tanruixiang Any update?

I'm sorry for the long absence of updates due to illness. I will continue this work this weekend.

**Comment by git-hulk** [comment]
@tanruixiang Thanks for your feedback. No hurry, I'm just wondering if I missed anything.
