### ISSUE TITLE
[NEW] Add `SINTERCARD` command aligned Redis

### ISSUE THREAD

**Issue by boatrainlsz** [apache/kvrocks#1083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

add support for [SINTERCARD](https://redis.io/commands/sintercard/) command in Redis, which is available since Redis 7.0.0

### Solution

Since `SINTER` and `SCARD` were implemented already, I think it's quite straightforward to combine those two commands' logic.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@boatrainlsz Thanks, assigned.
