### ISSUE TITLE
Add support for migrating STREAM in cluster mode

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

The STREAM type(partial commands) is supported in #745, but didn't add support for migrating in the cluster mode.

For more detail can see: https://github.com/apache/incubator-kvrocks/blob/unstable/src/cluster/slot_migrate.cc#L617

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by torwig** [comment]
@git-hulk I'll try to implement this.

**Comment by git-hulk** [comment]
> @git-hulk I'll try to implement this.

cool, thanks @torwig
