### ISSUE TITLE
command compact turn to be unknown command after rename compact to xxx

### ISSUE THREAD

**Issue by iushas** [apache/kvrocks#1127]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

All version 

### Minimal reproduce step

1. add rename config into config file
 ```
rename-command compact                             _dont_run_compact_rudely
```
2. exce compact or _dont_run_compact_rudely
```
127.0.0.1:6379> _dont_run_compact_rudely
(error) ERR unknown command _dont_run_compact_rudely
```

compacion_checker can worker well，
![image](https://user-images.githubusercontent.com/7236171/202422151-658f5d3f-89a3-40b4-a3fc-9a071b954a19.png)

### What did you expect to see?

compact can be executed manual after rename 

### What did you see instead?

UP

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@iushas That's a known bug and it's fixed in #1047. Good news is @PragmaTwice has called the release vote in Apache community, 2.2.0 will be coming tonight if no further objection.

**Comment by PragmaTwice** [comment]
@iushas Hi, you can try docker image apache/kvrocks:2.2.0 and see if it is solved. It is a prerelease now but will be an official release soon.

**Comment by iushas** [comment]
thans @git-hulk  and @PragmaTwice ， it's normal in 2.2.0。 Looking forward to the official release！

**Comment by git-hulk** [comment]
> thans @git-hulk and @PragmaTwice ， it's normal in 2.2.0。 Looking forward to the official release！

@iushas New release is available now.
