### ISSUE TITLE
Move VERSION file to src folder

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#1148]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Move `VERSION` file to `src` folder, so that we have a tidy root layout.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
You should correspondingly update the build logic to fulfill VERSION information, including those in `x.py` and `CMakeList.txt`.

**Comment by PragmaTwice** [comment]
Actually I have some doubt about this proposal. In my view, the `VERSION` file is not a source file, which seems not proper to be placed into the `src` directory.

We can see the CI failed when someone try to move this file to `src` in #1149, whose reason is quite funny: there is a header named `version` in the C++ standard, and the move cause compiler to find wrong header and fail to compile.
