### ISSUE TITLE
Support deleting old logs by day

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1168]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Currently, Kvrocks didn't have a way to auto-delete old logs which may occupy the disk capacity, so it'd be better to offer a way to keep recent logs only. 

related discussion: https://github.com/apache/incubator-kvrocks/discussions/1167

### Solution

We can do it by simply adding a configuration to enable or disable it since the glog has already supported removing old logs.

https://github.com/google/glog/blob/c18db3903b9f0abd80ae740fde94f7e32aa40b92/README.rst#automatically-remove-old-logs

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by IoCing** [comment]
I would like to work on it !

**Comment by git-hulk** [comment]
Thanks @IoCing, assigned
