### ISSUE TITLE
SLAVEOF command may block a long time

### ISSUE THREAD

**Issue by caipengbo** [apache/kvrocks#1170]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.2.0

### Minimal reproduce step

1. `echo 6 > /proc/sys/net/ipv4/tcp_syn_retries`
2. `SLAVEOF` a non-routable IP address(such as `10.255.255.1`)
3. `SLAVEOF new_master_ip port`

### What did you expect to see?

Step 3 should not block for a long time because we are switching to the new master, which should be a quick operation.

### What did you see instead?

Step 3 will block a long time(**> 2min** based on above reproduced scenario)

### Anything Else?

This is because we use blocking IO when use socket [connect(2)](https://man7.org/linux/man-pages/man2/connect.2.html). In some cases, `connect(2)` will be blocked for a long time.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@caipengbo I think the root cause is we didn't set a timeout for the connect operation, so it will backoff retransmit the syn packet(1s,2s,4s,8s,16s,32s,64s) until reaching the `tcp_syn_retries`(default is 6 for most Linux distro).

**Comment by caipengbo** [comment]
> @caipengbo I think the root cause is we didn't set a timeout for the connect operation, so it will backoff retransmit the sync packet(1s,2s,4s,8s,16s,32s,64s) until reaching the tcp_syn_retries(default is 6 for most Linux distro). 

Yes, we should add a timeout.

**Comment by git-hulk** [comment]
Cool, got it.

**Comment by caipengbo** [comment]
Let's set it a little longer than 3 seconds, so we can tolerate 2 times lost sync packages? @git-hulk

**Comment by git-hulk** [comment]
Yes, sounds good to me.
