### ISSUE TITLE
Add disablelogclean command to close 

### ISSUE THREAD

**Issue by IoCing** [apache/kvrocks#1204]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

At present, we can enable logclean by configuring log-retention-days. but we can't disable logclean except reboot with  set log-retention-days to -1

### Solution

we can add a new command to disable logclean by calling `google::DisableLogCleaner()`.
we also can add more options to dynamically configure log-retention-day.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Maybe I made an oversight during the code review of #1171, since I thought that the previous PR was able to do this by sending `config set log-retention-days -1` from a kvrocks client.

**Comment by IoCing** [comment]
> config set log-retention-days -1

oh , i get it  ,We have implemented it in the callback.

I forgot the config command.
