### ISSUE TITLE
tip bug for: zrangebylex

### ISSUE THREAD

**Issue by lt1946** [apache/kvrocks#1210]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

latest

### Minimal reproduce step

latest

### What did you expect to see?

value1 , value2 , value3

### What did you see instead?

zadd(key, 1f, "value1");
zadd(key, 2f, "value2");
zadd(key, 3f, "value3");
zadd(key, 4f, "value4");
zadd(key, 5f, "value5");
zadd(key, 6f, "value6");
zadd(key, 7f, "value7");
zadd(key, 8f, "value8");
zadd(key, 9f, "value9");
zadd(key, 10f, "value10");

zrangebylex(key, "-", "[value3");

will get result: value1 , value2 , value3 , value10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ShooterIT** [comment]
it should not be a bug.
i think the result is `value1 , value10, value2 , value3 `, the Lexicographic order of `value10` is less than `value2`
