### ISSUE TITLE
new bug for: sscan

### ISSUE THREAD

**Issue by lt1946** [apache/kvrocks#1211]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

latest

### Minimal reproduce step

check redis command.

### What did you expect to see?

if count==0 ,return ok! and for count!=0.

### What did you see instead?

SSCAN with COUNT >0 , retrun error.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by torwig** [comment]
Hi @lt1946 , could you provide more info about your case? What is the error message?
I just executed the following:
```
127.0.0.1:6666> sadd set1 10 20 30 40 50 60 80 80 40 50 20
(integer) 11
127.0.0.1:6666> sscan set1 0 count 10
1) "0"
2) 1) "10"
   2) "20"
   3) "30"
   4) "40"
   5) "50"
   6) "60"
   7) "80"
```
In this case, `count` is greater than 0 and there is no error.

**Comment by git-hulk** [comment]
Close this issue since it has no further feedback. Feel free to reopen if you have any questions or feedback.
