### ISSUE TITLE
error command for:   georadius

### ISSUE THREAD

**Issue by lt1946** [apache/kvrocks#1213]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

latest

### Minimal reproduce step

example at : [https://redis.io/commands/georadius/](url)
redis> GEOADD Sicily 13.361389 38.115556 "Palermo" 15.087269 37.502669 "Catania"
(integer) 2

### What did you expect to see?

redis> GEORADIUS Sicily 15 37 200 km WITHDIST WITHCOORD
 
2) 1) "Catania"
   2) "56.4413"

### What did you see instead?

Expected :56.4413
Actual   :3.479447370796909E15

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@lt1946 Thanks for your report, but I can't reproduce the bug with your steps.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/4987594/209893891-e89d3a5c-4056-4d56-8d1c-66fbf4b647ab.png">
