### ISSUE TITLE
Persist the cluster nodes info in cluster mode

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1216]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Currently, the cluster nodes' topology is stored in memory and we need to re-sync the cluster topology to every node after restarting. There are a bit inconvenient and confusing for many users even though it's the design intention. So I think we can persist the cluster topology info in the local file to avoid re-syncing if it's unchanged.

### Solution

Dump the nodes' info into the local file, then load this file if exists.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
What's the different between this issue and https://github.com/apache/incubator-kvrocks/issues/1021 ?

**Comment by git-hulk** [comment]
@mapleFU Thanks for your reminder! I forgot we already have this issue, let's close it.
