### ISSUE TITLE
ASan/TSan does not work well with JeMalloc

### ISSUE THREAD

**Issue by xiaobiaozhao** [apache/kvrocks#1254]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

Mac  & Ubuntu all versions

### Minimal reproduce step

`./x.py build --unittest --compiler gcc -DDISABLE_JEMALLOC=ON -DENABLE_TSAN=ON`
`./x.py build --unittest --compiler gcc -DDISABLE_JEMALLOC=ON -DENABLE_ASAN=ON`

### What did you expect to see?

build succeed

### What did you see instead?

./x.py build --unittest --compiler gcc -DDISABLE_JEMALLOC=ON -DENABLE_TSAN=ON
$ /usr/bin/cmake /root/work/incubator-kvrocks -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_TSAN=ON
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:67 (message):
  **### ASan/TSan does not work well with JeMalloc**

-- Configuring incomplete, errors occurred!
See also "/root/work/incubator-kvrocks/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/root/work/incubator-kvrocks/./x.py", line 397, in <module>
    args.func(**arg_dict)
  File "/root/work/incubator-kvrocks/./x.py", line 122, in build
    run(cmake, str(basedir), *cmake_options, verbose=True, cwd=dir)
  File "/root/work/incubator-kvrocks/./x.py", line 68, in run
    raise RuntimeError(err)
RuntimeError: 
failed to run: ('/usr/bin/cmake', '/root/work/incubator-kvrocks', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_C_COMPILER=gcc', '-DCMAKE_CXX_COMPILER=g++', '-DENABLE_TSAN=ON')
exit with code: 1

### Anything Else?

I also test  `./x.py build --unittest --compiler gcc -DDISABLE_JEMALLOC=ON -DENABLE_TSAN=ON -DENABLE_OPENSSL=ON` build is OK.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xiaobiaozhao** [comment]
Will this be a feature?  @PragmaTwice

**Comment by git-hulk** [comment]
It's expected behavior, you can have a look at the CMakeList.txt.

**Comment by xiaobiaozhao** [comment]
> 

OK, Thx

**Comment by xiaobiaozhao** [comment]
reopen the issue
