### ISSUE TITLE
Improve the homepage of Kvrocks website

### ISSUE THREAD

**Issue by ColinChamber** [apache/kvrocks#1257]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

The Designer has already pushed the UI design blueprint to [Lanhu](https://lanhuapp.com/link/#/invite?sid=lX0DR86F). Let's move on to the next stage of coding, which will be implemented by Yuqiu Song.

### Solution

I suppose it can be divided to the following tasks.
* [x] Modify the colors of Header and Footer, and update the banner.
* [ ] Refactor introduction of the Redis Compatible feature.
	* [ ] Include a text editor with demo.
	* [ ] Include a pie chart displaying the proportion of implemented Redis commands.
* [x] Add icons and descriptions for four features.
* [ ] Add a list of logos.
* [x] Make the homepage mobile-friendly (optional).
* [ ] Add some animations (optional).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by sendRainAutumn** [comment]
I'm willing to submit a PR

**Comment by ColinChamber** [comment]
FYI @git-hulk @PragmaTwice

**Comment by tisonkun** [comment]
> I'm willing to submit a PR

Can you elaborate a bit on what exactly you're going to implement? I think we can create some subtasks and assign to you.

**Comment by PragmaTwice** [comment]
Hi @SongYuQiu, very much looking forward to your PR! ❤️ 

However, I would like to make a few suggestions:
- As Lanhu is a private collaboration platform, I thought it would be a good idea to post the design (like, in `png` or `jpeg` format) directly in this thread to make it easier for wider community members to view.
- You do not need to do everything in one PR (of course you can if you want), instead, you could try splitting the task into a series of PRs, which would allow the task to be done incrementally and also facilitate the review process.

**Comment by tisonkun** [comment]
![Web 1920 – 9](https://user-images.githubusercontent.com/18818196/218301534-c5a553cb-03c9-4d75-bf36-0f9f129e8d1e.png)

I get a copy of the design from the link. It looks cool and it seems a one-for-all contribution so we may not need subtasks.

Assigned to @SongYuQiu. Feel free to ping me if you need any help.

**Comment by ColinChamber** [comment]
I'm glad to see that the community homepage has been completely refreshed. 

There are still some tasks to be carried out, such as deciding which languages to use for the demo in the text box and what content to demonstrate. We also need to establish a statistical standard and provide the proportion of implemented Redis commands for using in a pie chart. @git-hulk @PragmaTwice 

BTW, I hope that in the next PR, you can swap the icons for Replication and Cluster. This is because the icon with three "K"s is more suitable for introducing the cluster feature. Thank you. @SongYuQiu

**Comment by git-hulk** [comment]
Thanks for @ColinChamber driving this great improvement.

It would be nice if can also fix the layout on the mobile web.

**Comment by ColinChamber** [comment]
The homepage has been updated, thanks to everyone.
