### ISSUE TITLE
when setslot set cluster version just bigger than last version

### ISSUE THREAD

**Issue by segment11** [apache/kvrocks#1260]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

It is easier for controller, the controller can only use one increase bigint sequence for one kvrocks cluster.

### Solution

Change cluster version step+1 check to just bigger than check.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
For `CLUSTERX  setnodes` command, it's right that we don't require to check if the version is continuous since it will fully update the cluster topology. But for the `CLUSTERX setslots`, it's a partial update behavior, so we need to check if the version is +1 to prevent missing some updates.

**Comment by git-hulk** [comment]
@segment11 It's fine to keep this issue since we can allow the `CLUSTERX SETNODES` just check if it's bigger than before.
