### ISSUE TITLE
Support batch fetch rows by key prefix

### ISSUE THREAD

**Issue by segment11** [apache/kvrocks#1261]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Improve performance so it can replace some cases using HBase.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @segment11,

Thanks for your feedback, Kvrocks currently supports the scan command to iterate keys with prefix. Could you help to add more context if it's NOT exactly what you want?

Reference: https://redis.io/commands/scan/

**Comment by segment11** [comment]
I actually want a time series database on rocksdb, and it has replica that can failover.
Take HBase as example, query n rows scan by rowkey，it is just read some hfiles(sstable) because the rowkeys are ordered.

**Comment by git-hulk** [comment]
Currently, the scan keys in Kvrocks are also ordered indeed, so it should be the same as HBase rows scan.
