### ISSUE TITLE
Support fix a unique slot for multi keys with the same prefix

### ISSUE THREAD

**Issue by segment11** [apache/kvrocks#1265]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

So that I can specified some key/value save in the same slot, read more efficient and do transaction easy.

### Solution

For example, keys: my-prefix@@suffix1, my-prefix@@suffix2...
only use my-prefix to do hash and find a slot.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by caipengbo** [comment]
Can hash tag meet your needs?

https://github.com/apache/incubator-kvrocks/blob/e1cc7f68aeb6b649286157b5676631f41936bf27/src/cluster/redis_slot.cc#L67
