### ISSUE TITLE
some key seem to be nil when I execute 'scan 0'

### ISSUE THREAD

**Issue by hlf2016** [apache/kvrocks#1267]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

v2.0.6
![image](https://user-images.githubusercontent.com/24551738/220008257-2ba500b4-cbc3-4979-b85d-c649909fd036.png)

### Minimal reproduce step

I do not know

### What did you expect to see?

the (nil) disappears

### What did you see instead?

the (nil)  exists and can not be deleted

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@hlf2016 I can't get the point and it'd be better to add reproduce steps, or we cannot fix this issue.

**Comment by hlf2016** [comment]
> @hlf2016 I can't get the point and it'd be better to add reproduce steps, or we cannot fix this issue.

I do not know how it appeared
![image](https://user-images.githubusercontent.com/24551738/220048312-43995393-8633-4d2b-ac25-a3e9fb508789.png)

as seen in the picture above

how can I delete the  `(nil)` key

**Comment by git-hulk** [comment]
Hi @hlf2016, thanks for your feedback, it should be related to this issue:https://github.com/apache/incubator-kvrocks/pull/930. Kvrocks will return an empty bulk string(`nil` for redis-cli), you can have a check if you have the empty key name like below:

```
127.0.0.1:6666> get ""
"1"
```
And delete if this key was not expected, then the `nil` will be disappeared.

We will fix this issue soon.

**Comment by hlf2016** [comment]
> Hi @hlf2016, thanks for your feedback, it should be related to this issue:#930. Kvrocks will return an empty bulk string(`nil` for redis-cli), you can have a check if you have the empty key name like below:
> 
> ```
> 127.0.0.1:6666> get ""
> "1"
> ```
> 
> And delete if this key was not expected, then the `nil` will be disappeared.
> 
> We will fix this issue soon.

Yes I once tried this  but it made no effects

![image](https://user-images.githubusercontent.com/24551738/220052372-523471e9-e9b9-415c-99d5-e0b4028b4e62.png)

So any other characters can lead to this ?

**Comment by git-hulk** [comment]
@hlf2016 It means this key exists and it's NOT a string type, you can use `type ""` to inspect the value type.

**Comment by hlf2016** [comment]
> type ""



> @hlf2016 It means this key exists and it's NOT a string type, you can use `type ""` to inspect the value type.

Ok thx very much    
I was totally blinded  
I'm sorry to bother you too much

**Comment by git-hulk** [comment]
> > type ""
> 
> > @hlf2016 It means this key exists and it's NOT a string type, you can use `type ""` to inspect the value type.
> 
> Ok thx very much I was totally blinded I'm sorry to bother you too much

No problem, welcome to join the WeChat community through: https://github.com/apache/incubator-kvrocks#social-media
