### ISSUE TITLE
About multi-language support

### ISSUE THREAD

**Issue by GoodManWEN** [apache/kvrocks#1273]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

First of all love and thanks for your great work. As a developer I am looking for a database that will help me manage a large number of random read and write files. I came across this project about 2 weeks ago,  and kvrocks hit the bull's eye.

As a developer, I'm more concerned with production deployment related issues from a practical point of view. As this was also my first encounter with RocksDB, I'm more interested in how it behaves at the application level specifically comparing to Redis. Because while it is of great interest to reduce the cost with large data store cases, it is more important to ensure that the data is safe and secure at the behavioural level in the first place. I read all the documentation on the official website, which taught me a lot, but the relevant information didn't seem to be enough.

After reading the default configuration file I think it is also necessary to read it in the same way as the documentation. I would like to see multilingual support in the community in order to speed up my reading, but unfortunately it seems that the community has not opened the option to do so, nor has it opened a channel for multilingual translation contributions.

### Solution

Here is a tentative translated version of the profile, which I've post to gist
[kvrocks_config_file_chs_translate.conf](https://gist.github.com/GoodManWEN/47582b4890ee6298f7bd88f986bdb706)

I tried to translate the document into Chinese to speed up the reading for native Chinese speakers, The original text has also been retained in case the translation leads to misunderstandings. I'm sure there are many good contributors to the community who use Chinese, and the only reason there are no translations at the moment is that they may not have the time. And cross-referencing makes reading a little faster for native speakers, which is a bit much to learn for a newbie to be honest.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@GoodManWEN Thanks for your warm proposal, I think it makes a lot of sense to have multi-language documentation. 

@tisonkun @PragmaTwice How about putting them on our official website?

**Comment by tisonkun** [comment]
No. I think it's a good supplement as a community work. We may set up a link (hint) but it would be hard to officially keet it up-to-date. We should leave such efforts third party and no promise unless we're sure it can be up-to-date and improve usability.

**Comment by git-hulk** [comment]
OK, it's good to maintain those third-party links in one place

**Comment by GoodManWEN** [comment]
Glad to hear your response. Talking about the continuous update translation of the configuration file, I personally feel that it's not a work takes take much time, I'm pleased if I could help with the Chinese translation work. However considering this is a kind of work that expertise is more needed than language skills. For example, in my earlier translations I had the problem of not recognizing the abbreviation of what WAL is. Only when I searched did I understand what it meant, maybe I wasn't the right person for the work.

**Comment by git-hulk** [comment]
@GoodManWEN Thanks for your efforts. I will add a page for third-party resources on our website and then link your page here.

**Comment by PragmaTwice** [comment]
Currently, in some cases (like performance tuning), users may be better to learn some knowledge about some concepts in (multi-leveled) LSMT and RocksDB.

I think it is indeed not friendly to new users, so we welcome all contributions towards a more user-friendly documentation.
