### ISSUE TITLE
Enable transaction support for the mset command

### ISSUE THREAD

**Issue by rawvoid** [apache/kvrocks#1277]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Hi, guys

Currently, using the mset command to write data in batches cannot ensure atomicity. We should let the system perform a rollback when the process is interrupted during data writing.

Regard

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Thanks for @tarvfx filing this issue.

**Comment by rawvoid** [comment]
@git-hulk Thanks for you adding this feature to the to do list. In addition, I would like to add that other batch operation instructions other than mset, such as `msetnx`, should all be applicable to this enhanced feature.

**Comment by PragmaTwice** [comment]
Rather than making `mset` atomic, I wonder if it is better to add a new flag to `mset` for atomicity and leave the default behavior align with Redis.

**Comment by git-hulk** [comment]
@PragmaTwice Yes, we won't expect to affect the default behavior of the mset command.

@tarvfx Sure, I will consider those commands together.

**Comment by git-hulk** [comment]
This was resolved in #1634
