### ISSUE TITLE
For the expired key, the TYPE command returns dirty data

### ISSUE THREAD

**Issue by jjz921024** [apache/kvrocks#1278]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

kvrocks v2.3.0

### Minimal reproduce step

```
127.0.0.1:31001> set k v ex 10
OK
127.0.0.1:31001> type k
"string"
127.0.0.1:31001> ttl k
(integer) 3
127.0.0.1:31001> ttl k
(integer) -2
127.0.0.1:31001> type k
"string"
127.0.0.1:31001> get k
(nil)
127.0.0.1:31001> type k
"string"
```

### What did you expect to see?

**None** should been returned for the expired key

### What did you see instead?

For the expired key, the TYPE command returns dirty data

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@jjz921024 Thanks for your good catch.

**Comment by ghost** [comment]
rocksdb has a feature whereby an expired key is not removed immediately but during compaction. If the size of a specific level is not large enough to trigger compaction, the old data remains. Compacting manually is one possible solution, but it may cause write stalls

**Comment by git-hulk** [comment]
Hi @Lericaro

This bug was caused by the type command didn't check the expiry time, and it's OK to recycle those expired items later by compaction.
