### ISSUE TITLE
maybe add a explicit [[fallthough]] is more better to the source readers

### ISSUE THREAD

**Issue by mzygQAQ** [apache/kvrocks#1290]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

maybe add a explicit [[fallthough]] is more better to the source readers

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by mzygQAQ** [comment]
https://github.com/apache/incubator-kvrocks/blob/unstable/src/cluster/replication.cc#L201

**Comment by PragmaTwice** [comment]
Good catch! Would you like to do that?

**Comment by mzygQAQ** [comment]
i will
