### ISSUE TITLE
Enable max_background_jobs

### ISSUE THREAD

**Issue by xiaobiaozhao** [apache/kvrocks#1292]
### Discussed in https://github.com/apache/incubator-kvrocks/discussions/1284

<div type='discussions-op-text'>

<sup>Originally posted by **xiaobiaozhao** February 27, 2023</sup>
Use `max_background_jobs` instead of `max_background_compactions` and `max_background_flushes`

https://github.com/facebook/rocksdb/blob/main/include/rocksdb/options.h#L699</div>

**Comment by bruceqiwang** [comment]
Will do this. Please assign to me.

**Comment by aleksraiden** [comment]
Good idea, it's much more clean to use!

**Comment by zevin02** [comment]
Please assign to me.

**Comment by git-hulk** [comment]
Hi @zevin02, thanks for your attention. 

@bruceqiwang was already working on it, PR #1374
