### ISSUE TITLE
Perform HSETNX with multiple values, just like HSET

### ISSUE THREAD

**Issue by aleksraiden** [apache/kvrocks#1294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

With HSET we can add a multiple key/field at once. But HSETNX, that's insert value only if they does not yet exist, use only one key/field pair at once. 

Could we changed HSETNX for usage with multiple values? 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by aleksraiden** [comment]
This needs for use HSET as append-only storage and optimize performance

**Comment by aleksraiden** [comment]
So, a command will return a count fields (integer replay), that are added to the hash-map or 0, if no data inserted.

@torwig could you provide a PR if this feature can be added? Lot of thanks!

**Comment by git-hulk** [comment]
It looks like this is a good feature, to see if @torwig or someone else would like to handle this.

**Comment by torwig** [comment]
@git-hulk Sure, I can implement this feature.

**Comment by git-hulk** [comment]
Thanks @torwig
