### ISSUE TITLE
Special symbols in the configuration of kvrocks2redis 

### ISSUE THREAD

**Issue by QQxiaoyuyu** [apache/kvrocks#1295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

The password configuration of kvrocks2redis does not support special symbols. My password contains (, #,). After the configuration is completed, some passwords are truncated, resulting in failure to connect to the database, 

### Minimal reproduce step

Password contains#

### What did you expect to see?

I hope that passwords containing all special characters can be configured for use

### What did you see instead?

E20230302 15:20:17.083904  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.099448  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.115800  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.132504  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.148733  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.166213  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.182044  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.206648  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.339524  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.362785  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.412103  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.474309  9563 sync.cc:78] auth got invalid response
E20230302 15:20:17.541461  9563 sync.cc:78] auth got invalid response

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
AFAIK it is an expected behavior:

The symbol `#` stands for the start of comments, e.g.
```
pass 123 # this is a comment, password is 123
pass "123#456" # password is 123#456
```

So if the value contains `#`, it is expected to be quoted.

I will close this issue if no further problems.

**Comment by QQxiaoyuyu** [comment]
Try the following password:    xxxx-&$(#(xxxxxxxxxxxxx))

**Comment by QQxiaoyuyu** [comment]
It's strange that I deleted the original data and can start it again. Printing is normal, but there is no connection to kvrocks2redis on src kvrocks 
After starting kv2redis, print as follows:

Log file created at: 2023/03/02 17:42:23
Running on machine: bj-lsy-205
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
I20230302 17:42:23.643076  1473 storage.cc:335] [storage] Success to load the data from disk: 11 ms
I20230302 17:42:23.643364  1473 sync.cc:65] [kvrocks2redis] Start sync the data from kvrocks to redis

But the server side is not connected

**Comment by QQxiaoyuyu** [comment]
1. Purpose: test whether there is any bad effect after upgrading kvrocks from 2.0.6 to 2.3. Therefore, it is necessary to import data from other kvrocks to test kvrocks 2.0.6

2. Environmental preparation

target-kv centos7.9 kernel-version linux-5.4.149

src-kv centos7.9 kernel-version linux-4.4.246

kvrocks2redis cenots7.9 kernel-version linux-5.4.149

3. Procedure

1) First compile kvrocks-2.3 on target-kv

2) Copy the compiled kvrocks2redis to kvrocks2redis

3) Copy kvrocks-2.0.6 to target-kv from src-kv, set the password x -&$(# (x)) and start

4) Configure the configuration file in kvrocks2redis, and set the source database and destination database passwords to x -&$(# (x))

5) Observe the print of the kvrocks2redis log, as follows

**Comment by QQxiaoyuyu** [comment]
E20230302 17:54:58.782781  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.783305  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.783797  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.784637  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.785199  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.785708  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.786188  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.787199  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.787710  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.788219  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.788702  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.789242  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.789800  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.790282  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.790824  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.791289  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.791800  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.792301  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.792833  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.793253  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.793803  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.794323  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.794811  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password
E20230302 17:54:58.795357  5467 redis_writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

**Comment by QQxiaoyuyu** [comment]
1. Purpose: test whether there is any bad effect after upgrading kvrocks from 2.0.6 to 2.3. Therefore, it is necessary to import data from other kvrocks to test kvrocks 2.0.6

2. Environmental preparation

target-kv centos7.9 kernel-version linux-5.4.149

src-kv centos7.9 kernel-version linux-4.4.246

kvrocks2redis cenots7.9 kernel-version linux-5.4.149

3. Procedure

1) First compile kvrocks-2.3 on target-kv

2) Copy the compiled kvrocks2redis to kvrocks2redis

3) Copy kvrocks-2.0.6 to target-kv from src-kv, set the password cceq -&$(# (KAfds) and start

4) Configure the configuration file in kvrocks2redis, and set the source database and destination database passwords to cceq -&$(# (KAfds)

5) Observe the print of the kvrocks2redis log, as follows:

E20230302 17:54:58.802428 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.802887 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.803411 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.803925 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.804463 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.804945 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.805450 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.805927 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.806439 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.806947 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.807446 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 17:54:58.807932 5467 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

6) Kill kv2redis and change the password of target-kv to tuiyi2023kvrockst

7) Restart kv2reids and observe the log printing as follows:

E20230302 18:06:49.413501 9068 sync.cc:78] auth got invalid response

E20230302 18:06:49.665562 9068 sync.cc:78] auth got invalid response

E20230302 18:06:49.809759 9068 sync.cc:78] auth got invalid response

E20230302 18:06:49.961756 9068 sync.cc:78] auth got invalid response

E20230302 18:06:50.253381 9068 sync.cc:78] auth got invalid response

E20230302 18:06:50.799962 9068 sync.cc:78] auth got invalid response

E20230302 18:06:50.817384 9068 sync.cc:78] auth got invalid response

E20230302 18:06:50.938107 9068 sync.cc:78] auth got invalid response

E20230302 18:06:50.996701 9068 sync.cc:78] auth got invalid response

E20230302 18:06:51.010406 9068 sync.cc:78] auth got invalid response

E20230302 18:06:51.021469 9068 sync.cc:78] auth got invalid response

E20230302 18:06:51.032426 9068 sync.cc:78] auth got invalid response

E20230302 18:06:51.044173 9068 sync.cc:78] auth got invalid response

8) Change the password of target-kv to x -&$(# (x)), and observe the print of kv2redis as follows

E20230302 18:08:55.798810 9871 sync.cc:78] auth got invalid response

E20230302 18:08:55.798920 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 18:08:55.803305 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 18:08:55.808208 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 18:08:55.812773 9871 sync.cc:78] auth got invalid response

E20230302 18:08:55.816367 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 18:08:55.822363 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 18:08:55.827317 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 18:08:55.828011 9871 sync.cc:78] auth got invalid response

E20230302 18:08:55.832218 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 18:08:55.839272 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

E20230302 18:08:55.844763 9966 redis_ writer.cc:112] [kvrocks2redis] redis Auth failed: -ERR invaild password

9) Close target-kv, clear the data directory and start it. Change the password to tuiyi2023kvrockstest, clear the kv2redis directory and restart it. Observe the kv2redis print as follows:

Log file created at: 2023/03/02 18:15:55

Running on machine: bj-lsy-205

Running duration (h:mm:ss): 0:00:00

Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg

I20230302 18:15:55.922307 13044 storage.cc:335] [storage] Success to load the data from disk: 12 ms

I20230302 18:15:55.922664 13044 sync.cc:65] [kvrocks2redis] Start sync the data from kvrocks to redis


After printing the log, the kv2redis process exits

**Comment by git-hulk** [comment]
Hi @QQxiaoyuyu 

You should quote the entire config value like the below:

```
namespace.__namespace "127.0.0.1 6379 123#456"
```

instead of

```
namespace.__namespace 127.0.0.1 6379 "123#456"
```

**Comment by git-hulk** [comment]
I confirmed that it works as expected, welcome to reopen it if you have any questions.

**Comment by QQxiaoyuyu** [comment]
![图片](https://user-images.githubusercontent.com/34185590/223303852-043f2cad-b3c7-4cf6-85e9-a512a6dfd3ae.png)
开始启动的时候日志报错，然后将文件删除后启动，日志没有报错，但是服务器上面没有kv2redis进程

**Comment by tisonkun** [comment]
@QQxiaoyuyu For new issue/question, please open a ticket on:

* https://github.com/apache/incubator-kvrocks/discussions/categories/q-a
* or https://github.com/apache/incubator-kvrocks/discussions/categories/%E4%B8%AD%E6%96%87

Please don't use a single issue as a group chat.

Locking...
