### ISSUE TITLE
Scan command response cursor is not a u64

### ISSUE THREAD

**Issue by mybee** [apache/kvrocks#1305]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

I use docker to run the kvrocks image which from docker hub with latest version

### Minimal reproduce step

10.20.40.82:6666> scan 0
1) "_FFWKCSNQDUGEYXCYAENRYPAZIYDLEPNFHSKHIKJKGKIXJUUXSJGSIXKJEHHOFFSBUPJRKBJFDRBQRZUGDLZLNDEDITICAOBCPNOVJGEJYTELZXFRTSBXOCPKBXVUXCOUKDHWFMYJBDYTHTMWQHNHGCQINMSBTANFRSKTN"
2)  1) "AHPNTDUXLGRYJVFVNZGDWVSFNCFQXLGZKWGXQOIRUSNQCLTUAISPHVYFQTBULMWRFIOAKVVCGKSSHOBYEJGFURW"
    2) "AYTLNVRHLWAYHNHJLCSOMO"
    3) "AZTTNRFRUDIXFHHMOVULSMTVUOMVXTCLHVCOUWMBAESWOTHJPJCNQTFVZBL"

### What did you expect to see?

10.20.40.82:6666> scan 0
1) "0"
2)  1) "AHPNTDUXLGRYJVFVNZGDWVSFNCFQXLGZKWGXQOIRUSNQCLTUAISPHVYFQTBULMWRFIOAKVVCGKSSHOBYEJGFURW"
    2) "AYTLNVRHLWAYHNHJLCSOMO"
    3) "AZTTNRFRUDIXFHHMOVULSMTVUOMVXTCLHVCOUWMBAESWOTHJPJCNQTFVZBL"

**this is my expect as like as redis.**

### What did you see instead?

10.20.40.82:6666> scan 0
1) "_FFWKCSNQDUGEYXCYAENRYPAZIYDLEPNFHSKHIKJKGKIXJUUXSJGSIXKJEHHOFFSBUPJRKBJFDRBQRZUGDLZLNDEDITICAOBCPNOVJGEJYTELZXFRTSBXOCPKBXVUXCOUKDHWFMYJBDYTHTMWQHNHGCQINMSBTANFRSKTN"
2)  1) "AHPNTDUXLGRYJVFVNZGDWVSFNCFQXLGZKWGXQOIRUSNQCLTUAISPHVYFQTBULMWRFIOAKVVCGKSSHOBYEJGFURW"
    2) "AYTLNVRHLWAYHNHJLCSOMO"
    3) "AZTTNRFRUDIXFHHMOVULSMTVUOMVXTCLHVCOUWMBAESWOTHJPJCNQTFVZBL"

### Anything Else?

I find this problem when I use redis-rs(Rust) to call kvrocks with scan command, the redis-rs panic the err:

Error: Response was of incompatible type: "Could not convert from string." (response was string-data('"_IRCEGAGIOIRFVOQZJTKDLXGZWBWRMUUKLXNPCRWXFQSQEWULLVFVXLTSVLRZSLJWPZEPVZURGWLFRRFWZIIVDWWFEXBEQIWSARRVPVNDCRNBEKZSOLNVIOAIGYVFRVXHJQCPYAHHZOTTAVZHIGNHSGLQEUVWFWJBBBDJRAIETFPFBWEOFPLCLED"'))

the error means: **the cursor is not a number, so can not convert to u64**

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Duplicated. See #534 and #417.

**Comment by PragmaTwice** [comment]
For redis-rs, I think you can use `cmd(..).arg(..)...` directly instead of the wrapped method `scan`, to workaround it.

**Comment by mybee** [comment]
Thank you for the quick response and explanation. I get it.

**Comment by git-hulk** [comment]
Yes, the scan's cursor incompatibility problem brings a lot of confusion, but still didn't find a way to keep consistent with Redis.
