### ISSUE TITLE
Add support of the new data structure JSON (RedisJSON)

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1306]
Refer to https://github.com/apache/incubator-kvrocks/discussions/1270.

As a plan in [Kvrocks 2023 Roadmap](https://github.com/orgs/apache/projects/199), we are eager to explore the ability to implement RedisJSON-like command set for kvrocks.

Everyone is welcome to ask questions, or contribute your ideas/PRs.

**Comment by xiaobiaozhao** [comment]
I think  https://github.com/danielaparker/jsoncons is very appropriate。

**Comment by mapleFU** [comment]
I'd like to pickup this issue, and I'll finish it next month. You can just assign it to me

**Comment by PragmaTwice** [comment]
> I'd like to pickup this issue, and I'll finish it next month. You can just assign it to me

Sure. Go ahead!

**Comment by git-hulk** [comment]
@mapleFU Are you still working on this?

**Comment by mapleFU** [comment]
Sorry for late reply, I'm a little busy these days. I'll give an RFC next week when I'm out for holidays

**Comment by git-hulk** [comment]
Sure, thanks for your update. Just to confirm if you have time on this. Hope you have a good vacation.

**Comment by PragmaTwice** [comment]
See #1805.
