### ISSUE TITLE
Bump Snappy to 1.1.10

### ISSUE THREAD

**Issue by aleksraiden** [apache/kvrocks#1309]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

We can try to use a newest release of Google Snappy library (1.10.0+, [https://github.com/google/snappy/releases/tag/1.1.10](https://github.com/google/snappy/releases/tag/1.1.10)). 

But at now googler's broke a Clang support, so I'am  waiting to fix release. 

I remember, that we had a some bug with snappy early (e.g. https://github.com/apache/incubator-kvrocks/issues/788), maybe in this release they are fixed. Let's try to check. 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Thanks @aleksraiden, can use `redis-benchmark -p 6666 -t set -d 102400 -r 100000000 -n 10000000` to check if the bug still exists.

**Comment by aleksraiden** [comment]
@git-hulk Lot of thanks, I check this into my private fork asap.

**Comment by aleksraiden** [comment]
A bug with corrupted  compression block have no reproduce in all my tests - Debian 11 х64 and special test unit with CentOS 7.9.2009 х64.

**Comment by git-hulk** [comment]
Thanks for your efforts.

**Comment by aleksraiden** [comment]
This would be a largest test platform for me - 3Tb volume dedicated for kvrocks )

**Comment by aleksraiden** [comment]
@torwig create a patch for Snappy with correct fix current problem (~1 LoC!!!! just see - https://github.com/google/snappy/pull/165) but we have no idea about how long a Googlers will be  thinking about it for a fix. So, could we can try a quick fix like LuaJIT - fork Google/Snappy repository into KVRocks lab, apply our fix and use a new Snappy codec right now. And in a future, when a new release of Snappy are shipped, we switch to use them. 

What you think about this? @git-hulk @tisonkun @torwig @PragmaTwice @ShooterIT

**Comment by git-hulk** [comment]
@aleksraiden I prefer to wait for @torwig's PR to be merged because the old version works well now. To see if others folks have any thoughts on this.

**Comment by tisonkun** [comment]
1. CMake supports such simple patches during the compile stage.
2. Generally, we don't maintain too many hacks upstream, you can apply the patch and run the revision in your prod, that's how OSS stratifies customized usage.

So I'm -1 on forking a new repo, but choose either 1 or 2 above.

**Comment by aleksraiden** [comment]
Ok, let's wait, I pinged one of the committers in snappy repo.

**Comment by aleksraiden** [comment]
In a Snappy repo bug are fixed now, just waiting a new release tag.

**Comment by git-hulk** [comment]
Hi @aleksraiden, great thanks for your follow-up.

**Comment by aleksraiden** [comment]
So, I add a new version of Snappy (based on this commit https://github.com/google/snappy/commit/f725f6766bfc62418c6491b504c8e5865ec99412), with (in addition to 1.10.0):
- Optimization of decompression in ARM platform
- Add prefetch for compression
- Fix -Wsign-compare bug

Because a Snappy have a something like 1-Year release cycle, and because this (1.10) release have a lot of performance improvements, my propose is use this version without waiting a next release of them.

**Comment by aleksraiden** [comment]
Done, now closing, thanks to all!
