### ISSUE TITLE
Add basic tests for kvrocks2redis

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#1338]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

So that we're sure that the fundamental functions of kvrocks2redis work well.

### Solution

@git-hulk I'm still counting on you to understand how to use kvrocks2redis. So that we can add some gocase to cover those usages.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
It should be hard to add Go test cases for this tool but can add a fixed dataset to make sure it works well with those data types.

**Comment by tisonkun** [comment]
@git-hulk That can be the case. But before we dive into the implementation, I suggest we reach a consensus on what fundamental functions of kvrocks2redis are and how a user manually use it.

**Comment by git-hulk** [comment]
OK, let me add a how-to-use kvrocks2redis doc first.

**Comment by tisonkun** [comment]
> OK, let me add a how-to-use kvrocks2redis doc first.

@git-hulk do you have a plan or estimate on this ticket?

**Comment by git-hulk** [comment]
@tisonkun Yes, I wonder if I should refactor this tool since it's NOT easy to maintain now. But I haven't started it yet. Plan to do that at the beginning of May, after I released the first version of the controller: https://github.com/KvrocksLabs/kvrocks_controller/issues/49

**Comment by tisonkun** [comment]
@git-hulk can you provide some basic how-to-use info here so that I can follow up?

**Comment by git-hulk** [comment]
> @git-hulk can you provide some basic how-to-use info here so that I can follow up?

Sure, thanks. Sorry for forgetting this, I'll add the how-to-use doc this week first.

**Comment by tisonkun** [comment]
Related to https://github.com/apache/kvrocks-website/pull/138.

**Comment by git-hulk** [comment]
I also created another issue #1643 to track improvements of `kvrocks2redis`.
