### ISSUE TITLE
SSCAN returns a cursor that cannot be cast to a number

### ISSUE THREAD

**Issue by JohnEskimSmith** [apache/kvrocks#1346]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

docker image:
apache/kvrocks:nightly
apache/kvrocks:2.3.0

checked with:
1. redis-cli
2. python3.11, package redis==4.5.3
3. go

### Minimal reproduce step

```127.0.0.1:9090> sadd set1 a b c d e f g h i j k l m n o p q r s t u v w x y z
(integer) 26
127.0.0.1:9090> smembers set1
 1) "a"
 2) "b"
 3) "c"
 4) "d"
 5) "e"
 6) "f"
 7) "g"
 8) "h"
 9) "i"
10) "j"
11) "k"
12) "l"
13) "m"
14) "n"
15) "o"
16) "p"
17) "q"
18) "r"
19) "s"
20) "t"
21) "u"
22) "v"
23) "w"
24) "x"
25) "y"
26) "z"
127.0.0.1:9090> sscan set1 0
1) "t"
2)  1) "a"
    2) "b"
    3) "c"
    4) "d"
    5) "e"
    6) "f"
    7) "g"
    8) "h"
    9) "i"
   10) "j"
   11) "k"
   12) "l"
   13) "m"
   14) "n"
   15) "o"
   16) "p"
   17) "q"
   18) "r"
   19) "s"
   20) "t"
127.0.0.1:9090>
```
![1](https://user-images.githubusercontent.com/3313476/227031572-e47df71b-9bc7-4b03-a1df-c5af3b48ce95.jpg)
![2](https://user-images.githubusercontent.com/3313476/227031578-bb952ffb-63d9-4956-a3ba-2599b7ad36f8.jpg)

### What did you expect to see?

For Redis:
```
127.0.0.1:6379> sscan set1 0
1) "1"
2)  1) "e"
    2) "o"
    3) "q"
    4) "h"
    5) "t"
    6) "a"
    7) "m"
    8) "d"
    9) "u"
   10) "b"
   11) "v"
127.0.0.1:6379> sscan set1 1
1) "7"
2)  1) "x"
    2) "w"
    3) "i"
    4) "c"
    5) "s"
    6) "g"
    7) "r"
    8) "l"
    9) "p"
   10) "n"
   11) "k"
127.0.0.1:6379> sscan set1 7
1) "0"
2) 1) "f"
   2) "j"
   3) "z"
   4) "y"
127.0.0.1:6379>
```
As we can see: cursor always is number. Moreover, the Python and Go libraries expect the cursor value to be represented as an integer. And of course code break when the cursor is not converted to a number.
![redis-good](https://user-images.githubusercontent.com/3313476/227032746-b1e33ade-ff24-4c20-8fe4-aa45efb42936.png)

### What did you see instead?

SSCAN returned cursor cannot be represented as a number

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @JohnEskimSmith

It's an expected behavior, Kvrocks didn't have the hash bucket distribution, so it cannot return the cursor as a number now. To workaround, can use the fork version of redis-py: https://github.com/hashlookup/redis-py which is from @adulau.

**Comment by PragmaTwice** [comment]
Duplicated. See #1305, https://github.com/apache/incubator-kvrocks/issues/534 and https://github.com/apache/incubator-kvrocks/discussions/417.

To modify the client implementation, see [e9c53fb1398e636106c0ec0165ba564943564a83](https://github.com/hashlookup/redis-py/commit/e9c53fb1398e636106c0ec0165ba564943564a83).

**Comment by JohnEskimSmith** [comment]
Hi @git-hulk
Thanks for the reply. Prior to posting the question, for myself, I quickly found how to get around this issue with change client.
The problem is of course with the compatibility of libraries and languages. And with a service with backend Kvrocks, that clients can access both with python or go(other...), you(me) have to keep this in mind, that very sad.

**Comment by git-hulk** [comment]
@JohnEskimSmith Yes, we have also realized and tried to work around this confusion.
