### ISSUE TITLE
Support fork-based start

### ISSUE THREAD

**Issue by aleksraiden** [apache/kvrocks#1365]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Need for elegant updating  etc. Like nginx, redis and so on.

### Solution

My propose is an adding new command-line startup options named "-d". If used, a process immediately fork himself and exit. So, after that we can update an executable file while server are running and then use a manual start/stop or use serviced reload options. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Seems we already have a `daemonize` option. Does this fit your needs?

**Comment by aleksraiden** [comment]
As I see, no. So my point is - how we can start kvrocks and updating executable file before restart service. But maybe all my thinking is a wrong way...

**Comment by aleksraiden** [comment]
https://unix.stackexchange.com/questions/353457/will-overwriting-to-an-executable-file-affect-a-process-which-is-running-the-ori
