### ISSUE TITLE
About the performance optimization of home page image loading

### ISSUE THREAD

**Issue by sendRainAutumn** [apache/kvrocks#1371]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

When I open the official website for the first time, the pictures on the home page load very slowly, taking up to 35s. As shown below:
![2491680686736_ pic](https://user-images.githubusercontent.com/46080479/230061516-86ede2f0-02a8-4397-8e54-a05cb6d6f1c5.jpg)

### Solution

It may be possible to cache static resources with the help of CDN.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by sendRainAutumn** [comment]
#1257

**Comment by git-hulk** [comment]
Hi @SongYuQiu

Thanks for your feedback. We can use `https://cdn.jsdelivr.net/` which will auto-mapping the GitHub repo file path to the CDN path.

For example, the mainPic's path is static/img/, then we can use `https://cdn.jsdelivr.net/gh/apache/incubator-kvrocks-website/static/img/mainPic.png` directly.

**Comment by ColinChamber** [comment]
![telegram-cloud-document-1-5019810286387856141](https://user-images.githubusercontent.com/95634254/231196052-4060e644-3b34-4c0c-83ac-cbdaccf415d2.jpg)
After the modifications, there was some improvement in speed. 
BTW, The DNS for cdn.jsdelivr.net and fastly.jsdelivr.net have been polluted by the GFW. For now, gcore.jsdelivr.net is still accessible, but its future availability is uncertain. FYI @SongYuQiu
