### ISSUE TITLE
SetClusterNodes  allow to match localhost and real ip when listening on 0.0.0.0

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1381]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Currently, `SetClusterNodes` can't match the node if the instance is listening on 0.0.0.0 instead of the real IP. 

For example, the cluster topology is: `lohMbHeln658feDcRVKYb4tT7XClAm3Zr4awKuoK 127.0.0.1 6666 master -  0-16383`, but the listen address is 0.0.0.0, then it won't match the cluster node since the listen IP is not strictly equal to cluster's node IP 127.0.0.1(as well as not localhost IP like 172.14.1.x).

This would confuse users because the cluster didn't work as their expected.

### Solution

Check the IP address is matched by the real listening IP addresses instead of the bind address directly when using 0.0.0.0.

https://github.com/apache/incubator-kvrocks/blob/unstable/src/cluster/cluster.cc#L211

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zevin02** [comment]
please assign to me

**Comment by PragmaTwice** [comment]
> please assign to me

Great! Assigned.
