### ISSUE TITLE
Supplement  Kvrocks-controller documents

### ISSUE THREAD

**Issue by ColinChamber** [apache/kvrocks#1382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Supplement  Kvrocks-controller documents

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@git-hulk where is the associated PR or this is closed as won't do?

**Comment by git-hulk** [comment]
> @git-hulk where is the associated PR or this is closed as won't do?

@tisonkun Sorry for didn’t mention the reason. The API doc was finished: https://github.com/RocksLabs/kvrocks_controller/blob/unstable/docs/API.md. And I think it would be more coherent to maintain the controller related issues in its repository if have any further issues.
