### ISSUE TITLE
Implement a TIME command from Redis

### ISSUE THREAD

**Issue by aleksraiden** [apache/kvrocks#1393]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

For more compatibility with original Redis spec and because a some other command like XADD etc. use internal time as identificatory of items. 

Redis spec are here - [https://redis.io/commands/time/](https://redis.io/commands/time/)  

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by enjoy-binbin** [comment]
redis used gettimeofday in the past, should we also use gettimeofday directly? (in Redis 7.2, TIME use a cached time)

**Comment by git-hulk** [comment]
Hi @enjoy-binbin 

I think it's fine to use the time function in [time_util.h](https://github.com/apache/incubator-kvrocks/blob/unstable/src/common/time_util.h).
