### ISSUE TITLE
config rewrite bug

### ISSUE THREAD

**Issue by iushas** [apache/kvrocks#1396]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.3.0

### Minimal reproduce step

namespace add xxx
config rewrite

### What did you expect to see?

no extra blank lines in kvrocks.conf

### What did you see instead?

First create 1w namespace, then config rewrite.
There are 1w extra blank lines after config rewrite

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by iushas** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/7236171/233042866-db93476a-5db4-4645-b4e6-331ffbb29b79.png">

**Comment by enjoy-binbin** [comment]
It seems that in addition to this problem, every time we perform a `config rewrite`, an additional newline is appended

**Comment by enjoy-binbin** [comment]
so it look like `file.eof()` problem. see https://stackoverflow.com/questions/21647/reading-from-text-file-until-eof-repeats-last-line

change it to this seems work
```diff
diff --git a/src/config/config.cc b/src/config/config.cc
index 3e3c286..77825ae 100644
--- a/src/config/config.cc
+++ b/src/config/config.cc
@@ -829,8 +829,8 @@ Status Config::Rewrite() {
   std::ifstream file(path_);
   if (file.is_open()) {
     std::string raw_line;
-    while (!file.eof()) {
-      std::getline(file, raw_line);
+    while (std::getline(file, raw_line)) {
+      if (file.eof()) break;
       auto parsed = ParseConfigLine(raw_line);
       if (!parsed || parsed->first.empty()) {
         lines.emplace_back(raw_line);
```

**Comment by git-hulk** [comment]
> It seems that in addition to this problem, every time we perform a `config rewrite`, an additional newline is appended

yes

**Comment by enjoy-binbin** [comment]
I tested the changes above locally, it will work (and it also can fix this issue)
should we need to change all `while (!file.eof())`, I see we still have a few places where we use this

**Comment by git-hulk** [comment]
Yes, I think so. cc @PragmaTwice
