### ISSUE TITLE
Syntax of HELLO is different from Redis

### ISSUE THREAD

**Issue by rueian** [apache/kvrocks#1403]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.3.0

### Minimal reproduce step

1. Set `requirepass mypass`
2. Send command: `HELLO 2 AUTH default mypass` after connected.

### What did you expect to see?

mypass should be accepted.

### What did you see instead?

`invalid password` error.

### Anything Else?

Hi, 

According to https://redis.io/commands/hello, the syntax of `HELLO` should be 
```
HELLO [protover [AUTH username password] [SETNAME clientname]]
```
and the default username should be `default`.

However, kvrocks' syntax seems to lack the username part:
https://github.com/apache/incubator-kvrocks/blob/6889b5916ab560ecd5eed79bb9786e36342f0e17/src/commands/cmd_server.cc#L660

Not sure if this is intended? But I think it will be great if matching redis' syntax.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
@mapleFU  could you take a look at this?

**Comment by mapleFU** [comment]
Hi @rueian . When I implement "hello", kvrocks didn't support auth like that.
https://github.com/apache/incubator-kvrocks/pull/881#issuecomment-1249985088

**Comment by PragmaTwice** [comment]
Hi @rueian, it seems meaningless in kvrocks to give a username, since the AUTH command in kvrocks is used to authorize accessibility to a corresponding [namespace](https://kvrocks.apache.org/docs/namespace/).

**Comment by rueian** [comment]
> Hi @rueian, it seems meaningless in kvrocks to give a username, since the AUTH command in kvrocks is used to authorize accessibility to a corresponding [namespace](https://kvrocks.apache.org/docs/namespace/).

Hi @PragmaTwice, I understand.

However, from a redis client implementation perspective, this difference in syntax means that a client implementation may need to treat Kvrocks differently to work with it. I think this may put some barriers for a client to adapt to Kvrocks.

**Comment by PragmaTwice** [comment]
@rueian Thanks for you explaination. It make sense. I am not averse to accept an `AUTH default <pass>` form. cc @git-hulk

**Comment by git-hulk** [comment]
I also prefer to allow passing the username, even though it's meaningless to Kvrocks.

**Comment by tisonkun** [comment]
@rueian IIRC the goredis client handle the `AUTH` command specially for kvrocks. If you're implementing a redis client and hope it can be compatible with kvrocks, feel free to start a discussion to add (compatible) integration tests. As our gocases are written on the top of goredis.

**Comment by tisonkun** [comment]
Aha. We change for being compatible with go-redis in https://github.com/apache/incubator-kvrocks/pull/830.

**Comment by rueian** [comment]
Hi @tisonkun,

Yes, I am also making a go redis client, rueidis, and got a report that it doesn't work with kvrocks because of the syntax difference with redis: https://github.com/rueian/rueidis/issues/204

But I am not sure if goredis do special work for kvrocks or not, since its latest version doesn't work with kvrocks as well.

For example:
```go
package main

import (
	"context"
	"fmt"
	"github.com/redis/go-redis/v9"
)

func main() {
	client := redis.NewClient(&redis.Options{Addr: "127.0.0.1:6666", Password: "mypass"})
	fmt.Println(client.Ping(context.Background()))
}
```
goredis actually send `hello 3 auth default mypass` to kvrocs. And then it returned `ping: Syntax error in HELLO option auth` error.

**Comment by tisonkun** [comment]
@rueian Thanks for your repro! That's a good new test case we can add to the integration test suite for verifying this issue is resolved :D
