### ISSUE TITLE
Support specify release candidate number in `x.py package source`

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#1407]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Otherwise, the RC always has the same tag name as the formal release name. And it's awkward to force-push for overwriting refs.

### Solution

cc @PragmaTwice @git-hulk may you check where we should use `-rcX` during the release process?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Sure, we can make it push to a tag with rc suffix.

**Comment by tisonkun** [comment]
@PragmaTwice what I'm afraid of is that there is still other place we need `rc` suffix except the git tag :D

**Comment by ZENOTME** [comment]
I can help with this.

Not sure whether my understand is correct, it's to support 
`./x.py package source -v 2.3.2 -rc 1` and then create a tag '2.3.2-rc1'.

**Comment by tisonkun** [comment]
@ZENOTME Thanks for your input! That sounds good to me. Please go ahead.
