### ISSUE TITLE
common/ParseUtil replace erro msgs with error integers 

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

for exmaple, one instantiation of ParseInt presents below.

https://github.com/apache/incubator-kvrocks/blob/30e9fd788a4acb585566a008f4d5fff65ee06ce3/src/common/parse_util.h#L113-L125

We can't get a more detailed information about what `v` meanings in Parse() func and just think it as an non-integer error if the parsing occurs the error.

I view the source code about calling `ParseInt`(or `ParseType`) functions and find that we use the parse  function without taking advantage of the info from error msgs.

```cpp
// in the process of pasrsing commands.
      auto parse_result = ParseInt<int64_t>(int1, 10);
      if (!parse_result) {
        return {Status::NotOK, InvalidMsgs};
      }
```

We can provide an exact error-msg actually, such as `out of range about the NodeId`, `illegal character of the 'ClusterNode' str`.

This is a issue for helpful msgs, so it is not necessary. Please add `help wanted` and `good for first` labels.

### Solution

It needs a lot of work here.

we just define different error-types in parse_util module and the concrete caller use the type to modify error-msgs.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
I think it seems not necessary to create status codes for every parsing error type. In kvrocks, a better and simple solution already exists:
```c++
auto version = ParseInt<VersionInteger>(version_str);
if (!version) {
  return std::move(version).Prefixed("failed to parse version");
}

// do something with *version ...
```

Then users will get a well-formed error message, like `failed to parse version: out of range` or `failed to parse version: encounter non-digit characters`.

And we even have a more compact form to handle this pattern:
```c++
int version = GET_OR_RET(ParseInt<int>(version_str).Prefixed("failed to parse version"));
// use this integer, no need of if statements
```

**Comment by infdahai** [comment]
yes, `v.Prefixed("failed to parse version");` is enough.
