### ISSUE TITLE
Add support of RocksDB auto-tune rate limiter for the background IO

### ISSUE THREAD

**Issue by wanghenshui** [apache/kvrocks#1417]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

https://rocksdb.org/blog/2017/12/18/17-auto-tuned-rate-limiter.html

### Solution
https://github.com/apache/incubator-kvrocks/blob/30e9fd788a4acb585566a008f4d5fff65ee06ce3/src/storage/storage.cc#L163

change to this
```c++
rocksdb::NewGenericRateLimiter(
        rate_limiter_bandwidth(),
        rate_limiter_refill_period_us(),
        rate_limiter_fairness(),
        rocksdb::RateLimiter::Mode::kWritesOnly,
        rate_limiter_auto_tuned()
      );
```

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @wanghenshui 

Thanks for your proposal, would you like to take this?

**Comment by mapleFU** [comment]
Seems that it can benefits I/O scheduling rather than using `kIORateLimitMaxMb` as fixed io limits? Should we default using that or just as a config?

**Comment by wanghenshui** [comment]
> Hi @wanghenshui
> 
> Thanks for your proposal, would you like to take this?

ok

**Comment by git-hulk** [comment]
> Seems that it can benefits I/O scheduling rather than using `kIORateLimitMaxMb` as fixed io limits? Should we default using that or just as a config?

I think it'd be better to make this as default. How do you think?

**Comment by mapleFU** [comment]
I guess we can, but we'd better testing it first. @xiaobiaozhao would you like to take a look or do some testing if auto tune rate limiter is supportted?

**Comment by xiaobiaozhao** [comment]
1. This parameter looks very good, can promote the whole DB performance college
2. I can test the parameters of performance improvement this weekend
