### ISSUE TITLE
Improve build Docker image on Alpine Linux with musl libc

### ISSUE THREAD

**Issue by aleksraiden** [apache/kvrocks#1421]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

If I need a build kvrocks Docker image, based on Alpine linux, I had an error:

> #0 3841.6 [ 98%] Building CXX object CMakeFiles/kvrocks.dir/src/main.cc.o
> #0 3851.1 [100%] Linking CXX executable kvrocks
> #0 3994.4 /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: CMakeFiles/kvrocks.dir/src/main.cc.o: in function `SegvHandler':
> #0 3995.4 /kvrocks/src/main.cc:87: undefined reference to `backtrace'
> #0 3995.4 /usr/lib/gcc/x86_64-alpine-linux-musl/11.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /kvrocks/src/main.cc:88: undefined reference to `backtrace_symbols'
> #0 4004.7 collect2: error: ld returned 1 exit status
> #0 4004.7 make[3]: *** [CMakeFiles/kvrocks.dir/build.make:249: kvrocks] Error 1
> #0 4004.7 make[2]: *** [CMakeFiles/Makefile2:521: CMakeFiles/kvrocks.dir/all] Error 2
> #0 4004.8 make[1]: *** [CMakeFiles/Makefile2:528: CMakeFiles/kvrocks.dir/rule] Error 2
> #0 4004.8 make: *** [Makefile:254: kvrocks] Error 2

It seems like musl does not provide the backtrace function.

### Solution

Some about this I fined there - https://github.com/xournalpp/xournalpp/issues/3817 and now I test some fix. 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
https://github.com/godotengine/godot/issues/57193
https://github.com/godotengine/godot-proposals/issues/2439

Seems you can try to install libexecinfo, or try to link it to kvrocks.

**Comment by aleksraiden** [comment]
> [godotengine/godot#57193](https://github.com/godotengine/godot/issues/57193) [godotengine/godot-proposals#2439](https://github.com/godotengine/godot-proposals/issues/2439)
> 
> Seems you can try to install libexecinfo, or try to link it to kvrocks.

Thanks, but it's only a part of them. I have successful build but  final container not work correctly. Investigating now
