### ISSUE TITLE
Failed to build kvrocks due to instruction tpause in TBB

### ISSUE THREAD

**Issue by mnizhq007** [apache/kvrocks#1425]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

kvrocks：2.4.0
-- CMAKE_BINARY_DIR:         /root/incubator-kvrocks-2.4.0/build
-- CMAKE_CURRENT_BINARY_DIR: /root/incubator-kvrocks-2.4.0/build/_deps/libevent-build
-- CMAKE_SOURCE_DIR:         /root/incubator-kvrocks-2.4.0
-- CMAKE_CURRENT_SOURCE_DIR: /root/incubator-kvrocks-2.4.0/build/_deps/libevent-src
-- PROJECT_BINARY_DIR:       /root/incubator-kvrocks-2.4.0/build/_deps/libevent-build
-- PROJECT_SOURCE_DIR:       /root/incubator-kvrocks-2.4.0/build/_deps/libevent-src
-- CMAKE_MODULE_PATH:        /root/incubator-kvrocks-2.4.0/build/_deps/libevent-src/cmake/
-- CMAKE_COMMAND:            /usr/local/bin/cmake
-- CMAKE_ROOT:               /usr/local/share/cmake-3.25
-- CMAKE_SYSTEM:             Linux-3.10.0-957.el7.x86_64
-- CMAKE_SYSTEM_NAME:        Linux
-- CMAKE_SYSTEM_VERSION:     3.10.0-957.el7.x86_64
-- CMAKE_SYSTEM_PROCESSOR:   x86_64
-- CMAKE_SKIP_RPATH:         NO
-- CMAKE_VERBOSE_MAKEFILE:   FALSE
-- CMAKE_C_FLAGS:             -Wall -Wextra -Wno-unused-parameter -Wstrict-aliasing -Wstrict-prototypes -fno-strict-aliasing -Wmissing-prototypes -Winit-self -Wmissing-field-initializers -Wdeclaration-after-statement -Waddress -Wnormalized=id -Woverride-init -Wlogical-op -Wwrite-strings
-- CMAKE_BUILD_TYPE:         RelWithDebInfo
-- CMAKE_C_COMPILER:         /usr/bin/cc (id GNU, clang 0, GNUC 1)
-- CMAKE_AR:                 /usr/bin/ar
-- CMAKE_RANLIB:             /usr/bin/ranlib

### Minimal reproduce step

./x.py build

### What did you expect to see?

I hope to successfully complete the compilation of the latest version.

### What did you see instead?

[  1%] Built target make_jemalloc
[  1%] Built target make_lz4
[  1%] Built target make_zstd
[  1%] Built target make_luajit
[  2%] Built target glogbase
[  2%] Built target glog
[  3%] Built target snappy
[  6%] Built target zlibstatic
[  6%] Building CXX object _deps/tbb-build/src/tbb/CMakeFiles/tbb.dir/address_waiter.cpp.o
[  8%] Building CXX object _deps/tbb-build/src/tbb/CMakeFiles/tbb.dir/allocator.cpp.o
[  8%] Building CXX object _deps/tbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.o
/tmp/ccWap3gD.s: Assembler messages:
/tmp/ccWap3gD.s:23862: Error: no such instruction: `tpause %ecx'
/tmp/ccWap3gD.s:25254: Error: no such instruction: `tpause %ecx'
gmake[3]: *** [_deps/tbb-build/src/tbb/CMakeFiles/tbb.dir/arena.cpp.o] Error 1
gmake[2]: *** [_deps/tbb-build/src/tbb/CMakeFiles/tbb.dir/all] Error 2
gmake[1]: *** [CMakeFiles/kvrocks.dir/rule] Error 2
gmake: *** [kvrocks] Error 2
Traceback (most recent call last):
  File "./x.py", line 393, in <module>
    args.func(**arg_dict)
  File "./x.py", line 134, in build
    run(cmake, *options, verbose=True, cwd=dir)
  File "./x.py", line 66, in run
    raise RuntimeError(err)
RuntimeError: 
failed to run: ('/usr/local/bin/cmake', '--build', '.', '-t', 'kvrocks', 'kvrocks2redis')
exit with code: 2

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Please provide more info about your build environment: OS version, arch, compiler toolchain, ...

**Comment by PragmaTwice** [comment]
Refer to https://github.com/oneapi-src/oneTBB/issues/859.

As they do not plan to fix this issue, you have several choices (one of them is ok):
- update your binutils version to  2.31.1 or later (it is not a pretty new version, so I think it is not too hard)
- use GCC <= 10 (but you need GCC >= 7 as a requirement of kvrocks, so the version of GCC need to be in [7, 10])
