### ISSUE TITLE
Hash::MGet: use DB::MultiGet for hash fields

### ISSUE THREAD

**Issue by rockeet** [apache/kvrocks#1441]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

`DB::MultiGet` pushes fields query to RocksDB, thus RocksDB can perform optimizations, such as async io by io uring.

Although this optimization is less than `mget` for strings, it is valuable because different fields may lies in different levels of the LSM Tree, thus async io can take effect.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zevin02** [comment]
I hope to deal with it

**Comment by git-hulk** [comment]
Thanks @zevin02, assigned
