### ISSUE TITLE
Add the support of the `BZMPOP` command

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1445]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

 This issue considers to support [`bzmpop`](https://redis.io/commands/bzmpop/), `bzpopmax`, `bzpopmin` commands.

And the implementation should process a `timeout` argument. 

### Solution

- [ ] bzmpop
- [ ] bzpopmax
- [ ] bzpopmin

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@infdahai Would you like to do this?

**Comment by infdahai** [comment]
I can accept this task for now but it needs time.

>And more specifically, I want to use bzpop<max|min|null>, <z|s>intercard, zmpop go APIs to write some go-unit tests for supporting the more commands from zset or set in kvrocks. These commands from redis(version >= 6.2) are not implemented in this project.

Because I want to implement all commands from [`zset`](https://redis.io/commands/bzmpop/). If anyone wants to get involved in this task, you can just reply under this issue.

**Comment by Yangsx-1** [comment]
I want to participate in the task, can i contact you through wechat or other ways?

**Comment by infdahai** [comment]
@git-hulk please invite him to wechat groups. Mabye you can search the TimerCB funcs in the codebase to learn how to add the event to the loop. And we can talk the impl here to help others also know the progress.

**Comment by git-hulk** [comment]
Please follow the WeChat Official Account at the bottom of README.md, then join the WeChat group via the guidance.

But we encourage everyone to discuss the proposal or solution via GitHub Discussion instead of a private channel.

**Comment by Yangsx-1** [comment]
Ok, I'm already in the group and i'll look into the code. I’m new in here, may i'll have many questions, lol.

**Comment by Yangsx-1** [comment]
I think it's bzpopmax rather than bzmpopmax.

**Comment by infdahai** [comment]
> I think it's bzpopmax rather than bzmpopmax.

Thanks, fixed

**Comment by PragmaTwice** [comment]
Note: As an ASF community, we do not endorse any discussion on some private channels like wechat group. 

We prefer public available discussion like GitHub issues, discussions and ASF mailing lists. Feel free to post your questions on these platform.

**Comment by Yangsx-1** [comment]
> Note: As an ASF community, we do not endorse any discussion on some private channels like wechat group.
> 
> We prefer public available discussion like GitHub issues, discussions and ASF mailing lists. Feel free to post your questions on these platform.

Ok, i'm just a little shy. I'll post my question if i cannot overcome it.

**Comment by Yangsx-1** [comment]
I‘ve already finish the code, and have tested it manually.
I'm now trying to add some go tests but i'm not very familiar with go and go test.
I want to know how to run single test for zset, i tried several ways but it didn't work.   :(

**Comment by git-hulk** [comment]
> I‘ve already finish the code, and have tested it manually. I'm now trying to add some go tests but i'm not very familiar with go and go test. I want to know how to run single test for zset, i tried several ways but it didn't work. :(

Hi @Yangsx-1, You can reach me on Slack if you need help.

**Comment by PragmaTwice** [comment]
> I‘ve already finish the code, and have tested it manually.
> I'm now trying to add some go tests but i'm not very familiar with go and go test.
> I want to know how to run single test for zset, i tried several ways but it didn't work.   :(

Try something like `./x.py test go <build-dir> -run <match-str>`.

And you can refer to `go test --help` for more information about the `-run` option.

**Comment by Yangsx-1** [comment]
Ok, I'll try it first. I'll contact you if i have some problems later @git-hulk
