### ISSUE TITLE
Data race in TBB::concurrent_queue when running integrate tests

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1448]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

detail logs: https://github.com/apache/incubator-kvrocks/actions/runs/5015903443/jobs/8992316856?pr=1446

### What did you expect to see?

all tests are passed

### What did you see instead?

one of them crashed when running

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
I think maybe it is a false positive. 

We can try to add it into https://github.com/apache/incubator-kvrocks/blob/unstable/tests/tsan-suppressions.

**Comment by git-hulk** [comment]
> I think maybe it is a false positive.
> 
> We can try to add it into https://github.com/apache/incubator-kvrocks/blob/unstable/tests/tsan-suppressions.

OK
