### ISSUE TITLE
How do I run a specified go unit test through x.py?

### ISSUE THREAD

**Issue by xiaobiaozhao** [apache/kvrocks#1450]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

How do I run a specified go unit test through x.py?

### Solution

I think a note could be added to the readme

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xiaobiaozhao** [comment]
@tisonkun Would you improve the documentation?

**Comment by infdahai** [comment]
for example, I exec the followling commands.
```shell
cd ${workspaceFolder}
./x.py build --unittest -DCMAKE_BUILD_TYPE=Debug  -j24

./build/unittest --gtest_filter=RedisSetTest.InterCard

./build/unittest --gtest_filter=RedisSetTest.*
```

After this, I get the output from `RedisSetTest.InterCard` and all outputs from `RedisSetTest`.

**Comment by infdahai** [comment]
I exec the command `./x.py test cpp rest --gtest_filter=RedisSetTest.*` and then I get an error msg like `FileNotFoundError: [Errno 2] No such file or directory: '~/incubator-kvrocks/rest'`.

https://github.com/apache/incubator-kvrocks/blob/fb0e3d42031a6e0691c7a736711d0a01d72bdb1a/x.py#L376-L379

https://github.com/apache/incubator-kvrocks/blob/fb0e3d42031a6e0691c7a736711d0a01d72bdb1a/x.py#L246-L250

The reason why the error occurs is that `basedir` is generated to the dir `~/incubator-kvrocks/rest`.

**Comment by PragmaTwice** [comment]
`./x.py test go <build-dir> <go-test-command-args...>`.

Same as `./x.py test cpp <build-dir> <gtest-command-args...>`.

**Comment by tisonkun** [comment]
I take a look at https://kvrocks.apache.org/community/contributing/#submit-patches-to-kvrocks. Maybe we can add a paragraph under the one talking about running tests.

But actually it's as intuitive as `./x.py test go --help` and the command is self-explain.

**Comment by tisonkun** [comment]
Also, we actually print back all real command, so you can already debugging:

```
./x.py test go build -run TestInvalid
$ /opt/homebrew/bin/go test -timeout=1800s -bench=. ./... -binPath=/Users/chenzili/Brittani/kvrocks/build/kvrocks -cliPath=redis-cli -workspace=/Users/chenzili/Brittani/kvrocks/tests/gocase/workspace -run TestInvalid
```

Notice the second line is the actual execute command.
