### ISSUE TITLE
Tracking issues: Add supports of all commands from `ZSET`

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1454]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Follow up on #595. More specifically, this issue throws a few tasks to support commands from `ZSET` and you can refer to [zset command](https://redis.io/commands/bzmpop/).

### Solution

We need to complete the following command currently.

- [x] #1490
- [ ] #1494 
- [ ] #1517
- [x] #1468
- [ ] #1506
- [x] #1482
- [x] #1502

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
cool, thanks for driving this.

**Comment by jihuayu** [comment]
We support all ZSet commands now, close this.
