### ISSUE TITLE
If a middle field is missing in kvrocks hmget, it returns nil for all subsequent fields, regardless of their existence.

### ISSUE THREAD

**Issue by zevin02** [apache/kvrocks#1455]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

# Description
When using the hmget function in kvrocks, if a middle field does not exist, all subsequent fields returned by the function are nil

# Version
unstable

# Minimal reproduce step
in kvrocks
![Screenshot from 2023-05-21 21-01-41](https://github.com/apache/incubator-kvrocks/assets/92536645/445736c9-37f4-4fd2-b60a-975edd863798)

# What did you expect to see?
In Redis, it is possible to find subsequent fields even if the middle field is missing, unlike in kvrocks where hmget returns nil for all subsequent fields when a middle field is absent.
![Screenshot from 2023-05-21 21-02-19](https://github.com/apache/incubator-kvrocks/assets/92536645/9238ed93-d50e-4222-b837-18d625df71a2)

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by infdahai** [comment]
I can't reproduce this result. I use the unstable branch. 

![image](https://github.com/apache/incubator-kvrocks/assets/30547248/53787574-68b7-427f-911c-99b1cc066b2a)

**Comment by git-hulk** [comment]
I think it may be introduced by your PR: https://github.com/apache/incubator-kvrocks/pull/1453
