### ISSUE TITLE
Add the support of the ZDIFF, ZDIFFSTORE commands

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1456]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support [zdiff](https://redis.io/commands/zdiff/), zdiffstore commands.

### Solution

- [ ] zdiff
- [ ] zdiffstore

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by zevin02** [comment]
Is this issue still ongoing, I think I can do it

**Comment by git-hulk** [comment]
@zevin02 cool, go ahead

**Comment by jihuayu** [comment]
Has been done in https://github.com/apache/kvrocks/pull/2021, close.
