### ISSUE TITLE
Add the support of the ZINTER, ZINTERCARD commands

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1457]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support [zinter](https://redis.io/commands/zinter/), zintercard commands.

### Solution

- [ ] zinter
- [ ] zintercard

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by IoCing** [comment]
i want to do this

**Comment by git-hulk** [comment]
@IoCing Assigned, thanks

**Comment by jihuayu** [comment]
Has been done in https://github.com/apache/kvrocks/issues/1983, close.
