### ISSUE TITLE
Add the support of the ZMPOP command

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1458]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [zmpop](https://redis.io/commands/zmpop/) command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by MizukiCry** [comment]
I want to try this:)

**Comment by git-hulk** [comment]
Hi @MizukiCry

Assigned, thanks!

**Comment by infdahai** [comment]
> I want to try this:)

You can refer to the simliar functions in `set` and `zpop<max|min>` in `zset`. And if you encounter some difficuities with this, you can build a draft pull request and we discuss there. 🦃
