### ISSUE TITLE
Add the support of the ZRANDMEMBER command

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1459]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [zrandmember](https://redis.io/commands/zrandmember/) command.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by jihuayu** [comment]
Duplicate issues https://github.com/apache/kvrocks/issues/1985
