### ISSUE TITLE
Add the support of the ZUNION command

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1461]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [zunion](https://redis.io/commands/zunion/) command.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by uds5501** [comment]
@git-hulk I want to try this

**Comment by infdahai** [comment]
hi, @uds5501 could you impl the function and refactor the `UnionStore` function passingly? Just move `overwrite` to the outer space like `Set::UnionStore` and `Set::InterStore`.

**Comment by uds5501** [comment]
@infdahai sure, will take a look.

**Comment by git-hulk** [comment]
@uds5501 assigned, thanks.
