### ISSUE TITLE
avoid the implicit conversion from `const char *` to `string` in `Status.h`

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1462]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

https://github.com/apache/incubator-kvrocks/blob/fb0e3d42031a6e0691c7a736711d0a01d72bdb1a/src/common/status.h#L75

https://github.com/apache/incubator-kvrocks/blob/fb0e3d42031a6e0691c7a736711d0a01d72bdb1a/src/common/status.h#L101-L126

Maybe we call the implicit copy currently and the implicit conversion from `const char *` to `string` in `Status.h` can confuse the compiler and the editor because we usually invoke `{NotOK, str(type: const char*)}` as the return String.

### Solution

We can use the `Slice` type to replace the string type of  `msg` and do `Slice(const char*)` funcs by referring to `leveldb`.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
`Slice` is just a **view**, which has no **ownership**.
For example, if we want to concat some string dynamicly, we cannot use `Slice` since it cannot extend lifetime of the object, e.g.
```
string x = to_string(count) + " apples";
return Slice(x); // dangling reference!
```

BTW `Slice` is not a well-designed type, instead we have `std::string_view` since c++17.

**Comment by PragmaTwice** [comment]
You can close it if no further questions :)

**Comment by infdahai** [comment]
>string x = to_string(count) + " apples";
return Slice(x); // dangling reference!

Something I'm wondering about is that I don't know what happens in kvrocks.

**Comment by infdahai** [comment]
OK，I get it. Should we solve the implicit conversion?

**Comment by PragmaTwice** [comment]
I think nope. It is by design.

Refer to [the 5th constructor of std::basic_string](https://en.cppreference.com/w/cpp/string/basic_string/basic_string).

BTW `{NotOK, "something"}` is more intuitive than `{NotOK, string("something")}` for me.

**Comment by infdahai** [comment]
Ok, thanks for your answer.
