### ISSUE TITLE
Refine functions and add parsing tests to `Set` 

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Many commands in the current [`cmd_set`](https://github.com/apache/incubator-kvrocks/blob/b9cfbead58f68aa914bb35360f82c3f8e0ec8c90/src/commands/cmd_set.cc) file miss parsing error tests(It is the same as `zset`.) and misses some necessary checks.

For example, `syntax: SPOP key [count]` from https://redis.io/commands/spop/.
https://github.com/apache/incubator-kvrocks/blob/b9cfbead58f68aa914bb35360f82c3f8e0ec8c90/src/commands/cmd_set.cc#L142-L155

### Solution

we can add the error check `"value is not an integer or out of range"`. And then we add some go tests to match parsing errors. 

You can just add some codes for one class or more classes(in `set` or `zset`).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by infdahai** [comment]
Please add a `good first issue` label.

**Comment by infdahai** [comment]
This issue just needs to add `require.ErrorContains()` in go tests. If someone is willing to do this, leave a message here.

**Comment by zncleon** [comment]
I'd like to try it

**Comment by git-hulk** [comment]
@zncleon Assigned, go ahead. @infdahai Thanks for taking care of this PR.

**Comment by zncleon** [comment]
I have some questions:
1. In redis6.9, if I enter `SPOP myset 3.5` or `SPOP myset -10`, it return `value is out of range, must be positive`, but in kvrocks, it return `value is not a n integer out of range `.It seems that the return in kvrocks is clearer. Should I modify it just like redis or leave it as it is ？  

2. if I enter `SPOP myset 3 4`, the arguments more than 3, kvrocks not return error. I can modify the checks in source code. But I can't test it in go test, for the arguments num of the function `SPopN` is 3. How can I do ?

**Comment by git-hulk** [comment]
> In redis6.9, if I enter "SPOP myset 3.5" OR "SPOP myset -10", it return "value is out of range, must be positive", but in kvrocks, it return "value is not a n integer out of range ".It seems that the return in kvrocks is clearer. Should I modify it just like redis or leave it as it is ？

Just leave it as it's.

> if I enter "SPOP myset 3 4", the arguments more than 3, kvrocks not return error. I can modify the checks in source code. But I can't test it in go test, for the arguments num of the function "SPopN" is 3. How can I do ?

You can use `client.Do` to send the raw command.

**Comment by infdahai** [comment]
You can add a go test for computing results and a go test for getting error msgs to coverege the throwing errors  for the second label

**Comment by infdahai** [comment]
you can add a go test if you want to compute the commands and add another tests for parsing error msgs.(usually use Do func, because go-redis gives a correct num-key argument in special commands for redis.)

**Comment by zncleon** [comment]
thx !
