### ISSUE TITLE
process crash when running perflog on macos

### ISSUE THREAD

**Issue by singular-seal** [apache/kvrocks#1480]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

OS - macos 13.3.1 (a) 
Kvrocks - 2.4.0

### Minimal reproduce step

1.config set profiling-sample-commands set
2.config set profiling-sample-ratio 100
3.config set profiling-sample-record-threshold-ms 0
4.set a 1

Then the process crashed.

### What did you expect to see?

shows 'OK'

### What did you see instead?

process crashed

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @singular-seal 

Can you paste the core stack in logs file?

**Comment by singular-seal** [comment]
E20230601 21:40:46.598451 2739503 main.cc:86] ======= Ooops! kvrocks unstable (commit 4218a2b) got signal: Segmentation fault: 11 (11) =======
E20230601 21:40:46.608981 2739503 main.cc:101] 1   libsystem_platform.dylib            0x00007ff804ee35ed _sigtramp + 29                                                                                                                                                                                                      _sigtramp
E20230601 21:40:46.609074 2739503 main.cc:103] 2   ???                                 0x0000000000003f40 0x0 + 16192
E20230601 21:40:46.609315 2739503 main.cc:101] 3   kvrocks                             0x000000010e5e7cab _ZN5redis10Connection27RecordProfilingSampleIfNeedERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEy + 203                                                                                        redis::Connection::RecordProfilingSampleIfNeed()
E20230601 21:40:46.609545 2739503 main.cc:101] 4   kvrocks                             0x000000010e5e691a _ZN5redis10Connection15ExecuteCommandsEPNSt3__15dequeINS1_6vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS7_IS9_EEEENS7_ISB_EEEE + 3930                                                      redis::Connection::ExecuteCommands()
E20230601 21:40:46.609745 2739503 main.cc:101] 5   kvrocks                             0x000000010e5e56fe _ZN5redis10Connection6OnReadEP11bufferevent + 142                                                                                                                                                                   redis::Connection::OnRead()
E20230601 21:40:46.609944 2739503 main.cc:101] 6   kvrocks                             0x000000010eae9197 bufferevent_run_deferred_callbacks_unlocked + 215                                                                                                                                                                   bufferevent_run_deferred_callbacks_unlocked
E20230601 21:40:46.610144 2739503 main.cc:101] 7   kvrocks                             0x000000010eaf3e47 event_process_active_single_queue + 887                                                                                                                                                                             event_process_active_single_queue
E20230601 21:40:46.610344 2739503 main.cc:101] 8   kvrocks                             0x000000010eaf13ae event_base_loop + 1582                                                                                                                                                                                              event_base_loop
E20230601 21:40:46.610559 2739503 main.cc:101] 9   kvrocks                             0x000000010e60f968 _ZN6Worker3RunENSt3__111__thread_idE + 24                                                                                                                                                                           Worker::Run()
E20230601 21:40:46.610762 2739503 main.cc:101] 10  kvrocks                             0x000000010e61102a _ZNSt3__114__thread_proxyB6v15006INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN4util12CreateThreadIZN12WorkerThread5StartEvE3$_1EE8StatusOrINS_6threadEEPKcT_EUlvE_EEEEEPvSJ_ + 74  _ZNSt3__114__thread_proxyB6v15006INS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN4util12CreateThreadIZN12WorkerThread5StartEvE3$_1EE8StatusOrINS_6threadEEPKcT_EUlvE_EEEEEPvSJ_
E20230601 21:40:46.610807 2739503 main.cc:101] 11  libsystem_pthread.dylib             0x00007ff804eb61d3 _pthread_start + 125                                                                                                                                                                                                _pthread_start
E20230601 21:40:46.610857 2739503 main.cc:101] 12  libsystem_pthread.dylib             0x00007ff804eb1bd3 thread_start + 15                                                                                                                                                                                                   thread_start

**Comment by git-hulk** [comment]
@singular-seal Thanks for your feedback, I found the root cause, will fix it soon.

**Comment by singular-seal** [comment]
> @singular-seal Thanks for your feedback, I found the root cause, will fix it soon.

Thanks a lot for the quick response.
