### ISSUE TITLE
ZRANGE with LIMIT and COUNT=0

### ISSUE THREAD

**Issue by torwig** [apache/kvrocks#1483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

The latest `unstable`.

### Minimal reproduce step

```
127.0.0.1:6666> zadd zset11 1 a 2 b 3 c 4 d 5 e 6 f 7 g
(integer) 7
127.0.0.1:6666> zrange zset11 0 6 byscore limit 0 0
```

### What did you expect to see?

Redis:

```
127.0.0.1:6379> zadd zset11 1 a 2 b 3 c 4 d 5 e 6 f 7 g
(integer) 7
127.0.0.1:6379> zrange zset11 0 6 byscore limit 0 0
(empty array)
```

### What did you see instead?

Kvrocks:

```
127.0.0.1:6666> zrange zset11 0 6 byscore limit 0 0
1) "a"
2) "b"
3) "c"
4) "d"
5) "e"
6) "f"
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by infdahai** [comment]
Let me take a look at this

**Comment by torwig** [comment]
@infdahai Assigned. Thank you.
