### ISSUE TITLE
Don't allow to slaveof itself or its replica

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1484]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Currently, we didn't check if the master is itself or in its replica set, so it may cause a replication loop like the below:

```
127.0.0.1:6666> SLAVEOF 127.0.0.1 6666
OK
127.0.0.1:6666> info replication
# Replication
role:slave
master_host:127.0.0.1
master_port:6666
master_link_status:up
master_sync_unrecoverable_error:no
master_sync_in_progress:0
master_last_io_seconds_ago:2
slave_repl_offset:0
slave_priority:100
connected_slaves:1
slave0:ip=127.0.0.1,port=6666,offset=0,lag=0
master_repl_offset:0
```

### Solution

Check the master host/port before sending the command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jihuayu** [comment]
@git-hulk  If I use `SLAVEOF 127.0.0.2 6666`, how can it check that the master is itself? Or if I send traffic with IP address 172.20.100.2 to the server where the master is located and use `SLAVEOF 172.20.100.2 6666`, how can it check?

Judging based on the IP address and port is not accurate.

**Comment by git-hulk** [comment]
@jihuayu Firstly, we don't promise it can recognize all conditions since the traffic device mapping is complex. What we can do is try our best to avoid this condition, so I think the below checks are enough:

- if Kvrocks is listening on address 0.0.0.0, we parse the IP addresses from the device and compare the master host and port
- if Kvrocks is listening on the exact IP address, just compare the IP and Port directly

Can take a look at https://github.com/apache/incubator-kvrocks/blob/7554a0dc3e0735d7968a5126cc81e060ff1a441b/src/common/io_util.cc#L317

@uds5501 has taken this issue in the Slack channel.

**Comment by zevin02** [comment]
I think I can do it

**Comment by git-hulk** [comment]
Hi @zevin02

Thanks for your attention.

@uds5001 has already taken this in community slack channel, will ping back if he has no time to do that.

**Comment by uds5501** [comment]
I am working on it, should be able to raise an MR in a couple of days.

**Comment by git-hulk** [comment]
> I am working on it, should be able to raise an MR in a couple of days.

Thanks for your efforts. No hurry, can do it while you're free.
