### ISSUE TITLE
[proposal] Reduce the block cache configurations into a single one

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1495]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Historically, we have three configurations to control the block cache behavior:

- [rocksdb.metadata_block_cache_size](https://github.com/apache/incubator-kvrocks/blob/unstable/kvrocks.conf#LL530C1-L530C34) which will determine the block cache size of the metadata column family
- [rocksdb.subkey_block_cache_size](https://github.com/apache/incubator-kvrocks/blob/unstable/kvrocks.conf#LL535C1-L535C32) which will determine the block cache size of other column families
- [rocksdb.share_metadata_and_subkey_block_cache](https://github.com/apache/incubator-kvrocks/blob/unstable/kvrocks.conf#L542) which is used to determine whether to share the same block cache between column families.

But most users don't understand why we need to configure two block cache sizes without investigating the implementation. And it also didn't make sense to separate them since the user data may be changed as time elapsed.

### Solution

We can reduce them into a single one like `rocksdb.block_cache_size` and deprecate old configurations, and also remove them from the kvrocks.conf.

1. If the `rocksdb.block_cache_size` was set, then use it as the block cache and ignore old configurations.

2. If the `rocksdb.block_cache_size` was NOT and `rocksdb.share_metadata_and_subkey_block_cache` was enabled, then calculate the `rocksdb.block_cache_size` from `rocksdb.metadata_block_cache_size` and `rocksdb.share_metadata_and_subkey_block_cache`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@ShooterIT @PragmaTwice @torwig @caipengbo How do you think about this proposal?

**Comment by caipengbo** [comment]
I think this is a good proposal. It's more user friendly.

**Comment by Yangsx-1** [comment]
Can you assign this task to me? @git-hulk

**Comment by git-hulk** [comment]
Sure, thanks.
