### ISSUE TITLE
Convert the timeout parameter from an integer to a double value

### ISSUE THREAD

**Issue by Yangsx-1** [apache/kvrocks#1503]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

In redis, the timeout parameter of commands like [BLPOP](https://redis.io/commands/blpop/) is a double value, but in kvrocks, the parameter must be an integer.

### Solution

We can change `parseint` in the Parse function into `parsefloat`.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @Yangsx-1

Many thanks for your feedback. It should be a mistake in the Redis document, the timeout in the BLPOP is an integer indeed: https://github.com/redis/redis/blob/b00a2351865bb1d87e2d2701b77c8a68daefb054/src/t_list.c#L1218

**Comment by Yangsx-1** [comment]
> Hi @Yangsx-1
> 
> Many thanks for your feedback. It should be a mistake in the Redis document, the timeout in the BLPOP is an integer indeed: https://github.com/redis/redis/blob/b00a2351865bb1d87e2d2701b77c8a68daefb054/src/t_list.c#L1218

![1687001044238](https://github.com/apache/incubator-kvrocks/assets/85615957/72e11ebc-5acd-418e-bd9c-b90d811e1db4)
But i tested it locally, timeout can be floating-point number?

**Comment by git-hulk** [comment]
> > Hi @Yangsx-1
> > Many thanks for your feedback. It should be a mistake in the Redis document, the timeout in the BLPOP is an integer indeed: https://github.com/redis/redis/blob/b00a2351865bb1d87e2d2701b77c8a68daefb054/src/t_list.c#L1218
> 
> ![1687001044238](https://user-images.githubusercontent.com/85615957/246604544-72e11ebc-5acd-418e-bd9c-b90d811e1db4.png) But i tested it locally, timeout can be floating-point number?

oh, good. You're right that Redis will parse it as a double when the unit is a second:https://github.com/redis/redis/blob/b00a2351865bb1d87e2d2701b77c8a68daefb054/src/timeout.c#L171.

**Comment by git-hulk** [comment]
@Yangsx-1 assigned, thanks for your good catch.
