### ISSUE TITLE
Transferring resources out of the Incubator after graduation

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1509]
The vote for Kvrocks to graduate as a Top Level Project has been passed[1] and also established in the board meeting(2020-06-21). So we would like to transfer resources out of the incubator according to [Transferring Resources out of the Incubator](https://incubator.apache.org/guides/transferring.html) and this issue is used to track the checklist:

**Update the Incubator status records**
  - [x] Update the podling status page. All sections should now be filled in including EXIT. (Owner: @git-hulk)

**Source**
  - [x] Git repositories will be renamed to drop the incubator- prefix, please ensure that developers change their remotes. After you’ve created the TLP request, request the rename.(Owner: @git-hulk) - https://issues.apache.org/jira/browse/INFRA-24718
  - [x] SVN repositories will be moved from the incubator to other locations, if you need the move done please raise an infra ticket after the TLP Parent Request.(Owner: @git-hulk) - https://issues.apache.org/jira/browse/INFRA-24718
  - [x] Post an announcement to the development list telling everyone that the repository is about to be moved

**Websites**
- [x] If you have any fully qualified links to your podling.incubator.apache.org on your website change them

**Distribution mirrors**
- [x] Dist area (dist.apache.org) release/${project} and dev/${project} folders can be created by PMC members.
  - Do not forget to copy KEYS file from release/incubator/${project} location.
  - You have two major options then:
    - you can keep incubating released artifacts at release/incubator/${project} and remove artifacts once your TLP project does their first release.
    - you can move the last incubating released artifacts to your release/${project}, taking care that incubating stay in path (you will need to change website and mail for the new location)

**Final Revision of Podling Incubation Records**
- [x] Update the svn incubator/trunk/content/projects/${project}.xml file to show the project’s status. (Owner: @git-hulk)
- [x] Update the podling summary metadata file, incubator/trunk/content/podlings.xml svn file. (Owner: @git-hulk)
- [x] After your project has finished reporting to the Incubator, then remove the "reporting" element from that podlings.xml file.(Owner: @git-hulk)
- [x] Ensure that other svn resources for your project have moved to your new home.
- [x] Review this whole graduation guide.

[1] https://lists.apache.org/thread/hbl8fsy5pw0k2k6prx62r1v1r7n9psjr

**Comment by tisonkun** [comment]
@git-hulk could you link to the board resolution about the graduation so that it's transparent a resolution?

**Comment by git-hulk** [comment]
> @git-hulk could you link to the board resolution about the graduation so that it's transparent a resolution?

@tisonkun I only received the new role change notification: https://lists.apache.org/thread/ktlqnzl85mtvyyk8bw26f3rq0nl66pb2 for now, it contains the transfer resources guide.

**Comment by git-hulk** [comment]
Resources are transferred out of the incubator according to the guide. Will close this issue, can help to review and correct while you’re free. @PragmaTwice @tisonkun @torwig
