### ISSUE TITLE
Add the support of the HRANDFIELD comand

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1510]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [hrandfield](https://redis.io/commands/hrandfield/) command.

After this, we will support all the commands in the hash type from redis.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by infdahai** [comment]
Please add a good-first-issue label.

**Comment by zevin02** [comment]
please assign to me

**Comment by torwig** [comment]
@zevin02 Done. Thank you!
