### ISSUE TITLE
Add the support of the GEOSEARCH, GEOSEARCHSTORE comands 

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1511]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support [geosearch](https://redis.io/commands/geosearch/), [geosearchstore](https://redis.io/commands/geosearchstore/) commands.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by uds5501** [comment]
I can help with this.

**Comment by git-hulk** [comment]
@uds5501 assigned, thanks for your interest.

**Comment by uds5501** [comment]
@git-hulk / @infdahai does this command require a `BYBOX` as well? (Found it in the redis doc : https://redis.io/commands/geosearch/)
If yes, I wanted to understand how does the bounding box look like? Not able to visualize it just via this description:

**BYBOX: Search inside an axis-aligned rectangle, determined by <height> and <width>.**

edit : Wanted a confirmation, is the bounding box like this - https://www.memurai.com/blog/geospatial-queries-in-redis

**Comment by infdahai** [comment]
@uds5501 I think the blog is right. BTW, you can read this picture from the origin design https://github.com/redis/redis/issues/8094#issuecomment-739640315 . I think it's direct.
