### ISSUE TITLE
add the skip points for KeyRange

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1520]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Do we need to add a position to ignore the numkey integer because we only support a consistent range? For example, we add a wrong key currently in the `watch` command in [zdiffstore](https://redis.io/commands/zdiffstore/) and [zinterstore](https://redis.io/commands/zinterstore/).

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by infdahai** [comment]
@PragmaTwice do you think it is necessary?

**Comment by torwig** [comment]
@infdahai Could you please elaborate on this?  It's not clear to me from the `Motivation` part what issue you want to solve and what solution/solutions you consider/offer.

**Comment by infdahai** [comment]
I see the function iterates over `range.key_step`. And it will find the argument[i] to exec the watching.  https://github.com/apache/kvrocks/blob/8539ee50c7ed74dfd35a396d138efbc8bde65542/src/server/server.cc#L1659-L1670

**Comment by infdahai** [comment]
The unnecssary numkey will be added into the finding. I think it's innocuous because the numkey shouldn't exist in watched_key_map_.

I'll turn this off if you don't think it's necessary

**Comment by PragmaTwice** [comment]
The current key range design is divided to two methods:
- a *static* constant [start, end, step] if the key range can be determined without actual commands, e.g. `GET key`
- a *dynamic* [start, end, step] according to actual commands, e.g. `opname numkeys key... someflag`

To generalize the key range design to a more pervasive form, I think we can add the third method:
- a *static* constant [start, end, step] if the key range can be determined without actual commands, e.g. `GET key` -> [1,1,1]
- a *dynamic* [start, end, step] according to actual commands, e.g. `opname numkeys key... someflag` -> [2, 1+numkeys,1]
- a *dynamic* key position vector according to actual commands, e.g. `opname numkeys1 key1... someflags... numkeys2 key2... someflag` -> {2,3,...,1+numkeys1,4+numkeys1,...}

For the *skip points* idea, I think it seems not as straightforward as just a key position vector.

**Comment by infdahai** [comment]
Ok, I will add this method. That's a pretty immature *skip points*.

**Comment by infdahai** [comment]
BTW, do we use the vector to store `CommandKeyRange`? like this `{{2,1+numkeys,1},{4+numkeys,-1,1}}`

I think it will show well.

**Comment by PragmaTwice** [comment]
> BTW, do we use the vector to store `CommandKeyRange`? like this `{{2,1+numkeys,1},{4+numkeys,-1,1}}`
> 
> I think it will show well.

Looks fine to me.
