### ISSUE TITLE
Add the support of the LMPOP command 

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1526]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [lmpop](https://redis.io/commands/lmpop/) command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by HolyLow** [comment]
Hi, new guy here! I am willing to see how I could help on this issue. Please assign it to me if no others is working on this.

**Comment by git-hulk** [comment]
Hi @HolyLow, thanks for your interests, assigned

**Comment by JoverZhang** [comment]
Hi @HolyLow. Are you working on this issue? If not can I take it over?

**Comment by HolyLow** [comment]
@JoverZhang Hi, sorry for the reply delay, I am working on this issue already, and hopefully would propose the first version this week.

**Comment by HolyLow** [comment]
@git-hulk hi, I've opened a [PR](https://github.com/apache/kvrocks/pull/1737), but currently the (gocase) test cases are not added yet, as I am still trying to figure out how to launch the test case (in GoLand IDE, or from the x.py script...)

Any refer link on how to run the go test cases would be greatly appreciated.

**Comment by git-hulk** [comment]
Thank you! Can use Goland to run and debug test cases.

**Comment by PragmaTwice** [comment]
> Any refer link on how to run the go test cases would be greatly appreciated.

Please refer to https://kvrocks.apache.org/community/contributing .
