### ISSUE TITLE
Add the support of the LPOS command 

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [lpos](https://redis.io/commands/lpos/) command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JackTan25** [comment]
please assign me

**Comment by torwig** [comment]
@JackTan25 Done. Thank you!

**Comment by JackTan25** [comment]
hi, is there a reference pr for other commands? I'm sorry for that I'm little busy in the past days, there's no much progress on here. I will try to work on it now.
