### ISSUE TITLE
Add the support of the LRANGE command

### ISSUE THREAD

**Issue by infdahai** [apache/kvrocks#1529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [lrange](https://redis.io/commands/lrange/) command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by torwig** [comment]
@infdahai If I'm not mistaken, Kvrocks supports the `LRANGE` command.

**Comment by infdahai** [comment]
You are right. I close this issue now.
