### ISSUE TITLE
Running the `memory usage` command against a non-existent key resulted in an error

### ISSUE THREAD

**Issue by fosmjo** [apache/kvrocks#1538]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

kvrocks 2.4.0

### Minimal reproduce step

```sh
memory usage key-not-exist
```

### What did you expect to see?

return `nil`

### What did you see instead?

```sh
(error) ERROR NotFound: Not found : key-not-exist
```

### Anything Else?

This is not compatible with redis, which return `nil` when the key does not exist, and will cause [asynqmon](https://github.com/hibiken/asynqmon) failed sometimes when using `memory usage` command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@fosmjo Thanks for your feedback.
