### ISSUE TITLE
Flaky test TestZset ZRANGEBYSCORE_fuzzy_test

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#1552]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

master

### Minimal reproduce step

```
--- FAIL: TestZset (6.77s)
    --- FAIL: TestZset/ZRANGEBYSCORE_fuzzy_test,_100_ranges_in_100_element_sorted_set_-_skiplist (1.45s)
        assertions.go:37: 
            	Error Trace:	/home/runner/work/kvrocks/kvrocks/tests/gocase/unit/type/zset/assertions.go:37
            	            				/home/runner/work/kvrocks/kvrocks/tests/gocase/unit/type/zset/zset_test.go:1330
            	Error:      	"0.8835915986346754" is not less than or equal to "0.88359158989[119](https://github.com/apache/kvrocks/actions/runs/5465748637/jobs/9950010260#step:12:120)87"
            	Test:       	TestZset/ZRANGEBYSCORE_fuzzy_test,_100_ranges_in_100_element_sorted_set_-_skiplist
FAIL
```

### What did you expect to see?

Test passed.

### What did you see instead?

Test failed.

### Anything Else?

This seems a bug on float precision. I don't think it's about test suite precision but the server handling on precision.

cc @git-hulk @mwish

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by infdahai** [comment]
It may have been caused by this problem about double and float conversion from initial observations if the client executes right.

https://github.com/apache/kvrocks/blob/7e23c0bea1eb3d9c561af2dc110ebb803e0f32fe/src/types/redis_zset.cc#L517-L534

And I'm not sure the handling here either.
https://github.com/apache/kvrocks/blob/7e23c0bea1eb3d9c561af2dc110ebb803e0f32fe/tests/gocase/unit/type/zset/zset_test.go#L1309-L1321

**Comment by git-hulk** [comment]
@tisonkun Yes, it's a precision issue caused by the `strtod` which parsed the string "0.88359158989" as "0.88359158988999997". But Redis also has this issue, so I think it would be good to fix the test case only.

```
❯ redis-cli
127.0.0.1:6379> zadd z 0.88359158989 k1
(integer) 1
127.0.0.1:6379> zrange z 0 1 withscores
1) "k1"
2) "0.88359158988999997"
```
