### ISSUE TITLE
Tools: add `bugprone-use-after-move` checkings in clang-tidy

### ISSUE THREAD

**Issue by mapleFU** [apache/kvrocks#1564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Clang-tidy support some checkings like `bugprone-use-after-move`, which can be used to detect some use-after-move cases, and helps us make less bugs. We can enable some of the checkings.

### Solution

```
def clang_tidy(dir: str, jobs: Optional[int], clang_tidy_path: str, run_clang_tidy_path: str, fix: bool) -> None:
    ...
    options.append(f'-header-filter={"|".join(regexes)}')
+    options.append(f'-checks=bugprone-use-after-move')

    run(run_command, *options, *regexes, verbose=True, cwd=basedir)
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
You need to add them to `.clang-tidy` instead of modifying `x.py`.

**Comment by mapleFU** [comment]
@PragmaTwice I've add one in https://github.com/apache/kvrocks/pull/1566, would you mind take a look? And is there any more checkings could be added?

**Comment by mapleFU** [comment]
Closed by https://github.com/apache/kvrocks/pull/1566
