### ISSUE TITLE
Style: Change `Storage::SetReadOptions` to `Storage::DefaultScanOptions`

### ISSUE THREAD

**Issue by mapleFU** [apache/kvrocks#1572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

```c++
class Storage {
 public:
  explicit Storage(Config *config);
  
  void SetWriteOptions(const Config::RocksDB::WriteOptions &config);
  void SetReadOptions(rocksdb::ReadOptions &read_options);

  const rocksdb::WriteOptions &DefaultWriteOptions() { return write_opts_; }
};
```

Now kvrocks has `SetWriteOptions` and `SetReadOptions`. However, there syntax doesn't same. `SetWriteOptions` would set the `Storage` internal `rocksdb::WriteOptions` during intialize, and the detail option can be get by `DefaultWriteOptions()`.

However, `SetReadOptions` only does some fixup when called:

```c++
void Storage::SetReadOptions(rocksdb::ReadOptions &read_options) {
  read_options.fill_cache = false;
  read_options.async_io = config_->rocks_db.read_options.async_io;
}
```

Would we create a `DefaultScanOptions`, and remove `SetReadOptions` for that ?

### Solution

```c++
class Storage {
 public:
  explicit Storage(Config *config);
  
  void SetWriteOptions(const Config::RocksDB::WriteOptions &config);
-  void SetReadOptions(rocksdb::ReadOptions &read_options);

  const rocksdb::WriteOptions &DefaultWriteOptions() { return write_opts_; }
+ rocksdb::ReadOptions DefaultScanOptions();
};
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Sounds good to me
