### ISSUE TITLE
Add an archlinux environment for building and testing in CI 

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

ArchLinux is a main linux distro branch, as well as Debian (Ubuntu), RHEL (CentOS) and SUSE. So we can build and test kvrocks in an archlinux environment.

### Solution

It is a successor to https://github.com/apache/kvrocks/pull/1569. We can just implement the env based on it.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by aleksraiden** [comment]
Maybe we can use something like this - https://github.com/zaoqi/github-actions-archlinux

**Comment by Yangsx-1** [comment]
Let me try. :)

**Comment by PragmaTwice** [comment]
> Maybe we can use something like this - https://github.com/zaoqi/github-actions-archlinux

We can use the archlinux image directly: https://hub.docker.com/_/archlinux
