### ISSUE TITLE
Add the support of the XGROUP CREATE and DESTROY command

### ISSUE THREAD

**Issue by Yangsx-1** [apache/kvrocks#1586]
This issue intend to implement [XGROUP CREATE](https://redis.io/commands/xgroup-create/) and [XGROUP DESTROY](https://redis.io/commands/xgroup-destroy/) like redis.

see #1654 for more discusstions

**Comment by Yangsx-1** [comment]
I'll do this when i'm free.  :)

**Comment by git-hulk** [comment]
@Yangsx-1 assigned, thanks
