### ISSUE TITLE
Add the support of the XREADGROUP command

### ISSUE THREAD

**Issue by Yangsx-1** [apache/kvrocks#1588]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue intend to implement [XREADGROUP](https://redis.io/commands/xreadgroup/) command like redis.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ptbxzrt** [comment]
Hello! Can I have a try?

**Comment by Yangsx-1** [comment]
Hi! @ptbxzrt You can start doing this task when available.  :)
Please refer to #1654 and #1704 for the design.
