### ISSUE TITLE
when i use redisbenchmark set key ,then  " info keyspace" cannt get right result

### ISSUE THREAD

**Issue by jcy1001** [apache/kvrocks#1594]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

2.5.0

### Minimal reproduce step

when i use redisbenchmark set key ,then  " info keyspace" cannt get right result

### What did you expect to see?

the same ,no change

### What did you see instead?

new value

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @jcy1001, do you mean the key number is not correct? if yes, can take a look at: https://kvrocks.apache.org/docs/faq

**Comment by jcy1001** [comment]
OK

**Comment by jcy1001** [comment]
![image](https://github.com/apache/kvrocks/assets/24226340/861b2e29-a0cc-4da1-8ea8-80d65653817f)
only keys not change

**Comment by git-hulk** [comment]
I will close this issue soon, free feel to reopen it if needed.

**Comment by jcy1001** [comment]
![image](https://github.com/apache/kvrocks/assets/24226340/114aa5c4-cf63-4ec5-b568-514a94ad72f2)

i do like that  ,but i found it occur again

**Comment by jcy1001** [comment]
![image](https://github.com/apache/kvrocks/assets/24226340/d200183d-4a74-46a7-97c0-2f10eb86c7c8)
there are so many keys

**Comment by jcy1001** [comment]
@git-hulk

**Comment by git-hulk** [comment]
It's still scanning the db, please take a look later.
