### ISSUE TITLE
redis-benchmark  --cluster  Could not fetch node CONFIG

### ISSUE THREAD

**Issue by jcy1001** [apache/kvrocks#1599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

i use redis7.0 redis-benchark  option --cluster  found  it warning 

[root@localhost ~]# /root/redis-7.0.12/src/redis-benchmark --cluster  -h 10.168.106.187 -p  3001 -n 1000000 -c 10 -d  100  -r 1000000000 -q -t set
Cluster has 12 master nodes:

Master 0: kvrockskvrockskvrockskvrockskvrocksnod19 10.168.106.187:3019
WARNING: Could not fetch node CONFIG 10.168.106.187:3019
Master 1: kvrockskvrockskvrockskvrockskvrocksnode5 10.168.106.187:3005
WARNING: Could not fetch node CONFIG 10.168.106.187:3005
Master 2: kvrockskvrockskvrockskvrockskvrocksnod21 10.168.106.187:3021
WARNING: Could not fetch node CONFIG 10.168.106.187:3021
Master 3: kvrockskvrockskvrockskvrockskvrocksnod13 10.168.106.187:3013
WARNING: Could not fetch node CONFIG 10.168.106.187:3013
.....................................
................

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@jcy1001 It's expected due to Kvrocks don't support the config get 'save' and 'appendonly', but it won't affect the benchmark result. For more information, please refer: https://github.com/redis/redis/blob/b35e20d1defe5cb77e54de583b01d669200a3a51/src/redis-benchmark.c#L325

**Comment by jcy1001** [comment]
@git-hulk ok
