### ISSUE TITLE
Add the support of the RESTORE command

### ISSUE THREAD

**Issue by taiheyp** [apache/kvrocks#1648]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue considers to support the [DUMP](https://redis.io/commands/dump/) / [RESTORE](https://redis.io/commands/restore/) command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @taiheyp, thanks for your report. Will add it to our community roadmap and update you if have any progress.
