### ISSUE TITLE
SISMEMBER behaviour differs from redis

### ISSUE THREAD

**Issue by Rafiot** [apache/kvrocks#1659]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

Ubuntu 23.04

kvrocks 2.4 and 2.5

### Minimal reproduce step

`SISMEMBER foo bar` (if `foo` doesn't exist)

### What did you expect to see?

0 (as redis does: https://redis.io/commands/sismember/):

```
127.0.0.1:6379> SISMEMBER foo bar 
(integer) 0
```

### What did you see instead?

```
127.0.0.1:6666> SISMEMBER foo bar 
(error) ERR NotFound: 
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@Rafiot Thanks for your report.

**Comment by Rafiot** [comment]
Thanks!
