### ISSUE TITLE
Kvrocks can't guarantee atomicity for multiple keys commands

### ISSUE THREAD

**Issue by ShooterIT** [apache/kvrocks#1692]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

In kvrocks, for multiple keys commands, we may break atomicity.
such as `SDIFF、SUNIONSTORE、SINTERSTORE、SDIFFSTORE、ZUNIONSTORE、ZINTERSTORE`

For `SDIFFSTORE destination key1 [key2 ...]` command, kvrocks will read key1, key2 ... orderly without any lock, and then restore the diff into destination key. So maybe some keys may be changed when we read them orderly, that breaks atomicity but redis can guarantee atomicity.

Thank you @oranagra reports this.

### Solution

Now we have `MultiLockGuard`, i think it is easy to fix this.  We can lock these keys before we read or write, so it is impossible to change these keys.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by enjoy-binbin** [comment]
I noticed this earlier, since i worked on #1596 and #1634, but forgot to follow up.
it is good that oran mention it again, i will work on it and check all commands.

**Comment by enjoy-binbin** [comment]
> In kvrocks, for multiple keys commands, we may break atomicity.
such as SDIFF、SUNIONSTORE、SINTERSTORE、SDIFFSTORE、ZUNIONSTORE、ZINTERSTORE

Does SDIFF/SUNION/SINTER/SDIFF/ZUNION/ZINTER need support?

**Comment by ShooterIT** [comment]
does #1700 fix all multiple keys commands, do you check?

the below all are covered?

`DEL、SORT、MGET、MSET、BITOP、EXISTS、MSETNX、RENAME、 RENAMENX、BLPOP、BRPOP、RPOPLPUSH、BRPOPLPUSH、SMOVE、SUNION、SINTER、SDIFF、SUNIONSTORE、SINTERSTORE、SDIFFSTORE、ZUNIONSTORE、ZINTERSTORE、 PFMERGE、PFCOUNT`

**Comment by enjoy-binbin** [comment]
> does https://github.com/apache/kvrocks/pull/1700 fix all multiple keys commands, do you check?

no it doesn't. i checked roughly and #1700 only handles set/zset related set multi key operations.

For these commands you mentions:
- DEL or UNLINK now is a loop that del each key, we need to change it to batch write in the future.
- These commands are not yet supported by kvrocks: SORT / RENAME / RENAMENX / BRPOPLPUSH / PFMERGE / PFCOUNT
- These commands i think are ok (or are covered): MSET / RPOPLPUSH / SMOVE / SUNION / SINTER / SDIFF / SUNIONSTORE / SINTERSTORE / SDIFFSTORE / ZUNIONSTORE / ZINTERSTORE

so for commands like MGET / EXISTS, do we also need to lock all the keys? i am not familiar with BITOP, i will check it later

**Comment by git-hulk** [comment]
> so for commands like MGET / EXISTS, do we also need to lock all the keys?

I think it's unnecessary since we're using the snapshot.

**Comment by ShooterIT** [comment]
Yes, it is ok for MGET / EXISTS command.

so we just need to fix `DEL, UNLINK `?

**Comment by ShooterIT** [comment]
let's reopen it since there are some remaining things

**Comment by enjoy-binbin** [comment]
> so we just need to fix DEL, UNLINK ?

yep, i think so, i will find some times to fix it
