### ISSUE TITLE
Support `Get` with `rocksdb::PinnableSlice` to decrease copy for BLOB

### ISSUE THREAD

**Issue by mapleFU** [apache/kvrocks#1722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

RocksDB has support Get with `PinnableSlice` [1][2], and it's already used in `MultiGet` in our kvrocks[3]. For most of our objects, they're small object. So this might not get any benefits. However, as for type like Bitmap, BloomFilter. This could avoid copying memory.

[1] https://rocksdb.org/blog/2017/08/24/pinnableslice.html
[2] https://github.com/facebook/rocksdb/blob/main/include/rocksdb/db.h
[3] https://github.com/apache/kvrocks/blob/e2baeb1b2cdeb480d02b74d4eff23f2c418bc3e7/src/storage/storage.h#L109

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
@zncleon Would you like to support this? Since this can benefit the performance of BloomFilter.

A benchmark would better also be support here to verify that it really optimize our system.

**Comment by zncleon** [comment]
Sure, I am willing to support this.

**Comment by mapleFU** [comment]
Also cc @PragmaTwice @git-hulk , can we import google benchmark ( https://github.com/google/benchmark ) as a tool, and use it to do some micro benchmark?

**Comment by git-hulk** [comment]
Yes, that's great if we can do it regularly or in CI.

**Comment by PragmaTwice** [comment]
> Also cc @PragmaTwice @git-hulk , can we import google benchmark ( https://github.com/google/benchmark ) as a tool, and use it to do some micro benchmark?

Sure.

**Comment by ameya-deshmukh** [comment]
@zncleon can I take this up if you don't have the bandwidth? I am a first time contributor to the repo and this seems right up my alley.

**Comment by mapleFU** [comment]
Would you still want work on this @zncleon ?

**Comment by zncleon** [comment]
> @zncleon can I take this up if you don't have the bandwidth? I am a first time contributor to the repo and this seems right up my alley.

OK, you can take this up.

**Comment by mapleFU** [comment]
@ameya-deshmukh You can finish the patch and at me for review :-)

**Comment by chrisxu333** [comment]
Hello @mapleFU is this task still available to do? If so I'd like to take this.

**Comment by git-hulk** [comment]
@mapleFU Thanks for your interest! I assigned it to you since no one is working on this issue.

**Comment by mapleFU** [comment]
@chrisxu333 Just go ahead, finishing this need to support Get with `rocksdb::PinnableSlice` in `Storage`.

When you finish this, you can try to write a benchmark, and tell use what's the BLOB size that `Get` with `rocksdb::PinnableSlice` would be faster.

**Comment by chrisxu333** [comment]
@mapleFU Sounds good I'll go ahead and do it.

**Comment by mapleFU** [comment]
Yes you can @ me if you finished or need any help.

**Comment by chrisxu333** [comment]
@mapleFU I just finished supporting Get with PinnableSlice. Since you also mentioned writing a benchmark, do you mean using the Google benchmark mentioned previously in this thread? Or something else?

**Comment by mapleFU** [comment]
@chrisxu333 Sorry for late replying, I've too many mails so I forget to check this issue. T_T

You can use google benchmark to test. Though testing RocksDB(including disk io) with google-benchmark looks weird, I think the performance benifits of `rocksdb::PinnableSlice` is avoid copying in memory rather than disk io, so we can assume that all data is in memory during benchmarking. We can test the data in memtable or on sst, if the data is in memtable, just calling different `Get` is ok. And if the data is in SSTable, you can just try to Get the data first to make sure it's loaded in block cache or memtable, then calling `Get`

If introducing googlebenchmark would be heavy, you can try to write a script to testing and paste the result here. So that we can know whether the `Get` with `PinnableSlice` can benefit `BloomFilter` and `Bitmap` types in kvrocks. And you can submit the patch without the benchmark code for convenience.

**Comment by chrisxu333** [comment]
@mapleFU Sorry I was also busy on other stuff :( I just submitted the patch without benchmark code for reference. 

For the benchmark part, are you saying testing on the raw rocksdb api in the storage class, or on a higher level where we manipulate bloomfilter and bitmap type? :)

**Comment by mapleFU** [comment]
> For the benchmark part, are you saying testing on the raw rocksdb api in the storage class, or on a higher level where we manipulate bloomfilter and bitmap type? :)

I think raw test is ok. Because we know the pattern here:
1. BITMAP: usally one or multiple 8KiB value
2. BloomFilter: might greater than 8KiB, but will not too large

Maybe testing from 8KiB, 16KiB and 64KiB is ok.

**Comment by chrisxu333** [comment]
> I think raw test is ok. Because we know the pattern here:
> 
> 1. BITMAP: usally one or multiple 8KiB value
> 2. BloomFilter: might greater than 8KiB, but will not too large
> 
> Maybe testing from 8KiB, 16KiB and 64KiB is ok.

Sounds good. I just did some testing using my script on the raw storage api. Here is the result.

<img src="https://github.com/apache/kvrocks/assets/44099579/86a61c9d-ab5c-4b93-ab34-25689793ab7a" width="500">

<img src="https://github.com/apache/kvrocks/assets/44099579/5b1346bf-c4dd-4e8e-97a3-339843e55fa5" width="500">

P.S. These execution times are averaged among multiple `get()` calls. We could see the speedup is increasing as the size of value increases, which is what we want :)

**Comment by mapleFU** [comment]
Great! Also cc @git-hulk @PragmaTwice

**Comment by git-hulk** [comment]
Looks good. Seems the pinnable slice won't bring any side effects.
