### ISSUE TITLE
Large amount of failure of TestNamespace/Concurrent_creating_namespaces in CI

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1728]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

https://github.com/apache/kvrocks/actions/runs/6062050794/job/16447962006?pr=1712
https://github.com/apache/kvrocks/actions/runs/6062030374/job/16447930241?pr=1630
https://github.com/apache/kvrocks/actions/runs/6062030374/job/16447930290?pr=1630
...

cc @git-hulk 

### What did you expect to see?

-

### What did you see instead?

-

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
It may be related to #1727 which changed the random string.

**Comment by PragmaTwice** [comment]
> It may be related to #1727 which changed the random string.

cc @mapleFU
