### ISSUE TITLE
Add support of the XCLAIM command

### ISSUE THREAD

**Issue by Yangsx-1** [apache/kvrocks#1733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue wants to implement [XCLAIM](https://redis.io/commands/xclaim/) command like redis.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Beihao-Zhou** [comment]
Hi @Yangsx-1 ! I want to work on the issue, can you please assign it to me? Thank you!

**Comment by Yangsx-1** [comment]
> Hi @Yangsx-1 ! I want to work on the issue, can you please assign it to me? Thank you!

Assigned, thank you!
