### ISSUE TITLE
Add support of the XPENDING command

### ISSUE THREAD

**Issue by Yangsx-1** [apache/kvrocks#1734]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue wants to implement [XPENDING](https://redis.io/commands/xpending/) command like redis.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LiuYuHui** [comment]
I will working on it, please assign it to me :D

**Comment by Yangsx-1** [comment]
> I will working on it, please assign it to me :D

Assigned, thank you!
