### ISSUE TITLE
slowlog support return more info

### ISSUE THREAD

**Issue by luger1990** [apache/kvrocks#1736]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

from https://redis.io/commands/slowlog-get/ we can see, slowlog of redis suppprt return six values(Starting with Redis version 4.0.0: Added client IP address, port and name to the reply.):
1. A unique progressive identifier for every slow log entry.
2. The unix timestamp at which the logged command was processed.
3. The amount of time needed for its execution, in microseconds.
4. The array composing the arguments of the command.
5. Client IP address and port.
6. Client name if set via the [CLIENT SETNAME](https://redis.io/commands/client-setname) command.
but kvrocks only support first for values.

### Solution

add more info to slowlog cammand

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@luger1990 Thanks for your suggestion.

**Comment by LiuYuHui** [comment]
Hi @git-hulk , I want to work on it, could you please assign it to me?

**Comment by git-hulk** [comment]
Hi @LiuYuHui Thanks for your interest, assigned.

**Comment by git-hulk** [comment]
Resolved by #1740
