### ISSUE TITLE
Redis Trademark Violation

### ISSUE THREAD

**Issue by thallredis** [apache/kvrocks#1742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

Current website and associated docs: https://kvrocks.apache.org/

### Minimal reproduce step

Have a look at the copyrights that you are currently acknowledging...all of the Apache Software Foundation related ones.

### What did you expect to see?

We would appreciate you acknowledging the Redis trademark as well as your own copyrights.

### What did you see instead?

Missing trademark attribution for the use of Redis.

### Anything Else?

Thank you in advance for addressing this in a timely manner.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Hi @thallredis,

Thanks for your reporting! We highly appreciate the work Redis does and https://github.com/apache/kvrocks-website/pull/153 includes a sentence to reflect Redis trademarks. Could you please check if the current status meets the related policy?

**Comment by tisonkun** [comment]
Closed as resolved. Feel free to open a new issue if you find any other improvements.
