### ISSUE TITLE
Add the support of loading data from RDB file

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1753]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

#1684 supports parsing serialized binary formats from Redis
which is also the key implementation of loading the Redis RDB file.
So after that, I think we can support loading data from the RDB file directly.

### Solution

Implement other parts of parsing the RDB file.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xq2010** [comment]
I'm willing to submit a PR and will finish it next month.

**Comment by git-hulk** [comment]
@xq2010 Assigned, feel free to ask any questions if you need.

**Comment by xq2010** [comment]
@git-hulk  There is a commit in this pr:https://github.com/apache/kvrocks/pull/1798

**Comment by git-hulk** [comment]
> @git-hulk There is a commit in this pr:#1798

Thanks for your efforts!
