### ISSUE TITLE
slices.Compact

### ISSUE THREAD

**Issue by Deleplace** [apache/kvrocks#1770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

Hello, while researching for [this Go proposal](https://github.com/golang/go/issues/62729) I noticed [4 occurrences](https://github.com/search?q=repo%3Aapache%2Fkvrocks%20slices.Compact&type=code) of this pattern:

```
slices.Compact(keys)
```

which doesn't do what it seems to do, and should look like this instead:

```
keys = slices.Compact(keys)
```

I have not tried to execute it.

### Minimal reproduce step

Look at https://github.com/search?q=repo%3Aapache%2Fkvrocks%20slices.Compact&type=code

### What did you expect to see?

keys = slices.Compact(keys)

### What did you see instead?

slices.Compact(keys)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@Deleplace Thanks for your feedback, it's exactly a bug.

**Comment by tisonkun** [comment]
@Deleplace Thanks for your reporting! It should be now fixed by #1771.
