### ISSUE TITLE
Add the sanity check for docker image

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1793]
We'd better add some sanity checks in:

https://github.com/apache/kvrocks/blob/7f0c5156493dc3601bbc6f2157f9fa1d8462ea51/.github/workflows/kvrocks.yaml#L292-L309

_Originally posted by @tisonkun in https://github.com/apache/kvrocks/issues/1784#issuecomment-1735890155_

As mentioned in the comments, we at least check if the docker listening port can be accessed from outside.

**Comment by jyf111** [comment]
How about using the following commands? @git-hulk 

```shell
id="$(docker run --rm -d -p 6666:6666 kvrocks:ci)"
sleep 1m # waiting for the periodic container health check

if [ "$(docker inspect --format='{{.State.Health.Status}}' $id)" != "healthy" ]; then
  echo "Container is not healthy."
  exit 1
fi

if [ "$(ss --listening --no-header --tcp '( sport = :6666 )')" == "" ]; then
  echo "The container listening port can not be accessed from outside."
  exit 1
fi

docker stop $id
```

**Comment by git-hulk** [comment]
@jyf111 Looks good, thank you.
