### ISSUE TITLE
Add parameters to clean test data and build result in x.py

### ISSUE THREAD

**Issue by Yangsx-1** [apache/kvrocks#1801]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

I found the go test data in tests/gocase/workspace occupied too much disk space locally, so it may be more convenient for developers to clean the test data if we add a parameter in x.py for this task. 

May be we can also add a parameter to clean the build result for totally rebuilding.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
You can pass `deleteOnExit` flag to `go test` to remove files in workspace dir.

https://github.com/apache/kvrocks/blob/e38021ca509d21624957f217aae516360ff77adb/tests/gocase/util/flags.go#L26

**Comment by Yangsx-1** [comment]
> You can pass `deleteOnExit` flag to `go test` to remove files in workspace dir.
> 
> https://github.com/apache/kvrocks/blob/e38021ca509d21624957f217aae516360ff77adb/tests/gocase/util/flags.go#L26

Thank you!
