### ISSUE TITLE
Add the support of changing worker threads in-flight

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

It's hard to know the application workload as the time goes,
so that's impossible to estimate the right number of worker threads
to fulfill the workload requirement. So it'd be great if we can change
the worker thread number in-flight, and we don't need to worry much about
it's suitable at the beginning.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by guojidan** [comment]
provide a server command to change worker thread num in-flight?

**Comment by guojidan** [comment]
assign to me : )

**Comment by PragmaTwice** [comment]
Hi @guojidan , assigned!

BTW here we can just use `CONFIG SET ..` instead of a new command.

Refer to [config.cc](https://github.com/apache/kvrocks/blob/unstable/src/config/config.cc) for more details.

**Comment by guojidan** [comment]
thanks

**Comment by xiaobiaozhao** [comment]
@guojidan Do you have any ideas? I'm interested in this. I think we can talk about this.

**Comment by guojidan** [comment]
I have implemented a version，but I don't think it's good，Do you have any better ideas？ https://github.com/apache/kvrocks/commit/4b627a99cbbb071f9e00d57d9e1ccfe52ead88bd

**Comment by xiaobiaozhao** [comment]
If I look at this commit, there is nothing wrong with the big logic, what needs to be considered is how to do thread exit.

**Comment by guojidan** [comment]
Is it limited worker_num to greater than 1, I think 1 workers is Meaningless ,  and I think long connections can be transferred to other threads on exit

**Comment by guojidan** [comment]
take look @xiaobiaozhao  https://github.com/guojidan/kvrocks/commit/3b0c4b7d9190c5ffc6d1f3a4658cdf48e75bfdba

**Comment by guojidan** [comment]
I can't handle long connections properly, so let other people interested in it implement this issue, I will close pr and unassign to me.

**Comment by git-hulk** [comment]
@guojidan Thanks for your efforts. Let me take it and welcome to help review if you like.
