### ISSUE TITLE
Add support for the JSON.ARRAPPEND command

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1806]
Please refer to #1805.

**Comment by lieck** [comment]
I want to take this issue, thanks.

**Comment by git-hulk** [comment]
@lieck Assigned, thank you!

**Comment by mapleFU** [comment]
Oh I found a interesting thing in RedisJson...

```
///
/// JSON.ARRAPPEND <key> <path> <json> [json ...]
///
pub fn json_arr_append<M: Manager>(
    manager: M,
    ctx: &Context,
    args: Vec<RedisString>,
) -> RedisResult;
```

The code of it is `JSON.ARRAPPEND <key> <path> <json>`. But the document of it says the path is optional, it's so misleading...

Our current impl is right
