### ISSUE TITLE
Add support for the JSON.DEL command

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1813]
Please refer to https://github.com/apache/kvrocks/issues/1805.

**Comment by Qiaolin-Yu** [comment]
I want to try this. Can you assign this to me?

**Comment by PragmaTwice** [comment]
Sure. Please go ahead : )

**Comment by PragmaTwice** [comment]
BTW I think for this command the implementation may be a bit tricky since it may be not easy to retrieve the parent object of a object located by jsonpath in jsoncons.

But of course you can do some research to solve it. Good luck!

**Comment by Qiaolin-Yu** [comment]
> BTW I think for this command the implementation may be a bit tricky since it may be not easy to retrieve the parent object of a object located by jsonpath in jsoncons.
> 
> But of course you can do some research to solve it. Good luck!

 I have indeed recognized this problem when attempting to retrieve the parent object of a targeted object. I've tried several methods but still face the issue. Do you have any suggestions on how to address this in `jsoncons::jsonpath`?

**Comment by PragmaTwice** [comment]
Hi @Qiaolin-Yu , you can refer to https://github.com/danielaparker/jsoncons/issues/467.

**Comment by Qiaolin-Yu** [comment]
> Hi @Qiaolin-Yu , you can refer to [danielaparker/jsoncons#467](https://github.com/danielaparker/jsoncons/issues/467).

Thank you very much. I'll try it right away.
