### ISSUE TITLE
Add support for the JSON.MGET command

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1816]
Please refer to https://github.com/apache/kvrocks/issues/1805.

**Comment by skyitachi** [comment]
I want to pick up this issue

**Comment by git-hulk** [comment]
@skyitachi Assigned, thank you!

**Comment by git-hulk** [comment]
@skyitachi Are you still working on this issue?

**Comment by skyitachi** [comment]
yes, my computer is broken, this week maybe repaired :)

**Comment by git-hulk** [comment]
@skyitachi Thank you!
