### ISSUE TITLE
Add support for the JSON.MSET command

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1817]
Please refer to https://github.com/apache/kvrocks/issues/1805.

**Comment by chakkk309** [comment]
Hi, I want to try this task~

**Comment by PragmaTwice** [comment]
Assigned. Go ahead!

**Comment by git-hulk** [comment]
@chakkk309 Are you working on this issue?

**Comment by chakkk309** [comment]
> @chakkk309 Are you working on this issue?

Hi, this issue still working in progress.

**Comment by git-hulk** [comment]
OK, thank you!

**Comment by zjregee** [comment]
Is anyone working on it? I'd like to submit a PR to close this issue.

**Comment by git-hulk** [comment]
@zjregee Thank you! I have reassigned this issue to you.
