### ISSUE TITLE
Add support for the JSON.RESP command

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1822]
Please refer to https://github.com/apache/kvrocks/issues/1805.

**Comment by venkatdatta0** [comment]
Hi @PragmaTwice @git-hulk 

I am new to open source community.

Can i work on this task?

**Comment by venkatdatta0** [comment]
In Redis document, this particular method is marked as deprecated.

https://redis.io/commands/json.resp/

Do we want to add support for RESP?

**Comment by git-hulk** [comment]
@venkatdatta0 Surely yes, if you're willing to support this.

**Comment by jonathanc-n** [comment]
@venkatdatta0 Can i assume you are not working on this anymore? I am interested in working on this.

**Comment by git-hulk** [comment]
@jonathanc-n Thanks for mentioning this issue. It has been supported in #2390, will close this issue.
