### ISSUE TITLE
Refactor kvrocks2redis via rocksdb secondary instance

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1832]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Currently kvrocks2redis using network connections to catch up with incremental data. We can use [Read only and Secondary instances](https://github.com/facebook/rocksdb/wiki/Read-only-and-Secondary-instances) in RocksDB to remove such network connections.

cc @git-hulk 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by maochongxin** [comment]
Hi @PragmaTwice , I'm interested in this issue. Can I give it a try?

**Comment by PragmaTwice** [comment]
> Hi @PragmaTwice , I'm interested in this issue. Can I give it a try?

Sure! Assigned.
