### ISSUE TITLE
Compact on all cf with same range?

### ISSUE THREAD

**Issue by raffertyyu** [apache/kvrocks#1864]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

1142a9d87ac6c404dcf4e0d06778af9ae738539b

### Minimal reproduce step

none

### What did you expect to see?

call compact on specific cf

### What did you see instead?

call compact on all cf

### Anything Else?

In method `CompactionChecker::PickCompactionFiles`, kvrocks will search all sst files in cf specified by `cf_name`. If a sst file should be compacted, kvrocks will call 
```
storage_->Compact(&start_key, &stop_key)
```
But, `Compact` method will CompactRange on all cfs.

Expected:
`Compact` method needs a `cf_name` parameter to do compact on right cf not all cfs.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Good catch! Feel free to submit a PR if you are willing to fix it.

**Comment by raffertyyu** [comment]
OK, I will fix it.
