### ISSUE TITLE
Data race in namespace get

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1873]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

https://github.com/apache/kvrocks/actions/runs/6744677291/job/18335331806?pr=1871#step:12:81

### What did you expect to see?

CI passed

### What did you see instead?

CI failed

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by baobaomaomeng** [comment]
The logs for this run have expired and are no longer available.

**Comment by git-hulk** [comment]
@baobaomaomeng This should be fixed in #2347
