### ISSUE TITLE
redis.log not flush in docker on mac OrbStack

### ISSUE THREAD

**Issue by 3tieto** [apache/kvrocks#1883]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

https://lusun.com/v/5tn1fBHzmDO

> EVAL 'redis.log(redis.LOG_WARNING, "test")' 0

I recorded the videos, all in docker, and the first redis shown was output in real time. Then I turned off redis and used kvrocks. I can see that it needs to cache more than a dozen items before outputting them at once.

我录了下视频，都是docker，第一个展示的redis，是实时输出的。然后我关了redis，用kvrocks，可以看到要缓存十几条才一次输出

**Comment by git-hulk** [comment]
@3tieto Thank you!

**Comment by git-hulk** [comment]
I cannot reproduce it on my side. To see if other folks have any clues.

**Comment by i18nsite** [comment]
<img width="842" alt="image" src="https://github.com/apache/kvrocks/assets/145643935/06c278bb-a7e0-4ff5-929a-21e114984887">
如上图，加上FLAGS_logbuflevel = -1;   可以只延时一个输出了（我也不知道为什么还是要延时一个，也就是
stdout会实时输出， LOG(WARNING)要打印下一个的时候会输出上一个
）
<img width="1728" alt="image" src="https://github.com/apache/kvrocks/assets/145643935/96308c45-c1cf-4e22-afb9-1e616190809a">
