### ISSUE TITLE
add support for allow-cross-slot-keys for lua function

### ISSUE THREAD

**Issue by 3tieto** [apache/kvrocks#1884]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

lua function can read/write cross slot keys 

### Solution

https://developer.redis.com/create/redis-functions/
like redis
![image](https://github.com/apache/kvrocks/assets/147470591/6f1680ef-a73d-4998-88ca-be987b9a3caa)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PokIsemaine** [comment]
Hi @git-hulk @3tieto, I discovered this while creating a new https://github.com/apache/kvrocks/issues/2414. I'd like to know the status of this issue, if it's still unresolved and no one is responsible, maybe I can give it a try.

**Comment by git-hulk** [comment]
@PokIsemaine Thanks for your interest and it's good to go ahead. But be careful that this flag only takes effect in cluster mode and script's generated keys, for the predeclared keys should also forbid crossing slots if my memory serves.
