### ISSUE TITLE
The Sonar linter is too strict for test code.

### ISSUE THREAD

**Issue by jihuayu** [apache/kvrocks#1889]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

I noticed that many PRs fail the Sonar linter due to extensive code repetition in the TEST files. In such cases, the reviewer is required to manually inspect the results from Sonar. I believe that the Sonar linter should not be applied to test files. Moreover, the red cross on the commit message is not beautiful.

### Solution

In my opinion, it is unnecessary for the Sonar linter to take effect on test files.
Or, we could consider add additional Sonar linter rules for the test folder.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Seems the previous exclusion rules didn't take effect and now changed, please have a try again.

**Comment by jihuayu** [comment]
I think it would be beneficial to exempt test files from these duplicating check rules as well.
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=1881&id=apache_kvrocks&open=AYupwdoAZ8kRMyTUsysu

**Comment by git-hulk** [comment]
Yes, we exactly expected to exclude all test files. Seems the rules work well now, refer: https://sonarcloud.io/component_measures?metric=new_duplicated_lines&view=list&pullRequest=1881&id=apache_kvrocks

**Comment by PragmaTwice** [comment]
> I think it would be beneficial to exempt test files from these duplicating check rules as well. https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=1881&id=apache_kvrocks&open=AYupwdoAZ8kRMyTUsysu

You can check the latest report, which doesn't include these test files.

**Comment by jihuayu** [comment]
Can we also exclude Code Smells, in addition to Duplicated Lines? 

[![image](https://github.com/apache/kvrocks/assets/32858525/358d1f78-e7a3-42c9-91c7-9ceba827572e)](https://sonarcloud.io/component_measures?metric=new_technical_debt&view=list&pullRequest=1881&id=apache_kvrocks)
(You can navigate by clicking on the image)

**Comment by PragmaTwice** [comment]
> Can we also exclude Code Smells, in addition to Duplicated Lines?

I believe we still need to maintain some level of code quality, even in our test code.

**Comment by jihuayu** [comment]
> I believe we still need to maintain some level of code quality, even in our test code.

Do we need to fix code smells in the history code?

**Comment by julic20s** [comment]
Code smells is analysed in C++20(There are many C++ 20 features, such as using enum), but CMAKE_CXX_STANDARD is set to 17. Can Sonar linter change the cpp standard for checking?

**Comment by git-hulk** [comment]
@julic20s We weren't aware of this, I have changed it to C++17 now.
