### ISSUE TITLE
Quickstart "Error: Server closed the connection" for any command

### ISSUE THREAD

**Issue by theronic** [apache/kvrocks#1905]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

kvrocks version 2.6.0 (commit c0451df0)

macOS Ventura 13.4 on Apple M2 Pro Macbook Pro 14-inch 2023
Kvrocks: 

### Minimal reproduce step

As per [the docs](https://kvrocks.apache.org/blog/go-redis-kvrocks-opentelemetry/#getting-started-with-kvrocks):

    docker run -it -p 6666:6666 apache/kvrocks

In a separate terminal:

    redis-cli -p 6666
    > GET foo

### What did you expect to see?

Return nil or key value.

### What did you see instead?

On docker terminal:

```
I20231123 11:59:40.362723     1 main.cc:334] kvrocks version 2.6.0 (commit c0451df0)
I20231123 11:59:40.410612     1 storage.cc:332] [storage] Success to load the data from disk: 16 ms
I20231123 11:59:40.413663     1 worker.cc:72] [worker] Listening on: 127.0.0.1:6666
I20231123 11:59:40.414007     1 worker.cc:72] [worker] Listening on: 127.0.0.1:6666
I20231123 11:59:40.414085     1 worker.cc:72] [worker] Listening on: 127.0.0.1:6666
I20231123 11:59:40.414157     1 worker.cc:72] [worker] Listening on: 127.0.0.1:6666
I20231123 11:59:40.414258     1 worker.cc:72] [worker] Listening on: 127.0.0.1:6666
I20231123 11:59:40.414347     1 worker.cc:72] [worker] Listening on: 127.0.0.1:6666
I20231123 11:59:40.414443     1 worker.cc:72] [worker] Listening on: 127.0.0.1:6666
I20231123 11:59:40.414533     1 worker.cc:72] [worker] Listening on: 127.0.0.1:6666
I20231123 11:59:40.414712     1 worker.cc:515] [worker] Thread #281473666143544 started
I20231123 11:59:40.414757     1 worker.cc:515] [worker] Thread #281473654420792 started
I20231123 11:59:40.414800     1 worker.cc:515] [worker] Thread #281473654244664 started
I20231123 11:59:40.414839     1 worker.cc:515] [worker] Thread #281473654068536 started
I20231123 11:59:40.414875     1 worker.cc:515] [worker] Thread #281473653892408 started
I20231123 11:59:40.414916     1 worker.cc:515] [worker] Thread #281473653716280 started
I20231123 11:59:40.414952     1 worker.cc:515] [worker] Thread #281473632924984 started
I20231123 11:59:40.414999     1 worker.cc:515] [worker] Thread #281473632748856 started
I20231123 11:59:40.415161     1 server.cc:209] [server] Ready to accept connections
```

In redis-cli terminal:

```
Error: Server closed the connection
not connected>
```

### Anything Else?

Maybe I need to do some auth first, but the Quickstart guide does not specify this.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @theronic, thanks for your report. 

It's a fixed bug in Docker image configuration file, you can workaround by overwriting the bind address:

```shell
docker run -it -p 6666:6666 apache/kvrocks:2.6.0 --bind 0.0.0.0
```

refer: https://github.com/apache/kvrocks/issues/1851

**Comment by theronic** [comment]
Thanks, that works! I saw a different error though than is described in that issue, so that issue did not show up in my search. Closing.

Please update the docs :) If someone tries the Quickstart for the first-time and it doesn't work, immediately you think "oh oh - is this maintained?" which reduces chance of adoption in risk-averse companies.

**Comment by git-hulk** [comment]
> Please update the docs :) If someone tries the Quickstart for the first-time and it doesn't work, immediately you think "oh oh - is this maintained?" which reduces chance of adoption in risk-averse companies.

Sure, thanks for your kind suggestions.
