### ISSUE TITLE
output for 'level0_file_limit_stop' from ino is empty

### ISSUE THREAD

**Issue by bbqccx** [apache/kvrocks#1913]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

from 2.4 to 2.6

### Minimal reproduce step

info command

### What did you expect to see?

level0_file_limit_slowdown[default]:0
level0_file_limit_stop[default]:0
pending_compaction_bytes_slowdown[default]:0
pending_compaction_bytes_stop[default]:0
memtable_count_limit_slowdown[default]:0
memtable_count_limit_stop[default]:0

### What did you see instead?

level0_file_limit_slowdown[default]:
level0_file_limit_stop[default]:
pending_compaction_bytes_slowdown[default]:
pending_compaction_bytes_stop[default]:
memtable_count_limit_slowdown[default]:
memtable_count_limit_stop[default]:

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@bbqccx Thanks for your feedback, will fix this in next release.
