### ISSUE TITLE
Got (error) ERR MOVED when use redis-cli -c

### ISSUE THREAD

**Issue by jiangyunpeng** [apache/kvrocks#1922]
### Version

Redis-cli version: 6.2.5
Kvrocks version: 2.6.0

### Minimal reproduce step

Run follow command:

```
redis-cli -h 172.16.49.83 -p 7383 -c

set test abc
```

### What did you expect to see?

ok

### What did you see instead?

(error) ERR MOVED 6918 172.16.49.96:7384

**Comment by git-hulk** [comment]
@jiangyunpeng Thanks for your report, will take a look later.
