### ISSUE TITLE
Set command supports NX and GET options used together

### ISSUE THREAD

**Issue by rawvoid** [apache/kvrocks#1925]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

New features in Redis 7.0.0.

## History
- Starting with Redis version 2.6.12: Added the EX, PX, NX and XX options.
- Starting with Redis version 6.0.0: Added the KEEPTTL option.
- Starting with Redis version 6.2.0: Added the GET, EXAT and PXAT option.
- Starting with Redis version 7.0.0: Allowed the NX and GET options to be used together.

redis docs: https://redis.io/commands/set/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @tarvfx, thanks for your proposal.

From the Kvrocks side, what we need to be supported in the SET command are:

- KEEPTTL option(EX, PX, NX and XX options are supported now)
- Allowed to use the GET option together with EXAT/PXAT/NX

Did I miss anything?

**Comment by rawvoid** [comment]
Hi, @git-hulk 

Thanks, you filled in what I missed.

**Comment by jihuayu** [comment]
Adding the `KEEPTTL` and `GET` option to the set command is difficulty in the current implementation.
I will change the [`types/redis_string#Set`](https://github.com/jihuayu/incubator-kvrocks/blob/358cc4101651cfd19f558f9e46ef377c36b70ba6/src/types/redis_string.h#L45) function impl, Make it compatible with the new format of the `Set` command. And make [`SetEX`, `SetNX`, `SetXX`](https://github.com/jihuayu/incubator-kvrocks/blob/358cc4101651cfd19f558f9e46ef377c36b70ba6/src/types/redis_string.h#L46-L48) call the new `Set` function

**Comment by git-hulk** [comment]
@jihuayu Thank you!
