### ISSUE TITLE
Add version information for each command to the Supported Commands page in website

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1929]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

https://kvrocks.apache.org/docs/supported-commands

We'd better to add which version each command started to be supported, e.g.

|Command|Since Version|
|-|-|
|FCALL|2.7.0|

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
This may not be a good first issue but actually the contributor should know detail about the command impl history :D

**Comment by jihuayu** [comment]
Contributors can write a string matching program to check if each command exists in a specific version of the source code. 
So I think the contributor don't need to know detail about the command impl history

**Comment by kay011** [comment]
Hello, can you assign this issue to me?

**Comment by git-hulk** [comment]
@kay011 Thank you! As @jihuayu mentioned, maybe a quick way is to write a program to detect the support commands in each version.

**Comment by kay011** [comment]
@git-hulk Yeah！I plan to check the commands supported by each version through Python regular expressions. I will submit this script file and the final markdown file. This should be quick. Just paste the final results on the final docs.
