### ISSUE TITLE
Add support of the command COPY

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1945]
Refer to https://redis.io/commands/copy/

**Comment by Qiaolin-Yu** [comment]
I want to try. Can you assign this to me?

**Comment by PragmaTwice** [comment]
Sure! Assigned.

**Comment by Qiaolin-Yu** [comment]
May I know where I should write my unit tests?

**Comment by git-hulk** [comment]
@Qiaolin-Yu It's good to add Go tests only.

**Comment by Qiaolin-Yu** [comment]
By the way, for the optional part ```[DB destination-db]```, what should I do to write the KV to the ```destination-db```? Should I use ```RedisWriter::selectDB``` to implement?

**Comment by MaheshMadushan** [comment]
Hi @Qiaolin-Yu , according to my observation KVROCKS doesn't have DB instead you can use [namespace](https://kvrocks.apache.org/docs/namespace/) concept. Please verify with @git-hulk and @PragmaTwice

**Comment by git-hulk** [comment]
@MaheshMadushan You're right. The RENAME command also has similar issue, so we can use the namespace in those commands.

**Comment by jihuayu** [comment]
> @MaheshMadushan You're right. The RENAME command also has similar issue, so we can use the namespace in those commands.

@git-hulk Maybe not the RENAME command, but the MOVE command

**Comment by git-hulk** [comment]
@jihuayu Sorry for the wrong information. Yes, that's MOVE command instead of RENAME.

**Comment by Chiro11** [comment]
> By the way, for the optional part `[DB destination-db]`, what should I do to write the KV to the `destination-db`? Should I use `RedisWriter::selectDB` to implement?

@Qiaolin-Yu Hi, are you still working on this issue?

**Comment by Chiro11** [comment]
@git-hulk I think you can assign it to me now 'cause he hasn't responded for two months. This cmd is similar to `MOVE` and `RENAME`, suitable for me.

**Comment by git-hulk** [comment]
@Chiro11 Thank you!

**Comment by Chiro11** [comment]
@git-hulk To adapt to kvrocks, it may need to make minor modifications.
redis ver: `COPY source destination [DB destination-db] [REPLACE]`
I think we can replace 'DB' with 'NS'/'NAMESPACE'/'TO', or keep it, and replace destination-db to token.
What do you think?

**Comment by git-hulk** [comment]
@Chiro11 Perhaps we can support the [DB](DB must be 0) first and copy between namespaces should be implemented as COPYX.
