### ISSUE TITLE
Add support of the command DUMP

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1946]
Refer to https://redis.io/commands/dump/

**Comment by AntiTopQuark** [comment]
I noticed that this ISSUE hasn't been assigned to anyone for resolution, but it was mentioned in another issue #1949  that it should be done. 
@maochongxin Have you started working on it?

**Comment by maochongxin** [comment]
> I noticed that this ISSUE hasn't been assigned to anyone for resolution, but it was mentioned in another issue #1949  that it should be done. 
> 
> @maochongxin Have you started working on it?

You can do it, I may not have time to do this, thanks

**Comment by AntiTopQuark** [comment]
> > I noticed that this ISSUE hasn't been assigned to anyone for resolution, but it was mentioned in another issue #1949  that it should be done.
> > @maochongxin Have you started working on it?
> 
> You can do it, I may not have time to do this, thanks

Thanks

**Comment by AntiTopQuark** [comment]
@PragmaTwice 
Can you please assign this issue to me? 
Also, I've noticed that the DUMP command is closely related to the RESTORE command. 
Perhaps I can create a new issue for RESTORE and implement both commands simultaneously?

https://redis.io/commands/restore/

**Comment by git-hulk** [comment]
@AntiTopQuark Assigned. Thanks for your interest.

@maochongxin Thanks for your reply and efforts.

**Comment by PragmaTwice** [comment]
> Also, I've noticed that the DUMP command is closely related to the RESTORE command.
Perhaps I can create a new issue for RESTORE and implement both commands simultaneously?

RESTORE is already supported in https://github.com/apache/kvrocks/pull/1684.

**Comment by Chiro11** [comment]
@AntiTopQuark Are you still working on it?

**Comment by AntiTopQuark** [comment]
> @AntiTopQuark Are you still working on it?

I sincerely apologize for the prolonged delay. I am still working on this task and will do my best to complete it within the next three days. My apologies once again.

**Comment by jihuayu** [comment]
@AntiTopQuark Thank you for your efforts. We look forward to your PR.
