### ISSUE TITLE
Add support of the command MOVE

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1950]
Refer to https://redis.io/commands/move/

**Comment by jihuayu** [comment]
Kvrocks don't have DB, we have [namespace](https://kvrocks.apache.org/docs/namespace) instead.
So should we use namespace token in this command?
```shell
move key namespace_token
```

**Comment by PragmaTwice** [comment]
> Kvrocks don't have DB, we have [namespace](https://kvrocks.apache.org/docs/namespace) instead. So should we use namespace token in this command?
> 
> ```shell
> move key namespace_token
> ```

Looks good to me. cc @git-hulk

**Comment by git-hulk** [comment]
> > Kvrocks don't have DB, we have [namespace](https://kvrocks.apache.org/docs/namespace) instead. So should we use namespace token in this command?
> > ```shell
> > move key namespace_token
> > ```
> 
> Looks good to me. cc @git-hulk

Good to me +1

**Comment by mapleFU** [comment]
proposal is ok to me

**Comment by kay011** [comment]
This command was implemented by @enjoy-binbin  in #1723  but now it is a dummy command. Are we sure  to change the actual operation of the command which is different from Redis?

**Comment by enjoy-binbin** [comment]
I think it’s better to keep the redis style `MOVE key db`.

If we specifially need such a feature, we should add a new command, or at least do it in a way that is compatible with redis style.

**Comment by jihuayu** [comment]
@enjoy-binbin 
Add a new command looks good to me.

I provide a compatible solution:
When command args size is 3, `MOVE key db` , we treat it a dummy command.
When command args size is 4, `MOVE key ns_name ns_token` ,we move it to new namespace.

**Comment by haanhvu** [comment]
> @enjoy-binbin Add a new command looks good to me.
> 
> I provide a compatible solution: When command args size is 3, `MOVE key db` , we treat it a dummy command. When command args size is 4, `MOVE key ns_name ns_token` ,we move it to new namespace.

This has not been implemented right? I'll work on this.

**Comment by jihuayu** [comment]
> > @enjoy-binbin Add a new command looks good to me.
> > I provide a compatible solution: When command args size is 3, `MOVE key db` , we treat it a dummy command. When command args size is 4, `MOVE key ns_name ns_token` ,we move it to new namespace.
> 
> This has not been implemented right? I'll work on this.

No. But let's check with @git-hulk @PragmaTwice to make sure this is the ok behavior.

**Comment by git-hulk** [comment]
I'm fine with @enjoy-binbin solution. BTW, we must forbid using this command if the cluster mode is enabled.

**Comment by jihuayu** [comment]
Hi @haanhvu, according to @git-hulk's suggestion, we can use @enjoy-binbin's solution.
You can add a new command. 
Be bold in doing it, and feel free to continue raising questions here if any.

> I think it’s better to keep the redis style MOVE key db.
If we specifially need such a feature, we should add a new command, or at least do it in a way that is compatible with redis style.

**Comment by Chiro11** [comment]
> > @enjoy-binbin Add a new command looks good to me.
> > I provide a compatible solution: When command args size is 3, `MOVE key db` , we treat it a dummy command. When command args size is 4, `MOVE key ns_name ns_token` ,we move it to new namespace.
> 
> This has not been implemented right? I'll work on this.

Are you still working on this?

**Comment by jihuayu** [comment]
Hi @Chiro11 
It seems like nobody has work now. 
If you want to do it, you can send a PR directly.
