### ISSUE TITLE
Add support of the command RENAMENX

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1951]
Refer to https://redis.io/commands/renamenx/

**Comment by jihuayu** [comment]
We also don't have `RENAME` command. It can be directly added to this issue.

Refer: https://github.com/apache/kvrocks-website/blob/main/docs/supported-commands.md?plain=1#L153

**Comment by jihuayu** [comment]
I will do it.

**Comment by PragmaTwice** [comment]
Great! Assigned.

**Comment by jihuayu** [comment]
@PragmaTwice 
Hi, I found that there are the following limitations for the `RENAME` command in the Redis doc.
> In Cluster mode, both key and newkey must be in the same hash slot


Are there any examples of how to check if kvrocks is running in cluster mode and how to get the slot ID from keyname?

Refer: https://redis.io/commands/rename/#:~:text=In%20Cluster%20mode%2C%20both%20key%20and%20newkey%20must%20be%20in%20the%20same%20hash%20slot%2C
