### ISSUE TITLE
Add support of the command SORT and SORT_RO

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1952]
Refer to https://redis.io/commands/sort/ and https://redis.io/commands/sort_ro/

**Comment by HolyLow** [comment]
Hello, I am interested in this issue.

**Comment by PragmaTwice** [comment]
Great! Assigned.

**Comment by PokIsemaine** [comment]
Hello @HolyLow @PragmaTwice 
Is there any progress on this issue? If no one is working on it at the moment, I'm willing to try this question.

**Comment by git-hulk** [comment]
@PokIsemaine Thanks for your interest. I think it's fine to reassign since it's inactive for a long time.

**Comment by HolyLow** [comment]
@PokIsemaine My progress is limited (just annotations), so feel free to take this over.
@git-hulk Sorry for the huge delay, I could spare some time on another issue https://github.com/apache/kvrocks/issues/1372 recently, so please reserve that one for me if it's ok.

**Comment by git-hulk** [comment]
@HolyLow Thanks for your feedback.

> @git-hulk Sorry for the huge delay, I could spare some time on another issue https://github.com/apache/kvrocks/issues/1372 recently, so please reserve that one for me if it's ok.

Absolutely yes. No sorry and very appreciative of your efforts and contributions.
