### ISSUE TITLE
Add support of the command SMISMEMBER

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1959]

**Comment by jihuayu** [comment]
Refer: https://redis.io/commands/smismember/

**Comment by jyizheng** [comment]
Please assign it to me

**Comment by PragmaTwice** [comment]
> Please assign it to me

Assigned. Go ahead!

**Comment by sheharyaar** [comment]
Hi @PragmaTwice , it seems there has not been any update since December to this issue, can I please pick this up ?

**Comment by sheharyaar** [comment]
I can see in the source, that this is already implemented. This can be closed.

**Comment by git-hulk** [comment]
@sheharyaar Thanks for your reminder.

**Comment by jihuayu** [comment]
@jyizheng Thank you！
Do you want to have try https://github.com/apache/kvrocks/issues/1212 ？
