### ISSUE TITLE
Using `GET` to get json type key will not return error.

### ISSUE THREAD

**Issue by jihuayu** [apache/kvrocks#1969]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable 

### Minimal reproduce step

Using `GET` to get json type key will not return error.
I writed below test case.

```go
t.Run("GET JSON type key", func(t *testing.T) {
	require.NoError(t, rdb.Do(ctx, "JSON.SET", "a", "$", ` {"x":1,"y":2} `).Err())
	require.EqualValues(t, "\x00{\"x\":1,\"y\":2}", rdb.Get(ctx, "a").Val())
})
```

### What did you expect to see?

test failed

### What did you see instead?

test Passed

### Anything Else?

Maybe is this line problem.https://github.com/apache/kvrocks/blob/unstable/src/types/redis_string.cc#L86
```C++
if (metadata.Type() != kRedisString && metadata.size > 0) {
    return rocksdb::Status::InvalidArgument(kErrMsgWrongType);
  }
```
Why do we need to check `metadata.size > 0`?

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@jihuayu Good catch!

> Why do we need to check metadata.size > 0?

For example, we need to regard it as a non-existing key if all subkeys are deleted in a list(same as the hash/set/zset). But some types allow the empty subkey list like stream/bloomfilter. Can refer: [storage/redis_db.cc#L62](https://github.com/apache/kvrocks/blob/unstable/src/storage/redis_db.cc#L62)

The better way is to use `GetMetadata` to replace the decode function in `redis_string`.

**Comment by jihuayu** [comment]
Fixed after https://github.com/apache/kvrocks/pull/1971
