### ISSUE TITLE
Add kvrocks2redis test case runnig to CI workflow

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1976]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Now we have some test cases for kvrocks2redis, but they cannot be triggered by CI workflow yet.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jihuayu** [comment]
Assign to @Zakelly via #2149 
Can you replay this issue? I only can assign it to participants

**Comment by Zakelly** [comment]
> Assign to @Zakelly via #2149 Can you replay this issue? I only can assign it to participants

Sure, thanks
