### ISSUE TITLE
`BITCOUNT` return wrong when args > 4

### ISSUE THREAD

**Issue by jihuayu** [apache/kvrocks#1978]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

```shell
127.0.0.1:6666> SET mykey "foobar"
OK
127.0.0.1:6666> BITCOUNT mykey 5 30
(integer) 4
127.0.0.1:6666> BITCOUNT mykey 5 30 111
(integer) 26
```

### What did you expect to see?

`BITCOUNT mykey 5 30 111` return 4

### What did you see instead?

`BITCOUNT mykey 5 30 111` return ERROR

### Anything Else?

https://github.com/apache/kvrocks/blob/574d438b9acde7b45b0666564af4450c057aceea/src/commands/cmd_bit.cc#L94-L117

We need return ERROR when `args.size() > 4`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Below is how Redis works:

```
127.0.0.1:6379> SET mykey "foobar"
OK
127.0.0.1:6379>  BITCOUNT mykey 5 30
(integer) 4
127.0.0.1:6379>  BITCOUNT mykey 5 30 111
(error) ERR syntax error
```

@jihuayu would you like to fix it? Or I can take a look.

**Comment by jihuayu** [comment]
@tisonkun Go ahead. Thank you!
I will not fix it
