### ISSUE TITLE
Add support of the command ZRANDMEMBER

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#1985]
https://redis.io/commands/zrandmember/

**Comment by JxLi0921** [comment]
Hello! I have a question for this. I noticed that the current implementation of `SRANDMEMBER` always returns the first `count` members and it's not really random. Therefore, is it ok for the implementation of `ZRANDMEMBER` also just returns the first `count` members?

**Comment by PragmaTwice** [comment]
> Hello! I have a question for this. I noticed that the current implementation of `SRANDMEMBER` always returns the first `count` members and it's not really random. Therefore, is it ok for the implementation of `ZRANDMEMBER` also just returns the first `count` members?

You can follow the implementation of HRANDMEMBER, which is more reasonable.

**Comment by JxLi0921** [comment]
> > Hello! I have a question for this. I noticed that the current implementation of `SRANDMEMBER` always returns the first `count` members and it's not really random. Therefore, is it ok for the implementation of `ZRANDMEMBER` also just returns the first `count` members?
> 
> You can follow the implementation of HRANDMEMBER, which is more reasonable.

thanks! could you please assign this to me? btw, maybe it's `HRANDFIELD`, but not `HRANDMEMBER`

**Comment by PragmaTwice** [comment]
> thanks! could you please assign this to me? btw, maybe it's `HRANDFIELD`, but not `HRANDMEMBER`

Yeah you are right! Assigned.
