### ISSUE TITLE
Implement the migrate iterator for iterating key values

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1989]
Currently, we need to iterate all keys in the database in different places like the cluster migration and kvrocks2redis, but don't have an iterator for this purpose. It's very error-prone to implement this in different places since Kvrocks may add a new column family in the future, and we must be careful to iterate all keys in all column families. This would be a burden for maintenance, So I think we could add an iterator to iterate all keys in all column families.

## Proposal

For the API, we could generally comply with the rocksdb's iterator API, but we allow to add some extra functions if needed.

```C++

class Iterator {
public:
    Iterator(Storage *storage, const rocksdb::ReadOptions &options, const int slot = -1);
    ~KeyIterator();

    bool Valid() const;
    void Next();

    rocksdb::WriteBatch *Batch() const;
    Slice Key() const;
    Slice Value() const;
    RedisType Type() const;
};

```

And when implementing this iterator, it will iterate the metadata column family first and check its type, if it's not a string, then it will iterate the corresponding column family to get subkeys. That said, if we have a key `foo` with type `hash`, then the iterator will iterate `foo` and `foo:field1`, `foo:field2`, and so on.

This solution can bring those benefits:

- The codes look more intutive
- Can reuse this iterator if we want to iterate keys only

**Comment by git-hulk** [comment]
@caipengbo Would you mind taking a look while you're free.

**Comment by caipengbo** [comment]
> Would you mind taking a look while you're free. 

Good job, LGTM!
