### ISSUE TITLE
Add BIT option support for BITCOUNT command

### ISSUE THREAD

**Issue by jihuayu** [apache/kvrocks#2006]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

I found that the `BITCOUNT` command doesn't have the `BIT` option supported. [Source](https://github.com/jihuayu/incubator-kvrocks/blob/588650f51c434b161c8a8de65ea80871c7d2573e/src/commands/cmd_bit.cc#L124)

### Solution

Add BIT option support for `BITCOUNT` command.

relate issues: https://github.com/apache/kvrocks/issues/1212

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jihuayu** [comment]
We can trace it by https://github.com/apache/kvrocks/issues/1942.

**Comment by git-hulk** [comment]
@jihuayu Added it, thank you!

**Comment by kay011** [comment]
Is anyone working on this? If not, you can assign it to me

**Comment by jihuayu** [comment]
@kay011 Assigned. Thank you!
There are some doc you may need:
- https://kvrocks.apache.org/community/data-structure-on-rocksdb#bitmap
- https://redis.io/commands/bitcount/
