### ISSUE TITLE
Implement WAL iterator for migrating by WAL logs

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#2007]

**Comment by caipengbo** [comment]
In https://github.com/apache/kvrocks/pull/2004, we implement the unified key-value iterators, I want to change data to provide a unified iterators. 

For incremental data, we need to call `rocksdb::WALIter` and then implement the `rocksdb::WriteBatch::Handler` interface. 

I want to provide an interface that behaves similarly to `engine::DBIterator`: 

https://github.com/apache/kvrocks/blob/c772109516a6698f8e74d50c1a43bb1c02a697c5/src/storage/iterator.h#L52-L81. 

It will wrap `rocksdb::WALIter` and can return different value types. It is possible to implement their processing logic depending on the concrete type.

HDYT @git-hulk

**Comment by git-hulk** [comment]
@caipengbo Sounds good to me.
