### ISSUE TITLE
Improve the implementation of SRANDMEMBER

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2014]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Currently it just returns the first N members, which is not actually random.

We can improve it just like the implementation of HRANDMEMBER.
 (Or if you have better ideas for random, feel free to implement them)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wsehjk** [comment]
hello could you please assign this to. Interested in this problem

**Comment by git-hulk** [comment]
@wsehjk assigned, thank you!

**Comment by wsehjk** [comment]
Thanks, I'm newbie to this project. Does this project have any community where developers can communicate?

**Comment by git-hulk** [comment]
Yes, you can join the WeChat group via the official account at the bottom of README if you're using WeChat. Or you can join the Slack channel which is also mentioned in README.

**Comment by wsehjk** [comment]
Hi, here is a question. If the number of member (k) is less than the **count** we want to select, under the context of **random**, does it ok to generate results less than k?

**Comment by mapleFU** [comment]
@wsehjk https://github.com/apache/kvrocks/pull/1565/files this is a example for our current impl

**Comment by wsehjk** [comment]
> @wsehjk https://github.com/apache/kvrocks/pull/1565/files this is a example for our current impl

thanks, i will take a look at this. And i'm gonna try **Reservoir Sampling**
