### ISSUE TITLE
Allow to use hyper clock cache to replace the LRU cache

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#2022]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

The hyperclock cache was introduced in rocksdb in 7.7.3 and it may bring performance benefits for the block/row cache while compared to the LRU cache. This idea is mentioned by @PragmaTwice.

### Solution

Allow to enable the hyper cache via the configuration.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JxLi0921** [comment]
hello! I have a question for this. Noticed that this issue has a `need benchmark` tag, is there a standard way to benchmark kvrocks? For example, does simlply running redis-benchmark on my computer is enough , or we need to do some other experiments on some platforms?

**Comment by git-hulk** [comment]
@JxLi0921 Your local environment is enough. What we want to know is if the hyper clock cache can bring performance benefits while compared to LRU. And the benchmark result is also not a blocking item for merging PR.

**Comment by mapleFU** [comment]
> Noticed that this issue has a need benchmark tag, is there a standard way to benchmark kvrocks?

Perhaps you can try ycsb in your local environment. This is a way we can follow: https://github.com/apache/kvrocks/pull/1424#issuecomment-1546521178

**Comment by JxLi0921** [comment]
@git-hulk @mapleFU Thanks for your answers, got it! Could you please assign this to me? I would like to give it a try.

**Comment by git-hulk** [comment]
@JxLi0921 assigned, thank you!

**Comment by LiuYuHui** [comment]
It seems like that this issue had been solved?

**Comment by git-hulk** [comment]
@LiuYuHui Sorry for forgetting to close this issue, it's done in #2031.
