### ISSUE TITLE
Add RESP3 verbatim string type

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#2036]

**Comment by wsehjk** [comment]
hi may i apply to solve this issue?

**Comment by git-hulk** [comment]
@wsehjk sure, assigned. Thank you!

**Comment by wsehjk** [comment]
Thank you for this opportunity  to learn serialization protocols. I will solve this ASAP

**Comment by git-hulk** [comment]
@wsehjk Are you still working on this issue?

**Comment by wsehjk** [comment]
yes, still work on this. This week I can make some progress

**Comment by git-hulk** [comment]
ok, thank you!
