### ISSUE TITLE
Using the `debug protocol int` command will report an error that the int type is not supported.

### ISSUE THREAD

**Issue by AntiTopQuark** [apache/kvrocks#2045]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable(master)

### Minimal reproduce step

```
127.0.0.1:6666> debug protocol int
```

### What did you expect to see?

```
(error) Wrong protocol type name. Please use one of the following: string|**integer**|array|set|bignum|true|false|null
```

### What did you see instead?

```
(error) Wrong protocol type name. Please use one of the following: string|int|array|set|bignum|true|false|null
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@AntiTopQuark Thank you!
