### ISSUE TITLE
kvrocks' BITCOUNT result is different from Redis

### ISSUE THREAD

**Issue by kay011** [apache/kvrocks#2068]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

1. setbit mykey1 0 1
2. bitcount mykey1 -1 -1

### What did you expect to see?

redis result: 1
kvrocks result: 1

### What did you see instead?

redis result: 1
kvrocks result: 0

### Anything Else?

In `redis_bitmap.cc` 226~229 line. The processing of logical strings here is inconsistent. I am confused whether there are special considerations or a BUG here?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
```c++
  if (start < 0 || stop <= 0 || start >= stop) return rocksdb::Status::OK();
```

The point maybe the condition above...

**Comment by kay011** [comment]
```
if (start < 0) start += static_cast<int64_t>(metadata.size) + 1;
if (stop < 0) stop += static_cast<int64_t>(metadata.size) + 1;
if (stop > static_cast<int64_t>(metadata.size)) stop = static_cast<int64_t>(metadata.size);
if (start < 0 || stop <= 0 || start >= stop) return rocksdb::Status::OK();
```

I think the code is confused, what is the` metadata.size `means？ the used bytes of bitmap，why should +1 ？

**Comment by mapleFU** [comment]
> what is themetadata.sizemeans

Means the "extended" bit size. e.g.:

```
set bit 100 1
--> length = 100
set bit 99 1
--> length = 99
set bit 101 1
--> length = 101
```

> the used bytes of bitmap，why should +1 

You can edit it as you'd like 🤔

**Comment by kay011** [comment]
@mapleFU I do a test, it it not work like you said: 
set bit 100 1
--> length = 100
but: length = 13 😄

**Comment by mapleFU** [comment]
Yeah, it's bytesize, should contain a `mod 8`:

```
  uint32_t byte_index = (offset / 8) % kBitmapSegmentBytes;
  uint64_t used_size = index + byte_index + 1;
  uint64_t bitmap_size = std::max(used_size, metadata.size);
```

**Comment by jihuayu** [comment]
Maybe this is the same reason with https://github.com/apache/kvrocks/issues/1212#issuecomment-1366801588

**Comment by mapleFU** [comment]
@kay011 would you like fixing this? If not I'll do a quick fixing

**Comment by kay011** [comment]
> @kay011 would you like fixing this? If not I'll do a quick fixing

you can do it, I will merge your code in my other feature

**Comment by mapleFU** [comment]
I'm trying to fix it here: https://github.com/apache/kvrocks/pull/2069

**Comment by kay011** [comment]
@mapleFU BITPOS command may be have the same problem, please check~

**Comment by mapleFU** [comment]
Sigh, I've checked and also fixed that

**Comment by mapleFU** [comment]
closed by https://github.com/apache/kvrocks/pull/2069

**Comment by mapleFU** [comment]
https://github.com/apache/kvrocks/pull/2074

<del>Found BitmapString also has this problem 😅 Let me take time to fix it</del>

Oh, it's an expected behavior
