### ISSUE TITLE
RocksDB optimization

### ISSUE THREAD

**Issue by ShooterIT** [apache/kvrocks#209]
## Compression type
- Support multiple compression types

## Parameters
- enable enable_pipelined_write if having more CPUs
- use index_type: kTwoLevelIndexSearch to make index and filter blocks smaller
- enable pin_top_level_index_and_filter, pin_l0_filter_and_index_blocks_in_cache
- for cache_index_and_filter_blocks_with_high_priority, to avoid too high
- NewBloomFilterPolicy(bits_per_key, false) i.e. BloomFilterPolicy::kAutoBloom
- data_block_index_type: BlockBasedTableOptions::kDataBlockBinaryAndHash
- Set BlockBasedTableOptions::optimize_filters_for_memory to true, jemalloc_usable_size is safe if no bugs, redis adopts it
-  memtable_prefix_bloom_size_ratio and memtable_whole_key_filtering, to enable memtable filter.
- CompressionOptions::max_dict_bytes for lz4 and zstd

## Data partition  by ColumnFamily
- ~~One type one ColumnFamily~~

**Comment by dongdongwcpp** [comment]
`memtable_prefix_bloom_size_ratio` seems need a prefix_extractor, can it work for redis like system?

**Comment by ShooterIT** [comment]
@dongdongwcpp you mean we should set `prefix_extractor` if we want to enable `memtable_prefix_bloom_size_ratio`?
i think in redis system, there are many lookup reads, so i want to enable this feature, make sense? WDYT?
