### ISSUE TITLE
Create stream consumer group will make the xread command error

### ISSUE THREAD

**Issue by jihuayu** [apache/kvrocks#2109]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

```shell
XADD test * a a
XGROUP create test test 0
xread STREAMS test 0
```

### What did you expect to see?

```shell
1) 1) "test"
   2) 1) 1) "1708506496723-0"
         2) 1) "a"
            2) "a"
```

### What did you see instead?

(error) ERR Invalid argument: failed to decode stream entry value

### Anything Else?

I discovered this when developing the xreadgroup command.

The subkey of the consumer group overlapped with the subkey of the stream entry.
This causes the [range function](https://github.com/apache/kvrocks/blob/30f6bee42d4352715ce254a52c4403fe6b0ab5e7/src/types/redis_stream.cc#L686) to get the stream Entry with the group's subkey.

I think there is something wrong with the subkey design of the consumer & consumer group metadata.
https://github.com/apache/kvrocks/blob/30f6bee42d4352715ce254a52c4403fe6b0ab5e7/src/types/redis_stream.cc#L168-L176

I don't really understand why we puts the consumerGroupMetadataDelimiter at the end of the subkey. Shouldn't we put it at the start?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Yangsx-1** [comment]
Good catch! I'm still working on XREADGROUP and will finish it in a few days, and this bug may caused by no subkey identification in the original stream commands.  :(

**Comment by jihuayu** [comment]
@Yangsx-1 Thank you. I have fixed this bug, please review it.
