### ISSUE TITLE
"RDB LOAD" command fails

### ISSUE THREAD

**Issue by krizald** [apache/kvrocks#2118]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

**OS**: Debian GNU/Linux 11 (bullseye)
**KV Rocks**: 2.7.0 

### Minimal reproduce step

* Create a LIST (Key: ABC) in Redis 6.2
* Dump the RDB file
* RDB LOAD dump.rdb

### What did you expect to see?

RDB file should be loaded without error

### What did you see instead?

Load failed with error:

redis-cli throws error: (error) ERR reach the end of ziplist
KV Rocks log: E20240223 08:55:35.669234 1006372 rdb.cc:78] Unexpected EOF reading RDB file

### Anything Else?

I tried anther tool Redis-Shake to load the same RDB, with it's default setting. Firstly I got a similar error:
ERR [writer_127.0.0.1_7619] receive reply failed. cmd=[restore ABCD], error=[ERR reach the end of ziplist]
Then I follow this(https://github.com/tair-opensource/RedisShake/blob/0cf0af07411fb85dc9c08b78fea77c37880795a9/docs/src/zh/writer/redis_writer.md?plain=1#L28) to changed the redis-shake config to avoid using "restore" cmd. The RDP import is successful.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
The error seems not attached.

**Comment by krizald** [comment]
> The error seems not attached.

Sorry, I updated my post.

**Comment by git-hulk** [comment]
@krizald Thanks for your report. It will be great if you can upload you test rdb file as well.

**Comment by krizald** [comment]
> @krizald Thanks for your report. It will be great if you can upload you test rdb file as well.

@git-hulk here it is

[dump.zip](https://github.com/apache/kvrocks/files/14408108/dump.zip)

Dump file is generated with Redis 6.2.10

**Comment by git-hulk** [comment]
@krizald Thanks for your help. Will fix it soon.

**Comment by git-hulk** [comment]
Hi @krizald 

I have identified the bug in the quick list encoding, will fix it today, and release it in the next version(maybe 2.8.0).
