### ISSUE TITLE
set sync option to true for WriteOptions

### ISSUE THREAD

**Issue by photoszzt** [apache/kvrocks#2135]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

![image](https://github.com/apache/kvrocks/assets/1476795/7d4d1e62-346a-4874-862a-80e5ea1841df)
From the slack conversation, kvrocks currently doesn't set the WriteOptions's sync mode to true which might lose data upon crash. https://github.com/facebook/rocksdb/wiki/WAL-Performance 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Hi @photoszzt , thank you for your suggestion!

It is important to prevent data loss, but I wonder the performance impact of this option.

And should we enable sync mode by default, or we make it a configuration option (kvrocks.conf) for users?

**Comment by git-hulk** [comment]
Yes, this option might heavily affect the performance, so guess it will be better to make a configuration option for users.

**Comment by photoszzt** [comment]
![image](https://github.com/apache/kvrocks/assets/1476795/dde4626c-a4a0-45ba-8f1c-dc17c5023521)

@PragmaTwice There's an option in the conf file: rocksdb.write_options.sync. It's set to no right now. I assume it will set WriteOptions.sync=true when I change this config to yes. I'm going to see how much slower if this is set to yes.

**Comment by mapleFU** [comment]
I don't think we should change our default behavior here. But you can edit yourself's config

> I assume it will set WriteOptions.sync=true when I change this config to yes.

Yes.

**Comment by git-hulk** [comment]
@photoszzt I'm sorry for forgetting this configuration has been supported, you can achieve this by adding `rocksdb.write_options.sync yes` to your configuration file. cc @PragmaTwice @mapleFU 

Close this issue since it has been resolved, feel free to reopen it if you have any questions.
