### ISSUE TITLE
subkey column family name

### ISSUE THREAD

**Issue by xumingbo** [apache/kvrocks#2140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

2.7.0

### Minimal reproduce step

constexpr const char *kSubkeyColumnFamilyName = "default";

### What did you expect to see?

constexpr const char *kSubkeyColumnFamilyName = "subkey";

### What did you see instead?

constexpr const char *kSubkeyColumnFamilyName = "default";

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@xumingbo We expected to use the rocksdb `default` column family as the subkey column family, so it's an expected behavior NOT a bug.

**Comment by xumingbo** [comment]
If so, could you please comment on that line of code with "use the rocksdb default column family as the subkey column family" to have better code readability.
