### ISSUE TITLE
add options for set compress level

### ISSUE THREAD

**Issue by i18nsite** [apache/kvrocks#2143]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

https://github.com/facebook/rocksdb/wiki/Space-Tuning#compression-level
Default Zstandard compression level is 3 and it is also a default in RocksDB. Zstandard allows to set compression level from 1 to 19 and it trades compression speed and ratio (https://github.com/facebook/zstd). In one typical DB, we use level 6 and in general we use “compression_opts=-14:6:0”.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Beihao-Zhou** [comment]
Hii! Can you assign this to me? Thank you!! @i18n-now

**Comment by aleksraiden** [comment]
Important options, lot of thanks about implementation
