### ISSUE TITLE
kvrocks2redis test scripts fail

### ISSUE THREAD

**Issue by Zakelly** [apache/kvrocks#2149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

MacOSX 13.5
unstable commit id: 19d7bad87c0b147c96d94b79c1b1ed1e0d894e38

### Minimal reproduce step

1. Build
2. Start kvrocks via `./build/kvrocks -c kvrocks.conf`
3. Start redis-server
4. Start kvrocks2redis via `./build/kvrocks2redis -c utils/kvrocks2redis/kvrocks2redis.conf`
5. Install dependency:
    `pip install git+https://github.com/andymccurdy/redis-py.git@2.10.3`
6. Run test via `cd utils/kvrocks2redis/tests && python3 ./populate-kvrocks.py --password="" --flushdb=true`

### What did you expect to see?

All case passed I guess?

### What did you see instead?

```
FAIL ('set', 'foo', 1):'OK' != True
FAIL ('setex', 'foo_ex', 3600, 1):'OK' != True
******* Some case test fail *******
string
FAIL ('set', 'foo', 2):'OK' != True
FAIL ('set', 'foo2', 2):'OK' != True
FAIL ('setex', 'foo_ex', 7200, 2):'OK' != True
FAIL ('lset', 'lfoo', 0, 'a'):'OK' != 1
EXCP unsupported operand type(s) for |: 'str' and 'bool'
******* Some case test fail *******
string
list
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Zakelly** [comment]
I guess the return value `OK` should also be treat as passed.

**Comment by jihuayu** [comment]
Thank you! @Zakelly 
It seems like some commands return value has some wrong.
https://github.com/apache/kvrocks/blob/574d438b9acde7b45b0666564af4450c057aceea/utils/kvrocks2redis/tests/populate-kvrocks.py#L61 
It may "OK" not True.

These codes were introduced in #1963.

Is it possible that the issue is due to different versions of Python Redis client?

**Comment by Zakelly** [comment]
@jihuayu 
My redis-cli and redis-server version are both `7.2.4`, when I run `setex` command in redis-cli, it returns:
```
127.0.0.1:6379> setex foo_ex 7200 2
OK
```
Redis python module version:
```
pip3 show redis   
Name: redis
Version: 2.10.3
Summary: Python client for Redis key-value store
Home-page: http://github.com/andymccurdy/redis-py
Author: Andy McCurdy
Author-email: sedrik@gmail.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Requires: 
Required-by: 
```

**Comment by jihuayu** [comment]
@Zakelly 
Thank you for discovering this issue. The test for kvrocks2redis has not been run in CI, which may be a hidden bug.

After the fix it, do you want to add this test to our CI? refer: https://github.com/apache/kvrocks/issues/1976

**Comment by Zakelly** [comment]
@jihuayu Yes I'd like to. Please assign to me, Thanks

**Comment by Zakelly** [comment]
It seems the README is providing the wrong `redis-py` version. When I changed to 5.0.3, the problem solved.
