### ISSUE TITLE
PubSub with Lettuce not working as expected

### ISSUE THREAD

**Issue by asad-awadia** [apache/kvrocks#2156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

KVRocks version 2.8.0 and nightly

### Minimal reproduce step

Clone : https://gitlab.com/asad-awadia/kotlin-server-app - if a project/environment is required

```
fun main() {
  val redisClient = RedisClient.create(RedisURI.builder().withHost("0.0.0.0").withPort(6666).build())
  val pubSub = redisClient.connectPubSub()
  pubSub.addListener { println("received push message ${it.content}") }
  pubSub.sync().subscribe("channel")
  redisClient.connect().sync().publish("channel", "foo")
  Thread.sleep(5000)
}
```

### What did you expect to see?

The message callback listener is invoked with the message [foo] sent in the publish call

### What did you see instead?

No message is received - the listener callback is not invoked

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@asad-awadia Thank you!

**Comment by asad-awadia** [comment]
are you referring to the publish call? or the subscribe call?

https://github.com/redis/redis/blob/7.2.2/src/pubsub.c#L147 - seems to do the same

**Comment by git-hulk** [comment]
Thanks for your correction. It seems related to RESP3 PUSH which is not supported in Kvrocks yet, I will investigate it soon when I get time.

@asad-awadia I think you can use RESP2 instead of RESP3 for now if you have to depend on PubSub.

**Comment by asad-awadia** [comment]
push doesnt work with resp2 either - just tried it on 2.8.0

**Comment by git-hulk** [comment]
@asad-awadia Yes, Kvrocks doesn't support the PUSH yet, but PubSub works in RESP2 without depending on the PUSH protocol.
