### ISSUE TITLE
Add support of the command READONLY & READWRITE

### ISSUE THREAD

**Issue by singular-seal** [apache/kvrocks#2166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

1. redis cluster utilize [readonly](https://redis.io/commands/readonly/) to support reading from slave node
2. go-redis will send a 'readonly' command to server when 'ReadOnly' option is true during initialisation which would incur an error response from kvrocks 'ERR unknown command readonly' because kvrocks doesn't support command 'readonly'
3. this is important because without reading from slave a shard  is not readable during failover which is not acceptable for some businesses

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@singular-seal Thanks for your feedback.

**Comment by LiuYuHui** [comment]
Hi @git-hulk, I want to help implement this feature, could you give me some suggestions on where to start? thanks a lot!

**Comment by git-hulk** [comment]
@LiuYuHui Thank you! Go ahead.

**Comment by jihuayu** [comment]
Hi @LiuYuHui.
You can add a flag in `redis::Connection` to store if this connection enables read queries.
You can add new commands in [cmd_server.cc](https://github.com/apache/kvrocks/blob/unstable/src/commands/cmd_server.cc)

The following code may be the code you need to modify.
- https://github.com/apache/kvrocks/blob/unstable/src/cluster/cluster.cc#L804-L807

If you have any other questions, feel free to ask me.
