### ISSUE TITLE
Add support of the command ASKING

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#2168]

**Comment by MaheshMadushan** [comment]
Hello. Shall i try this if this is available?

**Comment by git-hulk** [comment]
@MaheshMadushan assigned, thank you 😊

**Comment by git-hulk** [comment]
@MaheshMadushan Are you working on this issue? If not, I will take over this task.

**Comment by MaheshMadushan** [comment]
> @MaheshMadushan Are you working on this issue? If not, I will take over this task.

I may not be able to work on this. please continue.

**Comment by git-hulk** [comment]
@MaheshMadushan Thanks for your feedback.

**Comment by jjz921024** [comment]
@git-hulk Hi, Shall i try this if this is available?

**Comment by git-hulk** [comment]
@jjz921024 Sure, thank you!
