### ISSUE TITLE
JSON.SET cant add a new field

### ISSUE THREAD

**Issue by superikw** [apache/kvrocks#2176]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

2.7.0 & 2.8.0

### Minimal reproduce step

redis> JSON.SET doc $ '{"a":2}'
OK
redis> JSON.SET doc $.b '8'
OK
redis> JSON.GET doc $
"[{\"a\":2}]"

### What did you expect to see?

"[{\"a\":2,\"b\":8}]" 

### What did you see instead?

"[{\"a\":2}]"

### Anything Else?

Example comes from https://redis.io/commands/json.set/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Yeah it is an known issue. Currently Kvrocks doesn't support set value for a nonexistant path.

Current a workaround is to retrieve the full object and then set the field.

I'll try to fix it soon.

**Comment by PragmaTwice** [comment]
It will be fixed in https://github.com/apache/kvrocks/pull/2178.

Although it's not a perfect fix since we're waiting for support in the underlying library jsoncons, it can work for most scenarios.

**Comment by superikw** [comment]
Thanks for your work :)
