### ISSUE TITLE
The slave of the kvrocks cluster failed to synchronize data from the master

### ISSUE THREAD

**Issue by QQxiaoyuyu** [apache/kvrocks#2179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

kvrocks 2.8 ，kvrocks-controller unstable，kvrocks编译是采用了-DPORTABLE=1

### Minimal reproduce step

在运行了kvcontroller的情况下，使用api创建集群 /api/v1/namespaces/test-ns/clusters 

{
  "name":"demo-kvcluster",
  "nodes":["192.168.1.189:16660","192.168.1.189:16661","192.168.1.175:16662","192.168.1.175:16663","192.168.1.51:16664","192.168.1.51:16665"],
  "replicas":2,
  "password":"xxx#$()D-"
}

### What did you expect to see?

在master节点上面set ld  1111111111111111，在slave上面可以get到

### What did you see instead?

![image](https://github.com/apache/kvrocks/assets/34185590/8df485cd-d691-4605-a0c8-73f708ea7f46)
slave上未能get 到 ld

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@QQxiaoyuyu Could you provide the `nodes.conf` of `192.168.1.175:16663`?

**Comment by QQxiaoyuyu** [comment]
![image](https://github.com/apache/kvrocks/assets/34185590/38b62f6a-a8cd-4bbc-88c1-6c88eb0437de)

**Comment by QQxiaoyuyu** [comment]
The reson is master-use-repl-port = yes, cluster must config no
