### ISSUE TITLE
Add support of the XAUTOCLAIM command

### ISSUE THREAD

**Issue by Yangsx-1** [apache/kvrocks#2181]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue wants to implement [XAUTOCLAIM](https://redis.io/commands/xautoclaim/) command like redis.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by nioshield** [comment]
@Yangsx-1 I'm interested in implementing this command, can you please assign it to me? Thank you!

**Comment by caipengbo** [comment]
@nioshield It's been assigned to you. Welcome to participate in it again :)

**Comment by LindaSummer** [comment]
Hi @Yangsx-1 ,

  This thread seems to be inactivated for two months.

  I'm new to kvrocks and want to make some contributions.

  Can this issue be assigned to me? 

Thanks very much.

**Comment by Yangsx-1** [comment]
> Hi @Yangsx-1 ,
> 
> This thread seems to be inactivated for two months.
> 
> I'm new to kvrocks and want to make some contributions.
> 
> Can this issue be assigned to me?
> 
> Thanks very much.

Assigned, thank you!
