### ISSUE TITLE
KVRocks cluster does not support failover.

### ISSUE THREAD

**Issue by hcymysql** [apache/kvrocks#2191]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

kvrocks-2.8.0.tar.gz

### Minimal reproduce step

I found that the KVRocks cluster cannot achieve the cluster failover functionality of Redis cluster. I shut down a master node, but it could not fail over to a slave node.

### What did you expect to see?

I found that the KVRocks cluster cannot achieve the cluster failover functionality of Redis cluster. I shut down a master node, but it could not fail over to a slave node.

### What did you see instead?

I found that the KVRocks cluster cannot achieve the cluster failover functionality of Redis cluster. I shut down a master node, but it could not fail over to a slave node.

### Anything Else?

I found that the KVRocks cluster cannot achieve the cluster failover functionality of Redis cluster. I shut down a master node, but it could not fail over to a slave node.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@hcymysql That's right. The Kvrocks didn't integrate the gossip protocol like the Redis cluster, and it maintains the cluster topology in outside components to simplify the internal design. The community is building the [controller](https://github.com/apache/kvrocks-controller) to manage the Kvrocks cluster, the controller will offer the Web UI and failover/slot migration feature. But you can see, it's under developing status and might take some time to make it ready for users.

**Comment by hcymysql** [comment]
thanks
