### ISSUE TITLE
Add support FT (Searching and querying Redis data)

### ISSUE THREAD

**Issue by Spywer** [apache/kvrocks#2198]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Search the index with a textual query, returning either documents or just ids

https://redis.io/docs/interact/search-and-query/
https://redis.io/commands/ft.search

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Duplicated with #2064.
