### ISSUE TITLE
Fix GetOptions initializer to make it valid in C++17

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2212]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

```
/home/runner/work/kvrocks/kvrocks/src/types/redis_zset.cc:220:46: warning: designated initializers are a C++20 extension [-Wc++20-designator]
  rocksdb::Status s = GetMetadata(GetOptions{.snapshot = ss.GetSnapShot()}, ns_key, &metadata);
```

### What did you expect to see?

no warning

### What did you see instead?

```
/home/runner/work/kvrocks/kvrocks/src/types/redis_zset.cc:220:46: warning: designated initializers are a C++20 extension [-Wc++20-designator]
  rocksdb::Status s = GetMetadata(GetOptions{.snapshot = ss.GetSnapShot()}, ns_key, &metadata);
```

### Anything Else?

cc @mapleFU 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
I just back home, will fix this tonight
