### ISSUE TITLE
[BUG] Docker image is dead

### ISSUE THREAD

**Issue by jbenguira** [apache/kvrocks#223]
I tried the docker version indicated in the readme:
docker run -it -p 6666:6666 bitleak/kvrocks

But it's failing because the docker image is not available anymore on docker hub.

Is there any reason why?

**Comment by git-hulk** [comment]
@jbenguira sorry that the latest docker image was deleted by mistake and it's recovered now. You can have a try now.

**Comment by jbenguira** [comment]
Thanks :)
