### ISSUE TITLE
 Snorcloud has reported a potential leak of memory pointed

### ISSUE THREAD

**Issue by jihuayu** [apache/kvrocks#2237]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

----
Snorcloud has reported a potential leak of memory points. It makes our project reliability Rating to E

https://sonarcloud.io/project/issues?open=AY5rFU4fqWrU_C5xtNe-&id=apache_kvrocks
Can you check is it an issue @PragmaTwice ?

**Comment by PragmaTwice** [comment]
I think it's a false positive.
