### ISSUE TITLE
bug: inappropriate type of `ttl_` of `CommandSet`

### ISSUE THREAD

**Issue by J0HN50N133** [apache/kvrocks#2248]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

Since db2860d until now.

### Minimal reproduce step

https://github.com/apache/kvrocks/blob/a2380535d5602692f3746783c48ccc7bb05cc58e/src/commands/cmd_string.cc#L307

Here determine whether `ttl_` less than `0`, if so, doing deletion. However, the type of `ttl_` if `uint64_t` which is impossible to less than 0.

https://github.com/apache/kvrocks/blob/a2380535d5602692f3746783c48ccc7bb05cc58e/src/commands/cmd_string.cc#L340

### What did you expect to see?

If `ttl_` less than `0`, doing deletion.

### What did you see instead?

The condition will never be true, thus, deletion will never be done.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@J0HN50N133 Thanks for your report.

You're right, would you submit a PR to fix this?

**Comment by J0HN50N133** [comment]
I could fix it. Although the behaviour here is correct (because of implicit cast), it's disturbing.
