### ISSUE TITLE
[BUG] Unable to build.

### ISSUE THREAD

**Issue by smdev0925** [apache/kvrocks#225]
Attempting to compile as per instructions on Readme. Unable to build.

![image](https://user-images.githubusercontent.com/16979556/115429334-3865f000-a1fb-11eb-9fa8-619e4c5c8681.png)

`./db/version_edit.h:86:8: error: implicitly-declared ‘constexpr rocksdb::FileDescriptor::FileDescriptor(const rocksdb::FileDescriptor&)’ is deprecated [-Werror=deprecated-copy]`

 - OS: Ubuntu 20.04
 - GCC/G++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
 - GNU Make 4.2.1

**To Reproduce**
1. Build as per instructions on README

**Comment by smdev0925** [comment]
Just an as update, it wouldn't compile under GCC 10.2.0 either but I did have success using GCC 8.4.0.

Perhaps add that as a requirement within your Readme.md?

![image](https://user-images.githubusercontent.com/16979556/115434306-74e81a80-a200-11eb-8a3d-7cac45fd5a57.png)

**Comment by git-hulk** [comment]
many thanks to @shanemarsh28 to find out about this issue, it seems rocksdb doesn't support higher version GCC(>=9) and fixed in newer, we would also fix that. any progress would update in this channel.

relate issue: https://github.com/facebook/rocksdb/issues/5303

**Comment by git-hulk** [comment]
We have confirmed that the newer version(after 6.15.1) of rocksdb has compatible with gcc9 in ubuntu20.04. @karelrooted would help to investigate whether the newer version has other issues within kvrocks, and we would upgrade the rocksdb dependence to the latest if all works well.
