### ISSUE TITLE
[NEW] set a max size in mb and max connections to a namespace

### ISSUE THREAD

**Issue by jbenguira** [apache/kvrocks#227]
It would be really great to be able to set a max size (in mb ideally or number of keys) and a max number of connections to a namespace. The use case is to have a shared instance that can be used safely with quota by a lot of users.

Thanks for considering this :)

**Comment by git-hulk** [comment]
It's hard to isolate the connection or the DB size between namespaces with the current design, since the namespace was designed to isolate data between different dimension data like Redis DB indeed, with no intention to solve the multi-users in the same instance.

**Comment by jbenguira** [comment]
OK thanks for the clarification
