### ISSUE TITLE
Enable the new data type encoding by default

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2291]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

After many versions, it's safe to make new version by default.

### Solution

Set `ENABLE_NEW_ENCODING` to ON by default in cmake.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@VasuDevrani Assigned, thank you.
