### ISSUE TITLE
Move the performance benchmark to website

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

It does not need to be shown in README. Just a link is enough.

Also, if there's no reproduce script for it, I think we can just delete them.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by suxb201** [comment]
@git-hulk I couldn't find the benchmark on the website, even though you've removed it from the README.md.

**Comment by git-hulk** [comment]
@suxb201 Yes, the reason is the benchmark result cannot be reproduced by users, so remove it first to avoid confusing users.

**Comment by PragmaTwice** [comment]
It is not because the current performance is lower than the benchmark result, just we cannot find the benchmark script, so we decide to remove it.

We can add a reproducible benchmark script and also a benchmark post to our website later.

Anyway welcome to do benchmark by yourself and share with us. @suxb201
