### ISSUE TITLE
Optimize the implementation of IntervalSet intersection

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

https://github.com/apache/kvrocks/blob/82f03ca5edc6640a46a8f26d63ceb9385f30f744/src/search/interval.h#L130

We can optimize this function since the implementation here uses just De Morgan's laws, not very efficient.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by 13015517713** [comment]
I'll do this, and will propose a solution later.

**Comment by mapleFU** [comment]
Closed by https://github.com/apache/kvrocks/pull/2300
