### ISSUE TITLE
Add support for the TOUCH command

### ISSUE THREAD

**Issue by VasuDevrani** [apache/kvrocks#2314]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

TOUCH command is useful feature in Redis, allows updating LRU time of one or more keys without modifying their values. 
Note: I have just started working around Kvrocks, so not sure if this would be needed. Although I can think of some possible solution. Needed review/guide here.

### Solution

will update

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Kvrocks doesn't keep the last access time of keys and doesn't support key eviction.

So it's not so meaningful to support this command.

See if other guys have any comment.

cc @git-hulk

**Comment by git-hulk** [comment]
> Kvrocks doesn't keep the last access time of keys and doesn't support key eviction.
> 
> So it's not so meaningful to support this command.
> 
> See if other guys have any comment.
> 
> cc @git-hulk

Yes, exactly.
