### ISSUE TITLE
Force PR titles to follow the conventional commit format

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2339]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

By following conventional commits, PR titles can be neater and clearer, making unstable commit history more user-friendly and easier to write release notes.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PokIsemaine** [comment]
GitHub Action is used in some projects to check PR title. Maybe we can also add related Actions

example:
https://github.com/amannn/action-semantic-pull-request

https://github.com/apache/pulsar/blob/master/.github/workflows/ci-semantic-pull-request.yml
