### ISSUE TITLE
Docker images with Debian or Ubuntu

### ISSUE THREAD

**Issue by thomas-0816** [apache/kvrocks#2344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Since many companies run their production servers on Debian or Ubuntu, it would be nice to have a Debian or Ubuntu container on docker hub as well, for local testing.

e.g. I tested with a single stage build:

```
# image size is 114M compared to alpine build with 38M uncompressed

FROM debian:bookworm-slim

# chain commands for single layer
RUN apt-get -y update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install git build-essential cmake libtool \
        python3 libssl-dev autoconf automake ninja-build redis-tools ca-certificates \
    && git clone --depth 1 --branch v2.8.0 https://github.com/apache/kvrocks.git \
    && cd kvrocks/ \
    && ./x.py build -DENABLE_OPENSSL=ON -DPORTABLE=1 -DCMAKE_BUILD_TYPE=Release -j $(nproc) \
    && cp build/kvrocks /bin/kvrocks \
    && cd / \
    && rm -rf /kvrocks \
    && apt-get purge -y --auto-remove git build-essential cmake libtool python3 libssl-dev autoconf automake ninja-build \
    && apt-get clean \
    && rm -rf /tmp/* /var/lib/apt/lists/* /var/cache/apt/archives/*

EXPOSE 6666

HEALTHCHECK ...

ENTRYPOINT ["/bin/kvrocks"...]
```

Release tags could be 2.8.0-debian, 2.8.0-alpine, etc.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@thbley Thanks for your proposal.

@apache/kvrocks-committers What do you think about this? From my perspective, it did help when users wanted to debug the kvrocks.

**Comment by enjoy-binbin** [comment]
Sound good to me.

**Comment by aleksraiden** [comment]
I think, we can close this issue as done

**Comment by git-hulk** [comment]
@aleksraiden Yes, closing.
