### ISSUE TITLE
Extend limits of max value size to > 1Gb

### ISSUE THREAD

**Issue by wessorh** [apache/kvrocks#2399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

I like kvrocks and I'm interested in storing values that are larger than 256M, rocks db supports larger values and I'd like to take advantage of that capability.

### Solution

I don't yet know where the limitations are and would appreciate clues so that I can investigate further.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hi @wessorh Thanks for your report.

Maybe we can add a configuration `proto-max-bulk-len` for this purpose like Redis: [config.c#L3206](https://github.com/redis/redis/blob/69b480cb7a9c804b59406cc134951af5b52d8ea6/src/config.c#L3206C27-L3206C45)
