### ISSUE TITLE
Confusing error message while failed to parse the cluster slots 

### ISSUE THREAD

**Issue by spihiker** [apache/kvrocks#2401]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

v2.9.0

### Minimal reproduce step

 CLUSTERX SETNODES "86f7e437faa5a7fce15d1ddcb9eaeaea377667b8 172.20.84.154 6666 master - 0-5460 3c363836cf4e16666669a25da280a1865c2d2874 172.20.84.154 6669 slave 86f7e437faa5a7fce15d1ddcb9eaeaea377667b8" 1
(error) ERR Slot is out of range

### What did you expect to see?

normal as redis.

### What did you see instead?

no 

### Anything Else?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Could you try to add a `\n`?

```
CLUSTERX SETNODES "86f7e437faa5a7fce15d1ddcb9eaeaea377667b8 172.20.84.154 6666 master - 0-5460 \n  3c363836cf4e16666669a25da280a1865c2d2874 172.20.84.154 6669 slave 86f7e437faa5a7fce15d1ddcb9eaeaea377667b8" 1
```

**Comment by spihiker** [comment]
After add a \n.It can run normally.Thank you.

**Comment by git-hulk** [comment]
@PragmaTwice @spihiker This error message is very confusing for users, I have changed the issue title to track and improve it.

**Comment by jonathanc-n** [comment]
@PragmaTwice @git-hulk Would this be more of a parser change vs. a changed error messsage? Is using '\n' the proper way to do it?

**Comment by jonathanc-n** [comment]
This can be closed

**Comment by git-hulk** [comment]
@jonathanc-n Thank you!
