### ISSUE TITLE
Add an alternative environment to CentOS in CI

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

https://github.com/apache/kvrocks/blob/unstable/.github/workflows/kvrocks.yaml#L423-L428

Here we used to remove CentOS since it's officially out of support.

But we can add some alternative to CentOS (but still be RHEL-compatible) like Rocky Linux.

### Solution

--

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by SpiffyEight77** [comment]
Hey @PragmaTwice , sorry to bother you at this moment.
I am interested in this issue and would like to contribute.
Could you please assign it to me? 🙇🏻‍♂️

Here's my plan for this task before submitting a PR:
1. Ensure successful source builds in Rocky Linux.
2. Implement the CI logic.
3. Test in GitHub Actions.

**Comment by PragmaTwice** [comment]
Sure! Assigned.
