### ISSUE TITLE
Set default value of redis_cursor_compatible to yes

### ISSUE THREAD

**Issue by pangtujun** [apache/kvrocks#2427]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

希望redis_cursor_compatible 参数默认设置成yes，支持scan命令

### Solution

希望redis_cursor_compatible 参数默认设置成yes，支持scan命令

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Fixed in #2429.
