### ISSUE TITLE
how to migrate pika to kvrocks

### ISSUE THREAD

**Issue by epubreader** [apache/kvrocks#2468]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

how to migrate pika to kvrocks?
redis-shake doesn't work

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
It needs to depend on whether Pika has any way to migrate data to other Redis targets, and I'm unsure about this. And for the redis-shake, it's used to migrate Redis server instead of Pika, but maybe we can have a try a scan mode which only requires Pika supports the scan command.

**Comment by epubreader** [comment]
both scan mode and Sync Reader do not work,
but I wrote the scan code myself and have migrated pika to kvrocks.

**Comment by git-hulk** [comment]
@epubreader Great!
