### ISSUE TITLE
Remove  speedb due to it's lack of active in the public repository

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#2475]
The speedb is no longer active in the public repository after the acquisition, maybe we can remove it. What do you think? @apache/kvrocks-committers

_Originally posted by @git-hulk in https://github.com/apache/kvrocks/issues/2332#issuecomment-2270418939_

**Comment by torwig** [comment]
@git-hulk How long they haven't been active?

**Comment by mapleFU** [comment]
The last commit appears 5 month ago🤔

We can do a fast checking in https://github.com/apache/kvrocks/pull/2332 whether it's a bug for stream or other, if it's a not a bug, and we rely on some undefined behavior in rocksdb we need fix that. If speedb has bug then let's just remove it

**Comment by mapleFU** [comment]
Oh damn: https://www.speedb.io/ they're acquired by redis now 😅 Lets just remove that

**Comment by PragmaTwice** [comment]
+1.

**Comment by git-hulk** [comment]
@torwig Yes, it's about 5 months which is the time point after acquisition.

**Comment by torwig** [comment]
5 months. Then +1.
