### ISSUE TITLE
Add more tests for stream consumer group

### ISSUE THREAD

**Issue by Yangsx-1** [apache/kvrocks#2478]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

We should add more test cases for stream consumer group, especially for the time related information such as idle time and inactive time, and other information in XINFO command.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jonathanc-n** [comment]
@PragmaTwice @git-hulk What is the syntax for isolating go tests for testing?

**Comment by jonathanc-n** [comment]
@Yangsx-1 Are there any tests you would like to add in particular? Checking certain functionality?

**Comment by git-hulk** [comment]
> @PragmaTwice @git-hulk What is the syntax for isolating go tests for testing?

What do you mean by isolating go tests? Are you asking how to run the specified test cases?

**Comment by jonathanc-n** [comment]
@git-hulk Yes, specified test cases.

**Comment by Yangsx-1** [comment]
> @Yangsx-1 Are there any tests you would like to add in particular? Checking certain functionality?

I think we should pay attention to time related variables, such as idel time and inactive time in XINFO CONSUMERS, and some counter variables such as pending number, last_delivered_id, entries_read, lag and so on.

**Comment by Yangsx-1** [comment]
> @git-hulk Yes, specified test cases.

You can run command like this: `./x.py test go ./build -run ^TestStreamOffset$ github.com/apache/incubator-kvrocks/tests/gocase/unit/type/stream -v`, and you can change `TestStreamOffset` when you want to test other go functions.

**Comment by git-hulk** [comment]
> @git-hulk Yes, specified test cases.

You can run with `-test.run`. For example, I want to run the test case `TestFullSyncReplication`, then you should enter the dir `tests/gocase/integration/replication` and run `go test -test.run "TestFullSyncReplication" -workspace /tmp -binPath {Your Kvrocks Binary Path}`.

Remember to replace `{Your Kvrocks Binary Path}` with your owner Kvrocks binary path.

**Comment by jonathanc-n** [comment]
@Yangsx-1 @git-hulk Thank you guys
