### ISSUE TITLE
Add descriptions for commands on website documentation

### ISSUE THREAD

**Issue by jonathanc-n** [apache/kvrocks#2492]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Create a brief description for each command that is supported on kvrocks.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by jonathanc-n** [comment]
Can I be assigned this issue?

**Comment by git-hulk** [comment]
@jonathanc-n Done, thank you!

**Comment by jonathanc-n** [comment]
This can now be closed.

**Comment by git-hulk** [comment]
@jonathanc-n Thank you.
