### ISSUE TITLE
Compile error from kvrocks v2.8.0 in CentOS 7 env

### ISSUE THREAD

**Issue by 903174293** [apache/kvrocks#2497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

kvrocks v2.8.0
CentOS7
git clone
git checkout v2.8.0
x.py build

### Minimal reproduce step

git clone
git checkout v2.8.0
x.py build

### What did you expect to see?

成功

### What did you see instead?

[ 84%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/os.cc.o
[ 84%] Linking CXX static library libfmt.a
gmake[3]: Leaving directory '/root/zhangwanbin/2.8.0/kvrocks/build'
[ 84%] Built target fmt
gmake[3]: Entering directory '/root/zhangwanbin/2.8.0/kvrocks/build'
Scanning dependencies of target kvrocks_objs
gmake[3]: Leaving directory '/root/zhangwanbin/2.8.0/kvrocks/build'
gmake[3]: Entering directory '/root/zhangwanbin/2.8.0/kvrocks/build'
[ 84%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/cluster/batch_sender.cc.o
[ 84%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/cluster/cluster.cc.o
[ 85%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/cluster/redis_slot.cc.o
[ 85%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/cluster/replication.cc.o
[ 85%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/cluster/slot_import.cc.o
[ 85%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/cluster/slot_migrate.cc.o
[ 85%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/cluster/sync_migrate_context.cc.o
[ 85%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/commands/cmd_bit.cc.o
[ 85%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/commands/cmd_bloom_filter.cc.o
[ 86%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/commands/cmd_cluster.cc.o
[ 86%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/commands/cmd_function.cc.o
[ 86%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/commands/cmd_geo.cc.o
[ 86%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/commands/cmd_hash.cc.o
[ 86%] Building CXX object CMakeFiles/kvrocks_objs.dir/src/commands/cmd_json.cc.o
In file included from /root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor_reader.hpp:20,
                 from /root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor.hpp:19,
                 from /root/zhangwanbin/2.8.0/kvrocks/src/types/json.h:28,
                 from /root/zhangwanbin/2.8.0/kvrocks/src/types/redis_json.h:27,
                 from /root/zhangwanbin/2.8.0/kvrocks/src/commands/cmd_json.cc:31:
/root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor_parser.hpp: In instantiation of ‘jsoncons::cbor::basic_cbor_parser<Source, Allocator>::mapped_string::mapped_string(const string_type&, const allocator_type&) [with Source = jsoncons::bytes_source; Allocator = std::allocator<char>; jsoncons::cbor::basic_cbor_parser<Source, Allocator>::string_type = std::basic_string<char>; typename std::allocator_traits<_Alloc>::rebind_alloc<char> = std::allocator<char>; jsoncons::cbor::basic_cbor_parser<Source, Allocator>::mapped_string::allocator_type = std::allocator<char>]’:
/root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor_parser.hpp:735:54:   required from ‘void jsoncons::cbor::basic_cbor_parser<Source, Allocator>::read_text_string(jsoncons::cbor::basic_cbor_parser<Source, Allocator>::string_type&, std::error_code&) [with Source = jsoncons::bytes_source; Allocator = std::allocator<char>; jsoncons::cbor::basic_cbor_parser<Source, Allocator>::string_type = std::basic_string<char>; typename std::allocator_traits<_Alloc>::rebind_alloc<char> = std::allocator<char>]’
/root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor_parser.hpp:471:17:   required from ‘void jsoncons::cbor::basic_cbor_parser<Source, Allocator>::read_item(jsoncons::item_event_visitor&, std::error_code&) [with Source = jsoncons::bytes_source; Allocator = std::allocator<char>; jsoncons::item_event_visitor = jsoncons::basic_item_event_visitor<char>]’
/root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor_parser.hpp:247:25:   required from ‘void jsoncons::cbor::basic_cbor_parser<Source, Allocator>::parse(jsoncons::item_event_visitor&, std::error_code&) [with Source = jsoncons::bytes_source; Allocator = std::allocator<char>; jsoncons::item_event_visitor = jsoncons::basic_item_event_visitor<char>]’
/root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor_reader.hpp:87:9:   required from ‘void jsoncons::cbor::basic_cbor_reader<Source, Allocator>::read(std::error_code&) [with Source = jsoncons::bytes_source; Allocator = std::allocator<char>]’
/root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor_reader.hpp:77:9:   required from ‘void jsoncons::cbor::basic_cbor_reader<Source, Allocator>::read() [with Source = jsoncons::bytes_source; Allocator = std::allocator<char>]’
/root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/decode_cbor.hpp:35:20:   required from ‘typename std::enable_if<(jsoncons::extension_traits::is_basic_json<Json>::value && jsoncons::extension_traits::is_byte_sequence<Source>::value), T>::type jsoncons::cbor::decode_cbor(const Source&, const jsoncons::cbor::cbor_decode_options&) [with T = jsoncons::basic_json<char, jsoncons::sorted_policy, std::allocator<char> >; Source = std::basic_string_view<char>; typename std::enable_if<(jsoncons::extension_traits::is_basic_json<Json>::value && jsoncons::extension_traits::is_byte_sequence<Source>::value), T>::type = jsoncons::basic_json<char, jsoncons::sorted_policy, std::allocator<char> >]’
/root/zhangwanbin/2.8.0/kvrocks/src/types/json.h:78:69:   required from here
/root/zhangwanbin/2.8.0/kvrocks/build/_deps/jsoncons-src/include/jsoncons_ext/cbor/cbor_parser.hpp:66:102: error: no matching function for call to ‘std::basic_string<char>::basic_string(const string_type&, const allocator_type&)’
             : type(jsoncons::cbor::detail::cbor_major_type::text_string), str(str,alloc), bytes(alloc)
                                                                                                      ^
In file included from /opt/rh/devtoolset-8/root/usr/include/c++/8/string:52,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/locale_classes.h:40,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/ios_base.h:41,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/ios:42,
                 from /opt/rh/devtoolset-8/root/usr/include/c++/8/ostream:38,
                 from /root/zhangwanbin/2.8.0/kvrocks/build/_deps/glog-build/glog/logging.h:49,
                 from /root/zhangwanbin/2.8.0/kvrocks/src/commands/commander.h:25,
                 from /root/zhangwanbin/2.8.0/kvrocks/src/commands/cmd_json.cc:23:
/opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3632:7: note: candidate: ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::basic_string<_CharT, _Traits, _Alloc>::__sv_wrapper, c

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@903174293 Could you please have a try at devtoolset-11?

**Comment by git-hulk** [comment]
@903174293 Feel free to reopen if this issue is still living on your side.
