### ISSUE TITLE
why did kvrocks stopped when run for a fewer days

### ISSUE THREAD

**Issue by epubreader** [apache/kvrocks#2526]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

docker 2.9.0 as a salve

### Minimal reproduce step

I20240829 07:04:55.666883     8 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 44, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 3(1), output level(files): 4(1), input bytes: 134621982, output bytes:62393026, is_manual_compaction:no, elapsed(micro): 886844
I20240829 07:04:55.674885     8 event_listener.cc:166] [event_listener/table_file_deleted] db: /data/db, sst file: /data/db/003332.sst, status: OK
I20240829 07:04:55.690603     9 event_listener.cc:177] [event_listener/table_file_created] column family: default, file path: /data/db/003355.sst, file size: 48023726, job_id: 46, reason: compaction, status: OK
I20240829 07:04:55.690665     9 event_listener.cc:108] [event_listener/subcompaction_completed] column family: default, job_id: 46, compaction reason: Unknown, output compression type: no, base input level(files): 3, output level(files): 4, input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.693023     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 46, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 3(1), output level(files): 4(1), input bytes: 96002854, output bytes:48023726, is_manual_compaction:no, elapsed(micro): 458673
I20240829 07:04:55.707248     9 event_listener.cc:166] [event_listener/table_file_deleted] db: /data/db, sst file: /data/db/003330.sst, status: OK
I20240829 07:04:55.733680     9 event_listener.cc:166] [event_listener/table_file_deleted] db: /data/db, sst file: /data/db/003348.sst, status: OK
I20240829 07:04:55.753513     9 event_listener.cc:166] [event_listener/table_file_deleted] db: /data/db, sst file: /data/db/003351.sst, status: OK
I20240829 07:04:55.753652     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 47, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.754774     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 47, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.754900     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 48, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.755821     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 48, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.755920     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 49, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.756806     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 49, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.756891     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 50, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.757870     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 50, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.757967     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 51, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.758857     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 51, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.758944     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 52, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.759829     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 52, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240830 00:00:17.913046   128 compaction_checker.cc:34] [compaction checker] Start the compact the column family: pubsub
I20240830 00:00:17.913148   128 compaction_checker.cc:37] [compaction checker] Compact the column family: pubsub finished, result: OK
I20240830 00:00:17.913177   128 compaction_checker.cc:34] [compaction checker] Start the compact the column family: propagate
I20240830 00:00:17.913203   128 compaction_checker.cc:37] [compaction checker] Compact the column family: propagate finished, result: OK
I20240831 00:00:38.788959   128 compaction_checker.cc:34] [compaction checker] Start the compact the column family: pubsub
I20240831 00:00:38.789081   128 compaction_checker.cc:37] [compaction checker] Compact the column family: pubsub finished, result: OK
I20240831 00:00:38.789122   128 compaction_checker.cc:34] [compaction checker] Start the compact the column family: propagate
I20240831 00:00:38.789162   128 compaction_checker.cc:37] [compaction checker] Compact the column family: propagate finished, result: OK
I20240831 22:35:40.682274     1 main.cc:52] Bye Bye
I20240831 22:35:40.724730   117 replication.cc:952] [replication] Stop ev loop
I20240831 22:35:40.726697     1 replication.cc:371] [replication] Stopped
"docker.log" 1211L, 191013B

### What did you expect to see?

why did kvrocks stopped when run for a fewer days

### What did you see instead?

why did kvrocks stopped when run for a fewer days

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
> I20240831 22:35:40.682274 1 main.cc:52] Bye Bye

It indicates that someone send some signal to the kvrocks process to make it stop.

IMHO it's not an issue.

**Comment by epubreader** [comment]
> > I20240831 22:35:40.682274 1 main.cc:52] Bye Bye
> 
> It indicates that someone send some signal to the kvrocks process to make it stop.
> 
> IMHO it's not an issue.

did someone hack the server, how to check it?

**Comment by epubreader** [comment]
Hi, @wanghenshui when kvrocks process down, the container should restart, I have add "restart-condition on-failure" parameter.

**Comment by epubreader** [comment]
add master logs:

I20240829 07:04:55.478088     9 event_listener.cc:166] [event_listener/table_file_deleted] db: /data/db, sst file: /data/db/003344.sst, status: OK
I20240829 07:04:55.478173     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 3475, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.478853     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 3475, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.478917     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 3476, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.479483     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 3476, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.479527     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 3477, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.480060     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 3477, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 4(1), output level(files): 5(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.480103     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 3478, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.480641     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 3478, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.480680     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 3479, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.481225     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 3479, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240829 07:04:55.481266     9 event_listener.cc:79] [event_listener/compaction_begin] column family: default, job_id: 3480, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(0), input bytes: 0, output bytes:0, is_manual_compaction:no
I20240829 07:04:55.481810     9 event_listener.cc:89] [event_listener/compaction_completed] column family: default, job_id: 3480, compaction reason: LevelMaxLevelSize, output compression type: snappy, base input level(files): 5(1), output level(files): 6(1), input bytes: 0, output bytes:0, is_manual_compaction:no, elapsed(micro): 0
I20240830 00:00:08.965274   127 compaction_checker.cc:34] [compaction checker] Start the compact the column family: pubsub
I20240830 00:00:08.965399   127 compaction_checker.cc:37] [compaction checker] Compact the column family: pubsub finished, result: OK
I20240830 00:00:08.965422   127 compaction_checker.cc:34] [compaction checker] Start the compact the column family: propagate
I20240830 00:00:08.965442   127 compaction_checker.cc:37] [compaction checker] Compact the column family: propagate finished, result: OK
I20240831 00:00:14.683569   127 compaction_checker.cc:34] [compaction checker] Start the compact the column family: pubsub
I20240831 00:00:14.684681   127 compaction_checker.cc:37] [compaction checker] Compact the column family: pubsub finished, result: OK
I20240831 00:00:14.684916   127 compaction_checker.cc:34] [compaction checker] Start the compact the column family: propagate
I20240831 00:00:14.684942   127 compaction_checker.cc:37] [compaction checker] Compact the column family: propagate finished, result: OK
I20240831 01:10:23.821178 258118 replication.cc:115] WAL was rotated, would reopen again
W20240831 22:35:43.263211 258118 replication.cc:84] Slave thread was terminated, would stop feeding the slave: 10.0.1.253:39616

**Comment by mapleFU** [comment]
Better dmesg -T or using other to see how signal is sent.

**Comment by wanghenshui** [comment]
> Hi, @wanghenshui when kvrocks process down, the container should restart, I have add "restart-condition on-failure" parameter.


do you mean docker process exist but kvrocks process get killed？`restart-condition on-failure` works for docker ONLY, not the kvrocks process, you could use supervisor guard it

also like mapleFU said,  better dmesg -T check who killed it, maybe OOM killer or something else

**Comment by epubreader** [comment]
> Better dmesg -T or using other to see how signal is sent.

[Fri Aug 30 20:05:58 2024] br0: port 13(veth184) entered blocking state
[Fri Aug 30 20:05:58 2024] br0: port 13(veth184) entered forwarding state
[Fri Aug 30 20:05:58 2024] eth1: renamed from veth92a8d29
[Fri Aug 30 20:05:58 2024] br0: port 13(veth180) entered blocking state
[Fri Aug 30 20:05:58 2024] br0: port 13(veth180) entered forwarding state
[Fri Aug 30 20:05:58 2024] eth2: renamed from vethd3e7546
[Fri Aug 30 20:05:58 2024] docker_gwbridge: port 8(veth1af94e5) entered blocking state
[Fri Aug 30 20:05:58 2024] docker_gwbridge: port 8(veth1af94e5) entered forwarding state
[Sat Aug 31 22:35:14 2024] net_ratelimit: 7 callbacks suppressed
[Sat Aug 31 22:35:14 2024] IPVS: rr: FWM 776 0x00000308 - no destination available
[Sat Aug 31 22:35:14 2024] IPVS: rr: FWM 776 0x00000308 - no destination available
[Sat Aug 31 22:35:14 2024] IPVS: rr: FWM 776 0x00000308 - no destination available
[Sat Aug 31 22:35:14 2024] IPVS: rr: FWM 776 0x00000308 - no destination available
[Sat Aug 31 22:35:15 2024] br0: port 15(veth148) entered disabled state
[Sat Aug 31 22:35:15 2024] veth923586d: renamed from eth0
[Sat Aug 31 22:35:15 2024] br0: port 15(veth148) entered disabled state
[Sat Aug 31 22:35:15 2024] veth148 (unregistering): left allmulticast mode
[Sat Aug 31 22:35:15 2024] veth148 (unregistering): left promiscuous mode
[Sat Aug 31 22:35:15 2024] br0: port 15(veth148) entered disabled state
[Sat Aug 31 22:35:15 2024] br0: port 14(veth150) entered disabled state
[Sat Aug 31 22:35:15 2024] veth5d92f73: renamed from eth1
[Sat Aug 31 22:35:15 2024] docker_gwbridge: port 14(veth07cee69) entered disabled state
[Sat Aug 31 22:35:15 2024] veth4d4e731: renamed from eth2
[Sat Aug 31 22:35:15 2024] docker_gwbridge: port 14(veth07cee69) entered disabled state
[Sat Aug 31 22:35:15 2024] veth07cee69 (unregistering): left allmulticast mode
[Sat Aug 31 22:35:15 2024] veth07cee69 (unregistering): left promiscuous mode
[Sat Aug 31 22:35:15 2024] docker_gwbridge: port 14(veth07cee69) entered disabled state
[Sat Aug 31 22:35:15 2024] br0: port 14(veth150) entered disabled state
[Sat Aug 31 22:35:15 2024] veth150 (unregistering): left allmulticast mode
[Sat Aug 31 22:35:15 2024] veth150 (unregistering): left promiscuous mode
[Sat Aug 31 22:35:15 2024] br0: port 14(veth150) entered disabled state
