### ISSUE TITLE
Improve the implementation of fence between the replication and workers

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#2528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

The replication thread needs to avoid using the DB pointer while restoring the DB.
It now will set `is_loading` to true to stop new commands to be executed and
wait for [WorkExclusivityGuard](https://github.com/apache/kvrocks/blob/unstable/src/server/server.cc#L1339) to confirm
existing commands have been done. But as @mapleFU mentioned in chat, it's an error-prone
way to do like that, maybe we need to improve this by introducing a better fence implementation.

### Solution

None

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LindaSummer** [comment]
Hi @git-hulk ,

I'd like to follow up on this issue. Could this be assigned to me?

Could you please provide more details about the chat mentioned and I can have a more comprehensive understanding of the problem. 😊

Best Regards,
Edward

**Comment by git-hulk** [comment]
@LindaSummer Thanks for your interest. We can close this issue after PR https://github.com/apache/kvrocks/pull/2549 which uses the `try_lock` to avoid the long pending in replication thread. So it should be good to leave as it is for now.

**Comment by LindaSummer** [comment]
> @LindaSummer Thanks for your interest. We can close this issue after PR #2549 which uses the `try_lock` to avoid the long pending in replication thread. So it should be good to leave as it is for now.

Got it! Thanks very much for your detail information about the issue. 😊
