### ISSUE TITLE
XINFO GROUPS fails to deduplicate; returns invalid `pending` 

### ISSUE THREAD

**Issue by nathanlo-hrt** [apache/kvrocks#2568]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable commit b8cf118bbe56984c7112c0929402f79d81d8a0d7

### Minimal reproduce step

```
127.0.0.1:3847> FLUSHALL
OK
127.0.0.1:3847> XGROUP CREATE stream1 group 0 MKSTREAM
OK
127.0.0.1:3847> XGROUP CREATE stream2 group 0 MKSTREAM
OK
127.0.0.1:3847> XREADGROUP GROUP group consumer STREAMS stream1 stream2 0 0
(nil)
127.0.0.1:3847> XINFO GROUPS stream2
1)  1) "name"
    2) "group"
    3) "consumers"
    4) (integer) 1
    5) "pending"
    6) (integer) 0
    7) "last-delivered-id"
    8) "0-0"
    9) "entries-read"
   10) (nil)
   11) "lag"
   12) (integer) 0
2)  1) "name"
    2) "group"
    3) "consumers"
    4) (integer) 0
    5) "pending"
    6) (integer) 1727818077688
    7) "last-delivered-id"
    8) "1727818077688-0"
    9) "entries-read"
   10) (integer) 0
   11) "lag"
   12) (integer) 0
```

### What did you expect to see?

The following output comes from Redis:
```
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379> XGROUP CREATE stream1 group 0 MKSTREAM
OK
127.0.0.1:6379> XGROUP CREATE stream2 group 0 MKSTREAM
OK
127.0.0.1:6379> XREADGROUP GROUP group consumer STREAMS stream1 stream2 0 0
1) 1) "stream1"
   2) (empty array)
2) 1) "stream2"
   2) (empty array)
127.0.0.1:6379> XINFO GROUPS stream2
1) 1) "name"
   2) "group"
   3) "consumers"
   4) (integer) 1
   5) "pending"
   6) (integer) 0
   7) "last-delivered-id"
   8) "0-0"
```

There are a few notable differences here:
1. `XREADGROUP GROUP` returns `stream1` and `stream2` as empty arrays instead of returning `nil` for the entire request
2. `XINFO GROUPS stream2` doesn't return a duplicated consumer group
3. `XINFO GROUPS stream2` correctly returns `pending = 0`

### What did you see instead?

`XINFO GROUPS` returns duplicated consumer groups, and returns an incorrect value for `pending`. 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by jonathanc-n** [comment]
@Yangsx-1 I didn't deal with the second part of that bug, as it was a logical error in the code and I wasn't too familiar with the implementation of the stream functions. As for directions, I believe the conflict arises due to how consumer groups are managed for different streams. The problem persists when more streams are added.

**Comment by LindaSummer** [comment]
> @Yangsx-1 I didn't deal with the second part of that bug, as it was a logical error in the code and I wasn't too familiar with the implementation of the stream functions. As for directions, I believe the conflict arises due to how consumer groups are managed for different streams. The problem persists when more streams are added.

Hi @jonathanc-n ,

I'd like to try to solve the rest part of this issue if you don't mind. 😊

Best Regards,
Edward
