### ISSUE TITLE
Dead lock possible?

### ISSUE THREAD

**Issue by calvinxiao** [apache/kvrocks#257]
The following code loop over `vector<StringPair>` and perform locking on each item.

- https://github.com/bitleak/kvrocks/blob/fbc41f03473c126a51c446a9216fef596dd47adc/src/redis_string.cc#L271-L285
- https://github.com/bitleak/kvrocks/blob/fbc41f03473c126a51c446a9216fef596dd47adc/src/redis_string.cc#L309-L323

If the keys are not sorted, is there going to be a potential dead lock problem?

**Comment by git-hulk** [comment]
Good question, there's not a possible deadlock since we lock and unlock one key every loop. if we lock all keys outside at once outside the loop that may cause deadlock without sorting.

**Comment by calvinxiao** [comment]
Right, it will get unlocked after each loop.
