### ISSUE TITLE
Move the rdb source files to a separate directory

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

It's not so related to other source files of `src/storage`, maybe it can be `src/storage/rdb`.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LindaSummer** [comment]
Hi @PragmaTwice ,

I want to follow up on this issue.

Could it be assigned to me?😊

Best Regards,
Edward

**Comment by git-hulk** [comment]
@LindaSummer Assigned, thank you!
