### ISSUE TITLE
Make configurable compression for L0-L1

### ISSUE THREAD

**Issue by paragor** [apache/kvrocks#2602]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

I have high write rate, and data have good compression (coef 8-10). But in kvrocks - L0 and L1 dont compress data. And i have a very big write/read rate for compaction L0-L1.
may be move to config this logic?

```
    // For the first two levels, it may contain the frequently accessed data,
    // so it'd be better to use uncompressed data to save the CPU.
    std::string compression_levels = "kNoCompression:kNoCompression";
    auto db = srv->storage->GetDB();
    for (size_t i = 2; i < db->GetOptions().compression_per_level.size(); i++) {
      compression_levels += ":";
      compression_levels += compression_option;
    }
    return srv->storage->SetOptionForAllColumnFamilies("compression_per_level", compression_levels);
  };
```

### Solution

add setting in config
```
 rocksdb.enable_compression_for_l0_and_l1 yes/NO
 ``` 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Maybe we can have an option called `rocksdb.nocompression_level`, 
and `rocksdb.nocompression_level n` means that the first `n` levels don't need to compress.

The default value can be 2.

**Comment by PragmaTwice** [comment]
Maybe we can have an option called `rocksdb.nocompression_level`, 

and `rocksdb.nocompression_level n` means that the first `n` levels don't need to compress.

**Comment by paragor** [comment]
```
    int compression_level;
    int nocompression_level;
```
funny naming :)

i think about something more verbose like
```
nocompression_for_first_levels
```

**Comment by PragmaTwice** [comment]
Good to me.

Also we can/should explain to users in comments.

**Comment by aleksraiden** [comment]
Good to me too, we also have an heavy write rate system
