### ISSUE TITLE
Add devcontainer config for Kvrocks

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2613]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

[Development Containers](https://containers.dev/) allows developers to use a container as a full-featured development environment. We can add a default container config for Kvrocks so that developers don't need to worry about enviornment problems.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by what-is-me** [comment]
Can I have a try?

**Comment by what-is-me** [comment]
Which base image should the devcontainer base on? debian:bookworm-slim or ubuntu:latest or any other version?

**Comment by git-hulk** [comment]
@what-is-me Assigned, thank you!

> Which base image should the devcontainer base on? debian:bookworm-slim or ubuntu:latest or any other version?

I prefer using `ubuntu:latest`. @PragmaTwice What do you think?
