### ISSUE TITLE
Key range of XREAD/XREADGROUP is not correct

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2625]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

https://github.com/apache/kvrocks/blob/5fccd57c66bc8f0e4138924fe6a0148931e5650f/src/commands/cmd_stream.cc#L1891-L1892

We need to define a KeyRangeGen function to make it produce correct key range.

### What did you expect to see?

--

### What did you see instead?

--

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LindaSummer** [comment]
Hi @PragmaTwice ,

I want to follow up on this issue.

Could it be assigned to me? 😊

Best Regards,
Edward

**Comment by PragmaTwice** [comment]
Sure.
