### ISSUE TITLE
Optimization of the "OK" String

### ISSUE THREAD

**Issue by RiversJin** [apache/kvrocks#2626]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

In the kvrocks codebase, we often see code like the following, representing a successfully executed action:
```c++
*output = redis::SimpleString("OK");
```
Due to the design of C++ and the limitations of std::string, although we know the returned string is always "+OK\r\n", the compiler cannot fully optimize this (https://godbolt.org/z/nr69s9z83).

Perhaps we could define "+OK\r\n" as a constant string to save on the overhead of repeated string concatenations. While this is a very short string, I believe this adjustment could provide a slight performance boost in theory.

Additionally, defining a constant string, rather than hardcoding "OK" throughout the code, may also improve code readability and maintainability.

I hope this suggestion is helpful. If there is support for this idea, I would be glad to submit a PR to implement this change.

Thank you for your consideration!

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
This is ok to me since "OK" would be frequently used, but I don't know what would other frequently used str like

**Comment by RiversJin** [comment]
> This is ok to me since "OK" would be frequently used, but I don't know what would other frequently used str like这对我来说很好,因为"OK"会经常使用,但我不知道其他经常使用的字符串会是什么

From the code perspective, it seems that "OK" is used most frequently, while others, like "PONG," appear occasionally. However, based on the principle of simplicity, I think caching the "OK" string alone should be sufficient.
