### ISSUE TITLE
StallConditionType2String transfer rocksdb::WriteStallCondition may be error

### ISSUE THREAD

**Issue by greatsharp** [apache/kvrocks#2633]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

kvrocks version 2.10.0

### Minimal reproduce step

In rocksdb,  WriteStallCondition is declared below

```c++
enum class WriteStallCondition {
  kDelayed,
  kStopped,
  // Always add new WriteStallCondition before `kNormal`
  kNormal,
};
```

see https://github.com/facebook/rocksdb/blob/main/include/rocksdb/types.h

but in kvrocks  /src/storage/event_listener.cc, function define

```
std::string StallConditionType2String(const rocksdb::WriteStallCondition type) {
  std::vector<std::string> stall_condition_strings = {"normal", "delay", "stop"};
  if (static_cast<size_t>(type) < stall_condition_strings.size()) {
    return stall_condition_strings[static_cast<size_t>(type)];
  }
  return "unknown";
}
```

if we pass type as WriteStallCondition::kNormal, then function StallConditionType2String returned 'stop';

totally reversed.

the EventListener::OnStallConditionsChanged will record a confused warning message.

### What did you expect to see?

WriteStallCondition::kNormal should be transfer to normal,
kDelayed should delay,
kStopped should be stop

### What did you see instead?

write stall condition was changed, from normal to stop

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Good catch! Would you like to fix it?

`std::vector<std::string>` seems not a good way to do that since it can not guarantee to be compatible to new versions of rocksdb when a new enum value is introduced.

We can impl by a `std::map<SomeRocksdbEnumType, std::string>`.

**Comment by mapleFU** [comment]
What about https://github.com/facebook/rocksdb/blob/a28cc4a38c2c7693a4786083d317bfc2cf874d76/db/write_stall_stats.h#L18 ?
