### ISSUE TITLE
Add more test cases about replication and cluster

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#2671]
By the way, can we add a test with master removed and about 5s' connection timeout in go integration?

_Originally posted by @mapleFU in https://github.com/apache/kvrocks/issues/2662#issuecomment-2477964921_

**Comment by LindaSummer** [comment]
Hi @PragmaTwice ,

  I want to follow up on this issue and learn about our replication logic.

 Could this issue be assigned to me? 😊

Best Regards,
Edward

**Comment by PragmaTwice** [comment]
Sure! Assigned.

**Comment by LindaSummer** [comment]
Hi @sryanyuan ,

Sorry to bother you in this thread.

I'm trying to create a case from your description for integration test.

> If the master is lost, the replication thread will block until the keepalive timer is reached when receiving full-sync SST files. At the same time, if we execute a 'clusterx setnodes' command, it will hold an exclusive lock until the replication thread is stopped. This will cause all other worker threads to block.

But I'm not sure about the configuration of the master and slave.

Could you give me some advice on reproducing the problem? 😊

Best Regards,
Edward

**Comment by PragmaTwice** [comment]
cc @mapleFU could you take a look?

**Comment by git-hulk** [comment]
The command `cluster setnodes` needs to stop the existing replication thread first before switching to the new master. So it will [stop the replication thread](https://github.com/apache/kvrocks/blob/698c3d4cedb7321b70bb4b4b2bc0abc9cd8db337/src/server/server.cc#L274) when adding the new master, but found the replication thread is hanging on fetching SST files for the sake of the connect/read timeout isn't set and the master is lost.

It will wait for about 3s after the PR #2662.

**Comment by LindaSummer** [comment]
> The command `cluster setnodes` needs to stop the existing replication thread first before switching to the new master. So it will [stop the replication thread](https://github.com/apache/kvrocks/blob/698c3d4cedb7321b70bb4b4b2bc0abc9cd8db337/src/server/server.cc#L274) when adding the new master, but found the replication thread is hanging on fetching SST files for the sake of the connect/read timeout isn't set and the master is lost.
> 
> 
> 
> It will wait for about 3s after the PR #2662.

Hi @git-hulk ,

Thanks for your detailed analysis! I will try this way today. 😊

By the way, do we have a way to confirm the SST file fetching status or force triggering the SST file syncing in cluster mode? 😊

Best Regards,
Edward

**Comment by git-hulk** [comment]
@LindaSummer Thanks for your efforts. For this case, I think it should be good to reproduce with an unreachable master IP only. Before PR #2662, it's expected to be hanging while switching to a new master. And after #662, it should be back to normal after a few seconds(3-4). cc @PragmaTwice @sryanyuan

**Comment by sryanyuan** [comment]
> Hi @sryanyuan ,
> 
> Sorry to bother you in this thread.
> 
> I'm trying to create a case from your description for integration test.
> 
> > If the master is lost, the replication thread will block until the keepalive timer is reached when receiving full-sync SST files. At the same time, if we execute a 'clusterx setnodes' command, it will hold an exclusive lock until the replication thread is stopped. This will cause all other worker threads to block.
> 
> But I'm not sure about the configuration of the master and slave.
> 
> Could you give me some advice on reproducing the problem? 😊
> 
> Best Regards, Edward

* Write some data into master
* Add a slave
* Before the full sync is completed, execute the following commands on the master to simulate network problems:
   ```
   service network stop
   echo `date "+%y-%m-%d %H:%M:%S"`---service network stop
   sleep 120s
   service network start
   echo `date "+%y-%m-%d %H:%M:%S"`---service network start
   ```

**Comment by LindaSummer** [comment]
> > Hi @sryanyuan ,
> 
> > 
> 
> > Sorry to bother you in this thread.
> 
> > 
> 
> > I'm trying to create a case from your description for integration test.
> 
> > 
> 
> > > If the master is lost, the replication thread will block until the keepalive timer is reached when receiving full-sync SST files. At the same time, if we execute a 'clusterx setnodes' command, it will hold an exclusive lock until the replication thread is stopped. This will cause all other worker threads to block.
> 
> > 
> 
> > But I'm not sure about the configuration of the master and slave.
> 
> > 
> 
> > Could you give me some advice on reproducing the problem? 😊
> 
> > 
> 
> > Best Regards, Edward
> 
> 
> 
> * Write some data into master
> 
> * Add a slave
> 
> * Before the full sync is completed, execute the following commands on the master to simulate network problems:
> 
>    ```
> 
>    service network stop
> 
>    echo `date "+%y-%m-%d %H:%M:%S"`---service network stop
> 
>    sleep 120s
> 
>    service network start
> 
>    echo `date "+%y-%m-%d %H:%M:%S"`---service network start
> 
>    ```

Hi @sryanyuan ,

Thanks very much!

Got it! I will try it later today.😊

Best Regards,
Edward

**Comment by sryanyuan** [comment]
> > > Hi @sryanyuan ,
> > 
> > 
> > > 
> > 
> > 
> > > Sorry to bother you in this thread.
> > 
> > 
> > > 
> > 
> > 
> > > I'm trying to create a case from your description for integration test.
> > 
> > 
> > > 
> > 
> > 
> > > > If the master is lost, the replication thread will block until the keepalive timer is reached when receiving full-sync SST files. At the same time, if we execute a 'clusterx setnodes' command, it will hold an exclusive lock until the replication thread is stopped. This will cause all other worker threads to block.
> > 
> > 
> > > 
> > 
> > 
> > > But I'm not sure about the configuration of the master and slave.
> > 
> > 
> > > 
> > 
> > 
> > > Could you give me some advice on reproducing the problem? 😊
> > 
> > 
> > > 
> > 
> > 
> > > Best Regards, Edward
> > 
> > 
> > 
> > * Write some data into master
> > * Add a slave
> > * Before the full sync is completed, execute the following commands on the master to simulate network problems:
> >   ```
> >   
> >   service network stop
> >   
> >   echo `date "+%y-%m-%d %H:%M:%S"`---service network stop
> >   
> >   sleep 120s
> >   
> >   service network start
> >   
> >   echo `date "+%y-%m-%d %H:%M:%S"`---service network start
> >   ```
> 
> Hi @sryanyuan ,
> 
> Thanks very much!
> 
> Got it! I will try it later today.😊
> 
> Best Regards, Edward

Glad to help
