### ISSUE TITLE
[QUESTION]hset mutiple arguments not supported?

### ISSUE THREAD

**Issue by hellower** [apache/kvrocks#273]
@@redis
127.0.0.1:6379> hset me lang english sex male
(integer) 2
127.0.0.1:6379> hgetall me
1) "lang"
2) "english"
3) "sex"
4) "male"
127.0.0.1:6379> 

===========================================================
@@kvrocks

127.0.0.1:6666>  hset me lang english sex male
(error) ERR wrong number of arguments        <====================
127.0.0.1:6666> 

127.0.0.1:9188> info
# Server
version:999.999.999
git_sha1:18d71d0d
os:Linux 4.19.0-16-cloud-amd64 x86_64
gcc_version:8.3.0
arch_bits:64
process_id:13
tcp_port:9188
uptime_in_seconds:313
uptime_in_days:0
# Clients
connected_clients:1
monitor_clients:0
...........
# RocksDB
estimate_keys[default]:1
block_cache_usage[default]:0
block_cache_pinned_usage[defa
......

**Comment by ShooterIT** [comment]
Yes, currently HSET command doesn't support multiple arguments. Let's support it 😄

**Comment by hellower** [comment]
wow !!
