### ISSUE TITLE
[BUG] dbsize return wrong value

### ISSUE THREAD

**Issue by hellower** [apache/kvrocks#275]
##################
# redis
##################
127.0.0.1:6379> keys *
1) "a"
2) "_tntchecker_"
3) "b"
127.0.0.1:6379> dbsize    <========== keys count
(integer) 3
127.0.0.1:6379>  info keyspace
-# Keyspace
db0:keys=3,expires=0,avg_ttl=0    <======== keys=3

##################
# kvrocks
##################
127.0.0.1:6666> keys *
1) "a"
2) "_tntchecker_"
3) "b"
127.0.0.1:6666> dbsize    <========== keys count
(integer) 0               <======= always return 0!!
127.0.0.1:6666>  info keyspace
-# Keyspace
-# Last scan db time: Thu Jan  1 00:00:00 1970
db0:keys=0,expires=0,avg_ttl=0,expired=0   <===== keys 0 
sequence:38283437
used_db_size:603247462
max_db_size:0
used_percent: 0%
disk_capacity:322110992384
used_disk_size:161157144576
used_disk_percent: 50%

**Comment by git-hulk** [comment]
Thanks for your report, it's not a bug actually, the kvrocks key-values were stored in disk, and find out expired keys was impossible unless we can scan it. So we MUST execute the `dbsize scan` command to async scan the DB for finding out the key number.

**Comment by hellower** [comment]
Thanks!
and Thank you for nice KVROCKS open source.

**Comment by ShooterIT** [comment]
Also welcome you to join in improving kvrocks 😄
