### ISSUE TITLE
[NEW] Redis modules

### ISSUE THREAD

**Issue by ehsanonline** [apache/kvrocks#305]
Supporting redis modules like RedisSearch and RedisGraph would be great. I tried to install them but there is no `MODULE LOAD` command or `loadmodule` in config file.

**Comment by git-hulk** [comment]
There's no possibility to use those Redis modules directly since the Kvrocks storage was on the disk, maybe we can implement mostly used modules ourselves.

@bitleak/kvrocks-core-team

**Comment by ShooterIT** [comment]
Thanks for your attention @ehsanonline Exactly, kvrocks doesn't support, actually, in our project 3.0, we want to multiple data models.

**Comment by crypt0miester** [comment]
any updates on this? I am working on a project that would make this a deal breaker. 

basically RedisSearch is needed to index a high volume dataset.

**Comment by caipengbo** [comment]
I think, for the search scenario, it is probably a relatively large project.  What I do know is that kvrocks will probably implement JSON first.

**Comment by crypt0miester** [comment]
alrighty. thanks champ. keep it up.
