### ISSUE TITLE
Difference between kvrocks and pika

### ISSUE THREAD

**Issue by dongdongwcpp** [apache/kvrocks#312]
What is the difference between pika and kvrocks? Does kvrocks provide better performance than pika?
Any improvements on the blackwidow storage engine design？

**Comment by git-hulk** [comment]
It's a good question, many users should have the same confusion, I would try to explain differences, but it's only my objective thoughts and can't promise fairness.

**From the key design:**

* We prefer to keep consistent with Redis sematic which the Pika didn't. e.g.  Pika allows different types to have the same key which wasn't expected.
* We do much work on improving the performance and decreasing the latency. Like  auto adjust the block and SST with the key-value size,  as well as using the compaction checker to reduce the full compaction on the RocksDB.
* We also care about profiling which would help users to find the performance issue. Users can use the `perf` command to investigate the issue when suffering the latency spike.
* Finally,  the core competitiveness of the kvrocks was simple and maintainable enough for most users. The tendis should be too complex for most users/companies, also hard to deploy.

**From the organization:**

this project didn't own by any company, it's a totally open-source org. Also, core team members were from different companies with many years in the distributed key-value field.
