### ISSUE TITLE
possible to implement redisearch?

### ISSUE THREAD

**Issue by hiqsociety** [apache/kvrocks#325]
do you have the implementation guideline on how to implement redisearch?
written like this?
https://kvrocks.medium.com/design-complex-structure-on-rocksdb-993a00fd4f6d?source=post_internal_links---------0----------------------------

**Comment by ShooterIT** [comment]
currently, we are thinking how to support redis module, but now, we don't have conclusion, we would like to listen your ideas if you have

**Comment by tisonkun** [comment]
Closed as inactive. We don't keep a wishing list. Any design is welcome.
