### ISSUE TITLE
Why is kvrocks so slow?

### ISSUE THREAD

**Issue by hiqsociety** [apache/kvrocks#332]
I've run kvrocks benchmark against redis

R 160k, w 55k/s 

Redis
R 1.2mil, w 1mil/s

**Comment by git-hulk** [comment]
Can u offer more information about the CPU(how many cores), Memory/Disk Type(HDD/SSD/NVMe...), as well as the benchmark command. BTW, seems you benched with the pipeline mode? It makes no sense that Redis performance up to the millilion QPS in single request mode.

**Comment by git-hulk** [comment]
dup with #322
