### ISSUE TITLE
How I stop the server?

### ISSUE THREAD

**Issue by ZonghaoWang** [apache/kvrocks#339]
**Describe the bug**

 - OS: [e.g. Centos 7]
 - Version [e.g. 1.1.5]

**To Reproduce**
1. 
2.
3.

**Expected behavior**

**Comment by git-hulk** [comment]
Do you mean how to shut down the kvrocks? If yes, use redis-cli to send the shutdown command.

**Comment by ZonghaoWang** [comment]
thank you
