### ISSUE TITLE
有时候从服务器无法进行同步

### ISSUE THREAD

**Issue by haodiao** [apache/kvrocks#341]
我的主服务器在国内，从服务器在国外，  
从服务器每隔几天就不再进行同步了，只能进行重起才能恢复正常，  
    
主从服务器之间的网络可能不是非常稳定，导致从服务器的同步功能卡住，希望可以解决这个问题

**Comment by ShooterIT** [comment]
What version are you using? Maybe this PR #284 fixed this problem, the latest version 2.0.2 that has this patch is released.

**Comment by haodiao** [comment]
@ShooterIT 就是最新的 2.0.2 出现同样的问题，这个版本发布的当天我就重新进行编译，     
到现在不到一周的时间，出现过3台从服务器同步中断的现象（必须重启才能恢复），    
我的环境是 1主8从（1主在国内，8台从在国外）

**Comment by ShooterIT** [comment]
@haodiao 能提供一下相应时间点主从的日志吗？

**Comment by haodiao** [comment]
@ShooterIT 
从服务器的日志：  
`E0721 19:44:41.368650 16702 replication.cc:133] [replication] connection error/eof, reconnect the master
E0721 19:44:45.402782 16702 replication.cc:211] [replication] Failed to connect the master, err:Connection timed out`

主服务器的日志（IP部分"*"代替）：    
`E0721 19:56:14.416370 14828 replication.cc:60] Ping slave[103.129.*.*:55912] err: Connection timed out, would stop the thread 
W0721 19:56:14.416435 14828 replication.cc:48] Slave thread was terminated, would stop feeding the slave: 103.129.*.*:55912`

**Comment by git-hulk** [comment]
这个主要是因为从库在断掉之后，目前重连机制有问题导致没有重连
