### ISSUE TITLE
Upgrade the version of cpplint from 1.5.0 to 1.5.5.

### ISSUE THREAD

**Issue by LykxSassinator** [apache/kvrocks#342]
Here, i've found a misleading cpplint errors generated by `cpplint.sh` in the progress of CI. And i've made sure that i've format the code by the Google code-style standard, with the necessary double-check by `cpplint` tool. However, the CI cpplint checking showed that there still exists some style errors in the code. So, i tried to check the difference of cpplint-1.5.0, defaultly used in the CI of kvrocks, between the version 1.5.5.
And the difference showed as bellow:
![image](https://user-images.githubusercontent.com/18441614/126864134-9e6c0bbb-8f34-4642-b735-70b7dd4ba846.png)

Finally, i've checked the `releasing logs` of `cpplint`, and found the following results:
![image](https://user-images.githubusercontent.com/18441614/126864169-782b0219-e104-4db2-8b06-7b6422cdd842.png)

***So, could we upgrade the version of `cpplint` in the CI of kvrocks to `1.5.5` ?***

 I‘ve verified the upgrade was valid in my local repository CI checking progress.
![image](https://user-images.githubusercontent.com/18441614/126864374-b349a959-96f9-4b41-a0da-bb9594026240.png)
![image](https://user-images.githubusercontent.com/18441614/126864393-3cc73ba3-92d3-4f65-8cfd-014055d2cf86.png)

**Comment by tisonkun** [comment]
cpplint is replaced with clang-format and clang-tidy in #800.

Closed as invalid.
