### ISSUE TITLE
namespace 有没有分空间存储？为什么重启后namespace都丢失了？

### ISSUE THREAD

**Issue by ZonghaoWang** [apache/kvrocks#353]
Please keep in mind that this issue tracker should be used for reporting bugs or proposing improvements to the kvrocks server.

Generally, questions about using kvrocks should be directed to the [community](https://groups.google.com/g/kvrocks).

It is also possible that your question was already asked here, so please do a quick issues search before submitting.

That said, please feel free to replace all this with your question :)

**Comment by ShooterIT** [comment]
这是设计文档 https://github.com/KvrocksLabs/kvrocks/blob/unstable/docs/multi-tenant.CN.md
namespace会作为key的前缀存储，应该不会丢失，有没有复现的步骤

**Comment by git-hulk** [comment]
@ShooterIT @ZonghaoWang 我在想是不是 config add $ns $token, 然后没有执行 config rewrite。如果记得 $ns 直接再增加就可以了，数据不会丢失。

**Comment by ZonghaoWang** [comment]
> @ShooterIT @ZonghaoWang 我在想是不是 config add $ns $token, 然后没有执行 config rewrite。如果记得 $ns 直接再增加就可以了，数据不会丢失。

没有执行config rewrite, 我执行后再试试

**Comment by ZonghaoWang** [comment]
问题解决了
