### ISSUE TITLE
[QUESTION] What's the recommended filesystem for kvrocks? 

### ISSUE THREAD

**Issue by adulau** [apache/kvrocks#354]
We are using kvrocks in production using ext4 filesystem and having around 4000 SST files.  We were wondering if XFS would be better for performance. Did you do some specific tests with the different filesystems?  Thank you very much.

**Comment by ShooterIT** [comment]
Thanks, I also thought this question, but i did not test😜, currently we also use ext4 filesystem, XFS has better performance in some scenes, it truly worths to test, @git-hulk did you ever test for different filesystem?
And kvrocks is based on rocksdb, maybe this is a generic questions.

**Comment by git-hulk** [comment]
No actually, we also used ext4.

**Comment by smartlee** [comment]
Our file system is xfs in production,kvrocks run in docker, and os is centos7 ,kernel version is 4.19.118
