### ISSUE TITLE
[QUESTION] Where is the data in docker container

### ISSUE THREAD

**Issue by orctom** [apache/kvrocks#364]
I see no VOLUME section in Dockerfile, no files in /data folder in container.
So where does the data been persisted?

**Comment by git-hulk** [comment]
The data was stored in dir `/tmp/kvrocks`, the docker was only intended for tests so didn't export the volume and data-dir.

**Comment by orctom** [comment]
Thanks dude.
Looking forward to a production ready docker image, easier to roll out to cloud.
