### ISSUE TITLE
[BUG]使用redisson 封装的 poll(num) 获取内容错误

### ISSUE THREAD

**Issue by QQxiaoyuyu** [apache/kvrocks#370]
**Describe the bug**

 - OS: [e.g. Centos 7]
 - Version [e.g. unstable]

**To Reproduce**
1. 
![图片](https://user-images.githubusercontent.com/34185590/137421277-d9635516-ce74-4113-b921-cd95c4fbb300.png)

2.正常 redisson 连 redis 是对的    不会出现类型错误
3.现在使用redisson 封装的 poll(num) 获取出的内容都是 String 类型了

**Expected behavior**

**Comment by git-hulk** [comment]
需要补充一下，对应执行的时候， Redis monitor 返回结果是什么，kvrocks  返回结果是什么

**Comment by QQxiaoyuyu** [comment]
kvrocks 返回的命令
![图片](https://user-images.githubusercontent.com/34185590/137427351-a7983bc8-8d5e-4ba1-91e8-f12b73aa2a5b.png)



redis 执行的命令，返回的结果
![图片](https://user-images.githubusercontent.com/34185590/137424651-3e6bcdb9-350f-47a2-b844-9dfd51e4d983.png)
结果
![图片](https://user-images.githubusercontent.com/34185590/137424683-5aab4ff2-244a-47a6-9cae-bfa4bdda9fa3.png)

**Comment by git-hulk** [comment]
Fixed by https://github.com/KvrocksLabs/kvrocks/pull/369
