### ISSUE TITLE
[NEW] Enable share block cache between  the metadata and subkey column family by default

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#372]
Kvrocks supported the share block cache between the metadata and subkey column family, it's really a good point to speed up the lookup query. So it should be enabled by default? since it hurts nothing, also most users should NOT care about how to allocate the ratio of block cache between the metadata and subeky column family.

**Comment by caipengbo** [comment]
Yes, it is a good idea to turn `rocksdb.share_metadata_and_subkey_block_cache` to `yes` by default.
