### ISSUE TITLE
[BUG] The configuration item rocksdb.compression cannot take effect

### ISSUE THREAD

**Issue by caipengbo** [apache/kvrocks#384]
Kvrocks has a configuration item called `rocksdb.compression`, which is assigned to `rocksdb::Options`:
https://github.com/KvrocksLabs/kvrocks/blob/2e43741ddedc06f0376d71dc385e9d53a24b3204/src/storage.cc#L87

But Kvrocks calls rocksdb's built-in optimization function:
https://github.com/KvrocksLabs/kvrocks/blob/2e43741ddedc06f0376d71dc385e9d53a24b3204/src/storage.cc#L80

This function will set `compression_per_level`. Like the [Rocksdb Wiki](https://github.com/facebook/rocksdb/wiki/Compression#configuration) says, when `options.compression_per_level` is used, `options.compression` is ignored.

Rocksdb's built-in optimization function selects the best compression algorithm. **So do we need to remove `rocksdb.compression` configuration item in Kvrocks?**

**Comment by git-hulk** [comment]
Good catch, as [OptimizeLevelStyleCompaction](https://github.com/facebook/rocksdb/blob/3e1bf771a3c7324306fc31317c9ea275e1a8dd61/options/options.cc#L600) would use the `lz4` first then the `snappy` if supported, but they're still some other compressions.  So seems that we can NOT enable the OptimizeLevelStyleCompaction when the compression was explicitly specified, HDYT.

**Comment by caipengbo** [comment]
`OptimizeLevelStyleCompaction ` function also optimizes other parameters, such as `write_buffer_size `, `max_bytes_for_level_base `, and so on. But we'll overwrite these parameters later. 

Maybe can we get rid of `OptimizeLevelStyleCompaction`, then set `compression_per_level`  in kvrocks?

**Comment by git-hulk** [comment]
Looks fine for me
