### ISSUE TITLE
Can I set     cluster-announce-*  at profiles ?

### ISSUE THREAD

**Issue by lt1946** [apache/kvrocks#421]
like these:
    cluster-announce-ip ${IP}
    cluster-announce-port ${PORT}
    cluster-announce-bus-port 1${PORT}
for redisson use.
Thanks.

**Comment by git-hulk** [comment]
Do you mean to use the kvrocks with the Redis cluster mode in Radisson? 

No, if I didn't misunderstand your meaning.

**Comment by lt1946** [comment]
yes, use at java like redisson!
I run cluster mode. find error; it's not set cluster-announce-ip at profile.

**Comment by git-hulk** [comment]
Kvrocks cluster mode has a bit different from Redis, so we can't add the kvrocks as the Redis cluster mode in Redisson. There should need more extra work to use Kvrocks mode in Redisson, but the good news was that you can use the Kvrocks as the single server or sentinel mode.

Welcome to feedback if you have any thoughts, :)
