### ISSUE TITLE
[NEW] Support some status to info command result

### ISSUE THREAD

**Issue by iushas** [apache/kvrocks#433]
When execute bgsave command in redis, we can get some progess stats and result stats through  info command, such as 
 "rdb_changes_since_last_save:253062290
rdb_bgsave_in_progress:0
rdb_last_save_time:1640050693
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:153
rdb_current_bgsave_time_sec:-1 ".etc,

we can known if the command excute rightly or not by analysor the info stats。

I think it will be cool if kvrocks can do the same things like redis !

@git-hulk

**Comment by git-hulk** [comment]
@iushas Thanks for your feedback, would add more informations for bgsave soon.
