### ISSUE TITLE
[BUG] Maybe there's a bug in the publish/subscribe logic

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#448]
**Describe the bug**
The github actions occasionally failed at Publish/Subscribe tcl test cases like below: 

https://github.com/KvrocksLabs/kvrocks/runs/4751562466?check_suite_focus=true#step:7:725

After reviewing the test case many times and it always happened on the ubuntu which was multi-threads, so i think it should be caused by the data race condition in the publish/subscribe logical, but still didn't find the right way to reproduce this issue.

**Comment by git-hulk** [comment]
Maybe we can have a try at Ubuntu with enabling the thread sanitizer.

**Comment by tisonkun** [comment]
Closed as stale. This issue seems vanished.
