### ISSUE TITLE
Wrong per-cmd latencies in Grafana dashboard

### ISSUE THREAD

**Issue by bisho** [apache/kvrocks#451]
**Describe the bug**
Not sure if you created this grafana dashboard, I hope it was you:
https://grafana.com/grafana/dashboards/15286

Latencies in the grafana dashboard are graphed as:

```
sum(rate(kvrocks_commands_duration_seconds_total{instance="$instance"}[$interval])) by (cmd)
```

If you see, the per-cmd command duration is not divided by the number of requests, so it is showing a sum of latencies for all run cmds. I think it should be:

```
sum(rate(kvrocks_commands_duration_seconds_total{instance="$instance"}[$interval])) by (cmd) / sum(rate(kvrocks_commands_total{instance="$instance"}[$interval])) by (cmd)
```

We also preferred to exclude the `psync` command, since it takes a lot longer than other production cmds, and makes it eaier to find issues with performance:

```
sum(rate(kvrocks_commands_duration_seconds_total{instance="$instance", cmd!="psync"}[$interval])) by (cmd) / sum(rate(kvrocks_commands_total{instance="$instance", cmd!="psync"}[$interval])) by (cmd)
```

If the intention was to show the usage by cmd type, then the graph is right, but you probably want to adjust the title to make it clear. We were shocked to see latency graph growing with load to very unreasonable numbers.

**Comment by git-hulk** [comment]
Yes, thanks for your feedback, you're right that we should divide the requests instead of total latency. Would fix it later~ : )

**Comment by git-hulk** [comment]
@bisho Fixed, can have a try again. For excluding `psync`, can modify it after importing since it would be strange to remove it from the basic template.

**Comment by bisho** [comment]
Looks great, thanks!
