### ISSUE TITLE
[QUESTION]Setbit max offset limit

### ISSUE THREAD

**Issue by ColinChamber** [apache/kvrocks#454]
Kvrocks' limit on setbit offset seems narrow, less than the maximum value in Redis (512M*8-1). According to the design of `metadata size(4byte)`, the max offset can even be larger than Redis. Why is the limit `INT_MAX` #164? Should `std::stoi` not be used in `bitcount`? Is there some context I don't comprehend @ShooterIT ?

![screenshot_358](https://user-images.githubusercontent.com/95634254/149277858-71828178-c6ae-4026-94f6-51cf006a58d9.png)
![screenshot_359](https://user-images.githubusercontent.com/95634254/149277870-9da97cc3-0163-48b8-a8c9-8c93dc5b3c18.png)

**Comment by git-hulk** [comment]
@ColinChamber It's a bug to use std::stoi, we should regard it as unsigned int. Would you like to fix this issue?

**Comment by ColinChamber** [comment]
Ok, I will fix it today.

**Comment by ColinChamber** [comment]
There is more code to modify than expected, and I still need some time to test.

> Ok, I will fix it today.

**Comment by git-hulk** [comment]
cool, very appreciate your hard work to make the Kvrocks better.
