### ISSUE TITLE
can it monitor expired key?

### ISSUE THREAD

**Issue by ZonghaoWang** [apache/kvrocks#457]
Please keep in mind that this issue tracker should be used for reporting bugs or proposing improvements to the kvrocks server.

Generally, questions about using kvrocks should be directed to the [community](https://groups.google.com/g/kvrocks).

It is also possible that your question was already asked here, so please do a quick issues search before submitting.

That said, please feel free to replace all this with your question :)

**Comment by git-hulk** [comment]
Do you mean can we monitor the number of expired key numbers?

**Comment by ZonghaoWang** [comment]
pubsub redis event,
in redis.conf, notify-keyspace-event

**Comment by git-hulk** [comment]
Got what you mean, it’s not easy for Kvrocks since expired behavior was delay to RocksDB compaction. Welcome to feedback if you have any thoughts l.

**Comment by ZonghaoWang** [comment]
thanks
