### ISSUE TITLE
Support for replica-announce-ip and replica-announce-port

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#484]
### Discussed in https://github.com/KvrocksLabs/kvrocks/discussions/481

<div type='discussions-op-text'>

<sup>Originally posted by **djotanov** February 13, 2022</sup>
In docker/kubernetes, instances don't have a fixed up. When working with dynamic IPs, sentinel will not work, unless kvrocks can be configured to announce DNS address of the instance (and mapped port if needed).
Does kvrocks support `replica-announce-ip' and 'replica-announce-port` properties (couldn't see them in config file)?
Redis support these since 3.2 version.</div>

**Comment by paragor** [comment]
done via https://github.com/apache/incubator-kvrocks/pull/1303
