### ISSUE TITLE
[BUG] phpredis: Can't communicate with any node in the cluster

### ISSUE THREAD

**Issue by xuzhenjun130** [apache/kvrocks#486]
**Describe the bug**
php客户端无法使用 kvrocks 集群
> https://github.com/phpredis/phpredis
报错：Can't communicate with any node in the cluster

 - OS: [Centos 7]
 - kvrocks [2.0.6] 编译
 - phpredis[ 5.1.1]
 - php: [7.4]

**To Reproduce**
1. 运行集群配置脚本：tools/try_cluster/try_cluster.sh
2. php代码：
```php
<?php
$config = [
    '192.168.100.244:30001',
    '192.168.100.244:30002',
    '192.168.100.244:30003',
    '192.168.100.244:30004',
    '192.168.100.244:30005',
    '192.168.100.244:30006',
];
$redis = new \RedisCluster(null,$config);

for ($i=0; $i< 10; $i++){
    $rs = $redis->set('name:'.$i, $i);
    $data = $redis->get('name:'.$i);
    var_dump($data);
}
```
运行以上php代码报错：Can't communicate with any node in the cluster

**Expected behavior**
上面的php代码，在 `tendis`  cluster 集群测试通过，无异常

kvrocks 集群信息：
```bash
192.168.100.244:30001> cluster nodes
kvrockskvrockskvrockskvrockskvrocksnode6 127.0.0.1:30006@40006 slave kvrockskvrockskvrockskvrockskvrocksnode5 1645008141999 1645008142000 1 connected
kvrockskvrockskvrockskvrockskvrocksnode5 127.0.0.1:30005@40005 master - 1645008141999 1645008142000 1 connected 10993-16383
kvrockskvrockskvrockskvrockskvrocksnode3 127.0.0.1:30003@40003 master - 1645008141999 1645008142000 1 connected 5461-10992
kvrockskvrockskvrockskvrockskvrocksnode4 127.0.0.1:30004@40004 slave kvrockskvrockskvrockskvrockskvrocksnode3 1645008141999 1645008142000 1 connected
kvrockskvrockskvrockskvrockskvrocksnode2 127.0.0.1:30002@40002 slave kvrockskvrockskvrockskvrockskvrocksnode1 1645008141999 1645008142000 1 connected
kvrockskvrockskvrockskvrockskvrocksnode1 127.0.0.1:30001@40001 myself,master - 1645008141999 1645008142000 1 connected 0-5460
192.168.100.244:30001> keys *
(empty list or set)
192.168.100.244:30001> set name hello
(error) MOVED 5798 127.0.0.1:30003
192.168.100.244:30001> get name
(error) MOVED 5798 127.0.0.1:30003
192.168.100.244:30001> exit
root@DESKTOP-LJ4P7IV:/www/crm2.910app.com# redis-cli -h 192.168.100.244 -p 30003
192.168.100.244:30003> get name
(nil)
192.168.100.244:30003> set name hello
OK
192.168.100.244:30003> get name
"hello"
```

另外，kvrocks 是否支持双主配置，如何配置？
目前业务使用ssdb，数据量30G还不算太大，估计迁移到kvrocks还能再用几年，不需要使用集群架构

**Comment by ShooterIT** [comment]
IP 地址改为 127.0.0.1 试试，try_cluster.sh 默认 bind 127.0.0.1了
```php
$config = [
    '127.0.0.1:30001',
    '127.0.0.1:30002',
    '127.0.0.1:30003',
    '127.0.0.1:30004',
    '127.0.0.1:30005',
    '127.0.0.1:30006',
];
```
不支持双主配置

**Comment by xuzhenjun130** [comment]
ok，改成 127.0.0.1 正常了。
之前我改了 `tools/try_cluster/default.conf`  中 把绑定ip 改成了 0.0.0.0， 没想到 try_cluster.sh 里面还有ip设置

另外吐槽一下，kvrocks 的文档太少了。

https://github.com/KvrocksLabs/kvrocks/wiki/Kvrocks-%E9%9B%86%E7%BE%A4%E6%96%B9%E6%A1%88%E7%AE%80%E4%BB%8B

集群介绍这里的示例格式并不能直接去执行，建议修改一下
```
CLUSTERX SETNODES
  "67ed2db8d677e59ec4a4cefb06858cf2a1a89fa1 127.0.0.1 30002 master - 5461-10922 16380 16383
    07c37dfeb235213a872192d90877d0cd55635b91 127.0.0.1 30004 slave 67ed2db8d677e59ec4a4cefb06858cf2a1a89fa1"
  1
```
- `CLUSTERX SETNODES` 后面没有换行
- 不能进入redis-cli 里面再执行，必须在外面 `redis-cli -h 127.0.0.1 -p 30001 clusterx setnodes "节点配置，一行一个"  1`

不看try_cluster.sh  根本不知道

**Comment by git-hulk** [comment]
@xuzhenjun130 如果是不需要集群模式就可以不用 enable cluster，直接使用 Master-Slave 方式，跟 Redis  使用几乎是一模一样

**Comment by xuzhenjun130** [comment]
@git-hulk   
主从这个明白。只是我们原来使用ssdb，部分业务把ssdb当成数据库在用了，两地机房，所以配置的是双主架构。
不改业务代码的情况下，不能使用主从

**Comment by ShooterIT** [comment]
> 之前我改了 tools/try_cluster/default.conf 中 把绑定ip 改成了 0.0.0.0， 没想到 try_cluster.sh 里面还有ip设置z

这个脚本参考了 Redis create cluster，这里 Redis 实现是一样的

Kvrocks 当前是几个爱好者在工作之外维护的，人力有限，很多地方需要靠大家一起建设，也非常欢迎你为 Kvrocks 完善文档。

cluster setnodes 中 node_info 每一行设置一个node信息，我忘了写了，已修改，谢谢指出
