### ISSUE TITLE
[NEW] Supports to configure the rocksdb advance option max_bytes_for_level_base

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#488]
As users may want to control the maximum data size for a level,
we can export the option `max_bytes_for_level_base`(the max total for level-1)
in our config file and allow to modify the value in-flight with `config set`.

For more detail can see: https://github.com/facebook/rocksdb/blob/main/include/rocksdb/options.h#L271

**Comment by tisonkun** [comment]
Closed by #497.
