### ISSUE TITLE
[BUG] Wrong replication state

### ISSUE THREAD

**Issue by ChrisZMF** [apache/kvrocks#504]
**Describe**
If a slave is in full syncing with master, the state can be seen via the item `master_sync_in_progress:1` of info replication. If master is down while slave is fetching SST, the slave will keep retrying connecting with master and the replication state will remain `kReplFetchSST`. The info replication will get `master_sync_in_progress:1`, but it should be `master_sync_in_progress:0`.

OS: all
Version: all

**To Reproduce**
- Start servers A and B
- Write a mount of data to A
- Set B as slave of A and guarantee the full-syncing will be triggered
- Kill A while B is fetching SST

**Expected behavior**
After killing A, check the state master_sync_in_progress on B, it should be `master_sync_in_progress:0`. But `master_sync_in_progress:1` is gotten.

![image](https://user-images.githubusercontent.com/18628342/155937374-113a9b66-dc46-46d4-888c-3676277d3f17.png)

**Comment by git-hulk** [comment]
good catch
