### ISSUE TITLE
[BUG]  kvrocks migrate does not support pasword

### ISSUE THREAD

**Issue by tianshimoyi** [apache/kvrocks#509]
**Describe the bug**
When kvrocks migrate, if the cluster has a password, migrate fails。

 - OS: [e.g. Centos 7]
 - Version [2.0.6]

**To Reproduce**
1. 
![451646291138_ pic](https://user-images.githubusercontent.com/68532999/156516068-d789f428-f7cd-4981-8140-a82fad5e1c2a.jpg)

2.  redis-cli -h $ip -p $port -a $password clusterx migrate $slot $dst_nodeid

**Expected behavior**
migrate should successfully!

![441646291115_ pic](https://user-images.githubusercontent.com/68532999/156516477-05a6dbca-f234-4358-bc9a-506db6c5ae6a.jpg)

**Comment by ChrisZMF** [comment]
Will be supported as soon as possible
