### ISSUE TITLE
[QUESTION]  Does the kvrocks migrate command and setslot command support batch slot operations?

### ISSUE THREAD

**Issue by tianshimoyi** [apache/kvrocks#510]
Are there any plans for the kvrocks migrate command and setslot to develop functionality to support batch slot migration？setslot needs to reset the version for each slot, which will make the version more and more difficult to control in the future.

**Comment by ShooterIT** [comment]
Yes, we have the plan but now we don't have much spare time, may can't support it soon. And current implementation is generally available. Of course, PR is welcome 😜

**Comment by ChrisZMF** [comment]
I will support batch slot operation for command setslot first.

**Comment by tisonkun** [comment]
Closed as stale. You can ask questions at the [Discussions forum](https://github.com/apache/incubator-kvrocks/discussions/categories/q-a).
