### ISSUE TITLE
[QUESTION] how to use supervised

### ISSUE THREAD

**Issue by sjpcg** [apache/kvrocks#512]
I noticed  a **configuration about supervisored** in the config file.But didn't really get it,Does it just like the **supervisored program** which can pulls  the kvrocks process up when it dies for some reason? And if so,how do i use it? Supervisored program need to be installed or  config it only? Thanks

**Comment by git-hulk** [comment]
Yes, the config item `supervised` was used to interact with your supervision tree which means you need to install tools like supervisor or systemd first.
