### ISSUE TITLE
[BUG] Slave can't re-sync with master again after changing password

### ISSUE THREAD

**Issue by ChrisZMF** [apache/kvrocks#513]
**Describe the bug**
If the connection between master and slave is broken (reasons may be network error, restarting master... ) after changing the password of master, the slave can't resynchronize with master again automatically. The resynchronization will fail because slave can't auth master successfully though the `masterauth` of slave is set rightly. It can be resolved by restarting slave with new `masterauth` or execute `slaveof no one` to reset the master-slave relationship.
![image](https://user-images.githubusercontent.com/18628342/156917178-a56aa134-42fc-4e89-9407-a1ca2a9d0ac2.png)

 - OS: all
 - Version: all

**To Reproduce**
1. Sync server B(slave) with server A(master)
2. Set or change `requirepass` of A and `masterauth` of B at the same time
3. Restart master with new password, then slave can't resync with master.

**Expected behavior**
The B(slave) can re-sync with A(master) automatically.

**Reason Analysis**
When slave sync with master, a `ReplicationThread` object will be created and the password of master will be assigned to its member variable `auth_`.  Although the value of `masterauth` is re-assigned, `auth_` will still hold the old value because it can't be re-assigned dynamically.

**Comment by git-hulk** [comment]
cool, can you help to handle this issue? @ChrisZMF

**Comment by ChrisZMF** [comment]
OK, I will fix it soon.
