### ISSUE TITLE
[QUESTION]Compile on ubuntu20.04

### ISSUE THREAD

**Issue by 0xLaiHo** [apache/kvrocks#516]
Build source with the command `make -j4` and got below error:

![image](https://user-images.githubusercontent.com/18321888/157604189-b2d3a5d4-1dfe-4493-b039-2e37ed0eb3c3.png)
![image](https://user-images.githubusercontent.com/18321888/157604434-83e7a9d4-34ed-43c6-a1ef-a87c23b123af.png)

**Comment by git-hulk** [comment]
Do you install dependencies first, seems missing the libtool:

```shell
sudo apt-get install gcc g++ make libsnappy-dev autoconf automake libtool which libgtest-dev
```

**Comment by 0xLaiHo** [comment]
of course,libtool version is 2.4.6,and i try it on another machines,still doesn't work

**Comment by 0xLaiHo** [comment]
> Do you install dependencies first, seems missing the libtool:
> 
> ```shell
> sudo apt-get install gcc g++ make libsnappy-dev autoconf automake libtool which libgtest-dev
> ```

![image](https://user-images.githubusercontent.com/18321888/157802313-f2d9f511-ec1e-4a85-8670-b17f05f24afe.png)

**Comment by git-hulk** [comment]
okay, thanks for your feedback, would have a try on my side soon.

**Comment by git-hulk** [comment]
![image](https://user-images.githubusercontent.com/4987594/157882056-0eaf5458-4668-49e1-b425-68bde850f66b.png)
I have a test on ubuntu 20.04 LTS, it's ok to compile from source. From your feedback, the autoconf did't use the `libtool`, you need to install dependencies before building. You need to check the `libtoolize --version` instead of libtool

**Comment by 0xLaiHo** [comment]
thank u for your help , it's success to compile .

**Comment by git-hulk** [comment]
cool, let's close this issue, welcome to reopen if you have any question or suggestion. Have fun.
