### ISSUE TITLE
[Question] how to get keys num in kvrocks ?

### ISSUE THREAD

**Issue by rfyiamcool** [apache/kvrocks#528]
how to get keys num in kvrocks by redis-cli ? 😁

in kvrocks

```
127.0.0.1:6379> info Keyspace
# Keyspace
```

in redis

```
127.0.0.1:6379> info Keyspace
# Keyspace
db0:keys=6,expires=0,avg_ttl=0
```

**Comment by git-hulk** [comment]
@rfyiamcool Thanks for your attention. Unlike Redis that Kvrocks didn't store keys number directly and it need to background scan the db to get keys number. So we must call `dbsize scan` command first before getting keys num. 

Like below:

```
127.0.0.1:6666> dbsize scan
OK
127.0.0.1:6666> info keyspace
# Keyspace
# Last scan db time: Thu Mar 24 06:38:39 2022
db0:keys=1,expires=0,avg_ttl=0,expired=0
sequence:1
used_db_size:0
max_db_size:0
used_percent: 0%
```

**Comment by rfyiamcool** [comment]
thank u.
