### ISSUE TITLE
[QUESTION] Change the license to Apache License Version 2.0

### ISSUE THREAD

**Issue by ShooterIT** [apache/kvrocks#530]
Hi, all Kvrocks contributors, we want to donate Kvrocks to Apache Software Foundation, the first step for us is changing the license to Apache License Version 2.0. As we know, Kvrocks is an open source software under the BSD-3-Clause license, we truly thank every contributor and user, you guys make Kvrocks great and have an active community, before we could submit PR to change license, we must to get your approval.

@git-hulk @karelrooted @ShooterIT  @Alfejik @caipengbo @ChrisZMF @shangxiaoxiong @ColinChamber @guoxiangCN @calvinxiao @patpatbear @WyattJia @smartlee @popunit @clyang @byronhe @QQxiaoyuyu @nioshield @singgel @liangjingyang @gaoyuanzong @rongzeng54 @unext-ops @fishery86 @xujianhai666 @LykxSassinator 

Please reply "Approved" if you agree.

**Comment by ShooterIT** [comment]
Approved

**Comment by caipengbo** [comment]
Approved

**Comment by WyattJia** [comment]
Approved🎉

**Comment by git-hulk** [comment]
Approved

**Comment by shangxiaoxiong** [comment]
Approved

**Comment by karelrooted** [comment]
Approved

**Comment by ChrisZMF** [comment]
Approved

**Comment by Alfejik** [comment]
Approved

**Comment by xujianhai666** [comment]
Approved

**Comment by ColinChamber** [comment]
Approved

**Comment by LykxSassinator** [comment]
Approved！
LGTM！！！

**Comment by patpatbear** [comment]
Approved

**Comment by liangjingyang** [comment]
Approved

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by unext-ops** [comment]
Approved

**Comment by calvinxiao** [comment]
Approved

**Comment by nioshield** [comment]
Approved🎉🎉🎉

**Comment by singgel** [comment]
Approved

**Comment by mzygQAQ** [comment]
Approved

**Comment by smartlee** [comment]
Approved

**Comment by QQxiaoyuyu** [comment]
Good ,Approved

**Comment by popunit** [comment]
Approved

**Comment by rongzeng54** [comment]
Approved

**Comment by clyang** [comment]
Approved

**Comment by byronhe** [comment]
Approved

**Comment by fishery86** [comment]
Approved

**Comment by gaoyuanzong** [comment]
Approved

**Comment by ShooterIT** [comment]
<img width="287" alt="image" src="https://user-images.githubusercontent.com/18362176/161023393-eaafba35-802a-4ee6-9bd1-8c61168323f1.png">
<img width="322" alt="image" src="https://user-images.githubusercontent.com/18362176/161023533-04d8cb0a-c625-44de-ba62-54f755310263.png">

26 contributors, 26 `Approved`s 🎉

Truly thank all contributors  for approving donating to Apache and changing the license to Apache License Version 2.0.

**Comment by LykxSassinator** [comment]
Approved

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Wang ***@***.***>
发送时间: 2022年3月27日 16:28
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: [KvrocksLabs/kvrocks] [QUESTION] Change the license to Apache License Version 2.0 (Issue #530)


Hi, all Kvrocks contributors, we want to donate Kvrocks to Apache Software Foundation, the first step for us is changing the license to Apache License Version 2.0. As we know, Kvrocks is an open source software under the BSD-3-Clause license, we truly thank every contributor and user, you guys make Kvrocks great and have an active community, before we could submit PR to change license, we must to get your approval.

@git-hulk<https://github.com/git-hulk> @karelrooted<https://github.com/karelrooted> @ShooterIT<https://github.com/ShooterIT> @Alfejik<https://github.com/Alfejik> @caipengbo<https://github.com/caipengbo> @ChrisZMF<https://github.com/ChrisZMF> @shangxiaoxiong<https://github.com/shangxiaoxiong> @ColinChamber<https://github.com/ColinChamber> @guoxiangCN<https://github.com/guoxiangCN> @calvinxiao<https://github.com/calvinxiao> @patpatbear<https://github.com/patpatbear> @WyattJia<https://github.com/WyattJia> @smartlee<https://github.com/smartlee> @popunit<https://github.com/popunit> @clyang<https://github.com/clyang> @byronhe<https://github.com/byronhe> @QQxiaoyuyu<https://github.com/QQxiaoyuyu> @nioshield<https://github.com/nioshield> @singgel<https://github.com/singgel> @liangjingyang<https://github.com/liangjingyang> @gaoyuanzong<https://github.com/gaoyuanzong> @rongzeng54<https://github.com/rongzeng54> @unext-ops<https://github.com/unext-ops> @fishery86<https://github.com/fishery86> @xujianhai666<https://github.com/xujianhai666> @LykxSassinator<https://github.com/LykxSassinator>

Please reply "Approved" if you agree.

―
