### ISSUE TITLE
[QUESTION] Any plan to support Redis Stream?

### ISSUE THREAD

**Issue by aleksraiden** [apache/kvrocks#532]
Hi, do you have any plans to support Redis Stream? That's good for use KVrocks as replacement for message-oriented system. My company is one of the needs of this.
Detailed: 

- [https://redis.io/commands/?group=stream](https://redis.io/commands/?group=stream) 
- [http://antirez.com/news/114](http://antirez.com/news/114)
- [http://antirez.com/news/128](http://antirez.com/news/128)

**Comment by ShooterIT** [comment]
Sorry, currently, we have no plan to implement Redis Stream. Why don't we use kafka?

**Comment by aleksraiden** [comment]
We want to use one and simple storage and in-memory. Kafka is too complicity and for one function need a dedicated system and infrastructure (for us).

**Comment by aleksraiden** [comment]
A small questions - if we are ported a  stream code into KVRocks, are you approve it to merge into release?

**Comment by git-hulk** [comment]
Of course, I think we would be very happy to see this. cc @ShooterIT

**Comment by ShooterIT** [comment]
Why not! for some features that redis has, we don't have enough time to implement it, it will be our pleasure if someone could push it forward.

**Comment by seaguest** [comment]
@aleksraiden 

FYI, [NATS](https://github.com/nats-io/nats-server) is a good alternative of Kafka, lightweight and easy to run, it does support persistence in JetStream mode.

**Comment by aleksraiden** [comment]
WE start implements this feature after porting LMOVE command :) in first release we have a plan to implement a base functions, withoit consumers group

**Comment by aleksraiden** [comment]
Please, help us - review and comment: https://github.com/apache/incubator-kvrocks/pull/745

**Comment by aleksraiden** [comment]
A lot of thanks @torwig
