### ISSUE TITLE
clear  call

### ISSUE THREAD

**Issue by liuqian1990** [apache/kvrocks#549]
`String::getValue value->clear();`  call clear
`String::getValues` not all clear

**Comment by git-hulk** [comment]
Thanks @liuqian1990 feedback. 

The String::getValues also clears the input values when calling the function `getRawValues`.

**Comment by liuqian1990** [comment]
`function getRawValue also call clear`

**Comment by liuqian1990** [comment]
`rocksdb::Status String::getRawValue(const std::string &ns_key, std::string *raw_value) {raw_value->clear();`

**Comment by git-hulk** [comment]
Sorry that I didn't get what your mean. Do you find any problems?
