### ISSUE TITLE
[QUESTION]rocksdb is stored in key order, supports range api, redis does not support

### ISSUE THREAD

**Issue by melin** [apache/kvrocks#552]
rocksdb is stored in key order, supports range api, redis does not support

**Comment by caipengbo** [comment]
Kvrocks supports rich Redis data types, some of which support range related APIs, like `zrange`, `lrange` etc, which you can find [here](https://github.com/apache/incubator-kvrocks/wiki/Support-Commands). Kvrocks implements the above APIs based on the rocksdb range APIs.

**Comment by tisonkun** [comment]
Closed as stale. You can ask questions at the [Discussions forum](https://github.com/apache/incubator-kvrocks/discussions/categories/q-a).
