### ISSUE TITLE
Remove unused and misleading variable `kDefaultConfPath`

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#559]
https://github.com/apache/incubator-kvrocks/blob/a5a5434a93388137be640c55b5440a66f42e1659/src/main.cc#L48

It seems we don't actually load config from `../kvrocks.conf` if `-c` is not specific.

cc @git-hulk @ShooterIT

**Comment by git-hulk** [comment]
Yes, u are right. It won't use this default config path any more.

**Comment by ShooterIT** [comment]
Current solution is not a good idea. But i think kvrocks should provide a way to start without conf file. i.e. without `-c xxx.conf`, this makes it easy to try.

**Comment by git-hulk** [comment]
@ShooterIT Kvrocks had supported that, so the default path was unused actually.

**Comment by tisonkun** [comment]
I'm going to prepare a patch to remove related code later today :)

**Comment by tisonkun** [comment]
FYI I record the experience to solve this issue on bilibili: https://www.bilibili.com/video/BV1w54y1Z7VP/

It may be a content to show how to participant Kvrocks community :)
