### ISSUE TITLE
Adopt issue template configs

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#560]
So far, we use GitHub legacy markdown format for issue template. However, GitHub provides a new [config feature for setting up issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).

Also, we'd better keep bug report and enhancement while guiding questions to mailing list and/or Discussions. We can make use of https://github.com/apache/skywalking/tree/master/.github/ISSUE_TEMPLATE.

If you like this idea, I can provide a patch in days.

cc @git-hulk @ShooterIT @karelrooted

**Comment by git-hulk** [comment]
+1, really cool.

**Comment by ShooterIT** [comment]
cool, thanks!
