### ISSUE TITLE
[QUESTION] Consider reintroducing googletest to cmake dependencies?

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#561]
The current `cmake/gtest.cmake` is confusing, especially since it contains a directory on [line 38](https://github.com/apache/incubator-kvrocks/blob/cf9901f88f5905f75e542999529fcbad2ec66dd1/cmake/gtest.cmake#L38) that does not exist, so this file does not seem to provide any functionality.

The project uses the system-supplied gtest, which makes it difficult to control its version. It also seems that the project does not use mechanisms such as `find_package` for gtest, but relies directly on the system header directory (e.g. `/usr/include` to find `gtest/gest.h`) and the `-lgtest` link option.

I think it would be better to reintroduce googletest with fixed tag/commit hash at the cmake level (source level) using `ExternalProject` or `FetchContent`. Since gtest doesn't have many translation units, it doesn't take long to compile.

I'm happy to provide PRs if that sounds like a good idea.

@tisonkun

**Comment by git-hulk** [comment]
+1, other guys also suffered this problem, I think we can reintroduce `gtest` to make the build process easier.

**Comment by ColinChamber** [comment]
By the way could you help to finish this PR #525 ? I'm sorry I don't have the time currently. Thanks @PragmaTwice

**Comment by git-hulk** [comment]
@ColinChamber we can delay this PR since glog0.5 remove the autoconf which would
break the makefile.

**Comment by ColinChamber** [comment]
OK

**Comment by PragmaTwice** [comment]
Solved in #564
