### ISSUE TITLE
[QUESTION] About compile option `-O0` in the cmake target `kvrocks`

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#563]
The `-O0` option currently added to target `kvrocks` in [CMakeLists.txt](https://github.com/apache/incubator-kvrocks/blob/unstable/CMakeLists.txt#L85) is confusing, as it may prevent compilation optimizations in Release mode.

The performance impact of compile optimizations can be huge, especially with heavy use of the c++ standard library, where optimized versions can be tens of times faster than unoptimized versions.

Were there any special considerations for adding `-O0` at that time?

**Comment by git-hulk** [comment]
Thanks @PragmaTwice 

No special consideration, we set it as O0 to make the debug easier.
I also agree it's a good idea to change it to `O2`.
