### ISSUE TITLE
Proposal: add multiple platforms and CPUs build workflow in GitHub Actions

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

As far as I know, Kvrocks works well on platforms like CentOS/Ubuntu/Debian and MacOSX, as well as CPU like ARM64 and Apple M1. But we didn't check the build system status now and we can't guarantee it's always fine over time. So I think we should check those statuses periodically.

### Solution

For most PRs won't affect the build system status, but it's a bit time and resource costly. The workaround is to check daily or weekly instead of every PR, and we can fix them in time when anyone was broken. Do you guys have any thoughts? 

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
IIRC [GitHub Actions doesn't provide hosted ARM64 machine](https://github.community/t/ask-about-github-hosted-runners-arm64-platform-support/167483) ([another instance](https://issues.apache.org/jira/browse/CURATOR-634)). We may need a sponsor for self-hosted runners, other CI platform or ask ASF Infra for more information.

**Comment by git-hulk** [comment]
Thanks @tisonkun.

Another solution can run those ARM64 jobs on Travis CI, but I'm wondering whether it makes sense or not.

**Comment by tisonkun** [comment]
Closed as now we're using Travis to achieve multiple platform supports. If GitHub Actions support ARM platform later, we can review this proposal.
