### ISSUE TITLE
Proposal: Remove handwritten makefiles to keep only one build system

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#574]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

As already discussed in https://github.com/apache/incubator-kvrocks/issues/562, https://github.com/apache/incubator-kvrocks/pull/564 and https://github.com/apache/incubator-kvrocks/pull/566, remove handwritten makfiles allow us to focus on improving CMake builds and reduce maintenance costs. CMake is a build system (generator) with a higher level of abstraction than makefiles, which can describe the build structure and hierarchy of a project in a more convenient form.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
+1
