### ISSUE TITLE
Improve `version.h.in` processing in CMake

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Now the generated version.h by CMake is not comsistent with the previous Makefiles.
The version is now set in [CMakeLists.txt#L20](https://github.com/apache/incubator-kvrocks/blob/unstable/CMakeLists.txt#L20), we can remove it and read version in the Changelog file, so we do not need to change CMakeLists while a new version is released.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
+1
