### ISSUE TITLE
Improve using of ASan and TSan in CMake build

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#590]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

As discussed in #586, we can improve using of ASan and TSan in the CMake build.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ShooterIT** [comment]
cool, thanks, l like this idea. And we can also run tests with ASan and TSan in daily CI.
