### ISSUE TITLE
[NEW] add lz4 lib

### ISSUE THREAD

**Issue by xiaobiaozhao** [apache/kvrocks#601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

KVrocks not included lz4 lib for lz4 compresssion. Only snappy is not enough，lz4 is a  efficient algorithm.

https://user-images.githubusercontent.com/52393536/168716155-82a51edf-74df-48e5-b047-f4e05a192719.png

### Solution

1. Add lz4 lib into build file.
2. Add conf for rocksdb.compression "lz4"

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Cool, agreed.

the compression ration and performance are better than `snappy`
in many scenarios. Someone also requests this feature if my memory serves.
