### ISSUE TITLE
Change the unit of the rocksdb options

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#612]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

PR https://github.com/apache/incubator-kvrocks/pull/497 and https://github.com/apache/incubator-kvrocks/pull/503 allowed changing the rocksdb options `blob_file_size` and `max_bytes_for_level_base` in-flight. But from the literal, we would think that the unit of these two configurations should be bytes(like `max_bytes_for_level_base`), but in fact was MiB. So it should be a good idea to change them with the right unit, this will NOT break the behavior  since we didn't release those features yet.

### Solution

Change the unit of `max_bytes_for_level_base` and `blob_file_size` to bytes in the configuration file.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by WyattJia** [comment]
And about max_bytes_for_level configuration's change, I opened another PR on #610 ,please review and thanks.
