### ISSUE TITLE
Enhancement: support Ninja as a CMake backend

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#621]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

CMake support Ninja (`-G Ninja`) as a build tools to generate, just like Makefiles, which provides more efficient build processing.
But there are some problem in current CMake configurations in kvrocks so we cannot use it.

I will investigate it and make a fix.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Agree. ClickHouse using ninja as the default build system and it does speed up the process.

When you prepare a patch, it'll be valuable to provide a report on the improvement by changing build system. Otherwise we may not make such switch without a clear motivation.

**Comment by PragmaTwice** [comment]
> Agree. ClickHouse using ninja as the default build system and it does speed up the process.
> 
> When you prepare a patch, it'll be valuable to provide a report on the improvement by changing build system. Otherwise we may not make such switch without a clear motivation.

My idea is to make ninja an option for build, e.g. specify `--ninja` (`./build.sh build --ninja`) to use ninja, otherwise (the default behavior is) use make, and because CMake already supports Ninja so only a few fixes are needed, not too many changes.
I will make a benchmark between make and ninja for kvrocks to test whether ninja speed up the build.
