### ISSUE TITLE
Enhancement: Support GitHub mirrors in CMake build configurations

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#622]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

GitHub has some access issues in some countries (connection resets or slow speeds), 
so we can support custom URL of dependencies in CMake configurations, such as `ghproxy.com`, 
which will speed up build procedure, e.g. `./build.sh build -DGITHUB_PROXY=https://ghproxy.com`.

**NOTICE: we may need to add SHA verification of fetched files to ensure that users are not vulnerable to MITM attacks by public proxy providers if we decide to add this feature.**

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Sounds reasonable :)
