### ISSUE TITLE
Improve website logo asset

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#623]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

![image](https://user-images.githubusercontent.com/18818196/172305964-987626d6-f547-4f12-af54-0a7d530e38d2.png)

> > @git-hulk the logo svg and favicon isn't quite good-look, though. I'm unfamiliar with draw a logo and maybe you can help on creating a better version.
> 
> OK, I'm also unfamiliar with that. Will contact the original designer to help.

Originally posted at https://github.com/apache/incubator-kvrocks-website/pull/5#issuecomment-1147160341.

cc @git-hulk

**Comment by git-hulk** [comment]
Thanks @tisonkun, the original designer has helped to update the logo, will submit soon.

**Comment by git-hulk** [comment]
@tisonkun can have a look at https://kvrocks.apache.org/, if looks good then we can close this issue.

**Comment by tisonkun** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18818196/172497252-ed83458c-af17-49f3-8501-3ef3534335a1.png">

It looks pretty better! Closed.
