### ISSUE TITLE
Track failed frequently integration test cases

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

As mentioned in https://github.com/apache/incubator-kvrocks/pull/646#issuecomment-1162660044, some integration test cases failed frequently
which may frustrate and confuse contributors, so I think we can find out
and disable them from old runs.

### Solution

- [x] Find out all failure frequently cases from old runs and fix them

### Replication Related

- [x] #655
- [x] #656
- [x] #676

### Cluster Related
- [x] #657

### Commands
- [x] #658

**Comment by tisonkun** [comment]
You may give a report (sheet) for flaky tests, sorting out by categorizes. For example, tcl tests or unit tests.

It should be helpful for anyone who tries to contribute to stabilize tests.

**Comment by git-hulk** [comment]
> You may give a report (sheet) for flaky tests, sorting out by categorizes. For example, tcl tests or unit tests.
> 
> It should be helpful for anyone who tries to contribute to stabilize tests.

Good point, all cases are from tcl tests. I will find them all recently and group them together.

**Comment by git-hulk** [comment]
@tisonkun I found most failures were caused by four tcl test cases，should we create issue for each one to track them?
<img width="736" alt="image" src="https://user-images.githubusercontent.com/4987594/175474994-58b7cb7a-d89c-48f3-bae8-72e024e14ba8.png">

**Comment by tisonkun** [comment]
@git-hulk yes. We can create subtasks for them. Basically we create issue if someone volunteer to investigate (otherwise we create dangling issues), and it happens I'll give a look at these cases :)

**Comment by git-hulk** [comment]
> @git-hulk yes. We can create subtasks for them. Basically we create issue if someone volunteer to investigate (otherwise we create dangling issues), and it happens I'll give a look at these cases :)

OK, will create issues later.

**Comment by tisonkun** [comment]
@git-hulk I've created them.

**Comment by git-hulk** [comment]
Many thanks!

**Comment by tisonkun** [comment]
@git-hulk all previous subtasks resolved. However, there is a new failure #676 detected :/

**Comment by git-hulk** [comment]
> @git-hulk all previous subtasks resolved. However, there is a new failure #676 detected :/

Got it, thanks @tisonkun. I will follow up and try to figure out the root cause.

**Comment by PragmaTwice** [comment]
```
*** [err]: Set instance A as slave of B in tests/integration/replication.tcl
Expected '1' to be equal to '0' (context: type source line 41 file /Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/tcl/tests/integration/replication.tcl cmd {assert_equal {1} [s -1 loading]} proc ::test)
*** [err]: requests on cluster are ok in tests/integration/cluster.tcl
Expected '16383' to be equal to '' (context: type source line 257 file /Users/runner/work/incubator-kvrocks/incubator-kvrocks/tests/tcl/tests/integration/cluster.tcl cmd {assert_equal "16383" [$r3 get $slot_16383_key]} proc ::test)
```
in https://github.com/apache/incubator-kvrocks/runs/7096118532?check_suite_focus=true

**Comment by tisonkun** [comment]
Closed as all subtasks done.

**Comment by git-hulk** [comment]
👍 Really great work, it's really to debug the flaky tests now.
