### ISSUE TITLE
Executing test client: LOADING kvrocks is restoring the db from backup

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#655]
Report: https://github.com/apache/incubator-kvrocks/runs/7026847364?check_suite_focus=true#step:10:713

**Comment by git-hulk** [comment]
I will follow up this issue, it should be caused by forbidding to get role when restoring
the data.

**Comment by PragmaTwice** [comment]
There is another fail with same exception: https://github.com/apache/incubator-kvrocks/runs/7085774273?check_suite_focus=true
But I feel that the root cause of this error and the above error may be different, because the execution path seems to be different.

**Comment by git-hulk** [comment]
Looks caused by this line: [replication.tcl#L196](https://github.com/apache/incubator-kvrocks/blob/unstable/tests/tcl/tests/integration/replication.tcl#L196), need to wait for restoring. Will fix it later.
