### ISSUE TITLE
Migrate incremental data via parsing and filtering data

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#657]
Report https://github.com/apache/incubator-kvrocks/runs/7034653085?check_suite_focus=true#step:10:687

**Comment by git-hulk** [comment]
This test case spent almost 30s on my local machine and it should be even slower in CI environment. So we can increase the wait time from 50s => 100s if has no idea. Do guys
have any thoughts about this case? @ChrisZMF @ShooterIT @caipengbo

**Comment by tisonkun** [comment]
It's a valid workaround. However, it's better to make the waiting determinately - is it possible?

**Comment by git-hulk** [comment]
> It's a valid workaround. However, it's better to make the waiting determinately - is it possible?

Yes, can check the migrate finished status which we're doing at line: [slotmigrate.tcl#L513](https://github.com/apache/incubator-kvrocks/blob/e2640f8e4297311dae1dabec76b203ded31b4aaf/tests/tcl/tests/integration/slotmigrate.tcl#L513), we can remove the time limit.

**Comment by git-hulk** [comment]
@tisonkun removed the time limit, can help to take a look again.

**Comment by caipengbo** [comment]
Is there any way we can reduce the waiting time?  I think this test case is taking too long.

**Comment by git-hulk** [comment]
Maybe we can test whether increase the pipeline size can help or not
