### ISSUE TITLE
get rocksdb ops by COMMAND INFO in tests/unit/command.tcl [expr abs($cmd_qps - $put_qps)] < 10

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#658]
Report: https://github.com/apache/incubator-kvrocks/runs/6453256361?check_suite_focus=true#step:7:2018

**Comment by caipengbo** [comment]
Let me track this problem.

**Comment by git-hulk** [comment]
@caipengbo I took a look at this test case and those metrics would be affected by other test cases, maybe we should change the test case to avoid that.

**Comment by caipengbo** [comment]
> I took a look at this test case and those metrics would be affected by other test cases, maybe we should change the test case to avoid that.

Yeah, it should be the effect of previous OPS, how about wait a little longer to let QPS empty? @git-hulk

**Comment by git-hulk** [comment]
Another workaround can be also fetching those metrics before running `lpush` and `lrange` command, then fetch and compare the diff value. So that we can make sure the metrics would affected by current test case only. How do you think? @caipengbo

**Comment by caipengbo** [comment]
That sounds good!

**Comment by caipengbo** [comment]
I looked again, and it didn't seem to be the influence of the previous OPS;  I took a look at this failed case：https://github.com/apache/incubator-kvrocks/runs/6453256361?check_suite_focus=true#step:7:2018, it show only 432 OPS. But theoretically, OPS should be 1000, the gap is too large. 

My guess is that tcl `after` statement is too short to be accurate in CI environments, HDYT @git-hulk

**Comment by git-hulk** [comment]
It's expected since we used time based metrics instead of counter: https://github.com/apache/incubator-kvrocks/blob/0b2de8ab6f661d90a279a0c11096755d7733b11c/src/stats.cc#L108

So ops can be affected by the elapsed time, I think it's too long instead of too short?
