### ISSUE TITLE
Add a label to trigger daily CI in PR

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#665]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

We could add a label like `need-daily-CI`, and when the label is applied to a PR, all jobs of daily CI will join in the checking sequence of this PR.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
cc @Xuanwo IIRC you have the knowledge to implement this requirement. Would you like to take over this issue or help on sharing knowledge need to implement this feature?

**Comment by tisonkun** [comment]
Actually since we already trigger daily CI if workflow file changed, I'm thinking of whether we can implement this as simple as adding a comment line in the workflow file and change that line to trigger it in PR.

```yaml
# This line is to trigger CI in pull request by changing the digest to any other random value; digest: 1096
```

cc @GoGim1

**Comment by PragmaTwice** [comment]
> Actually since we already trigger daily CI if workflow file changed, I'm thinking of whether we can implement this as simple as adding a comment line in the workflow file and change that line to trigger it in PR.
> 
> ```yaml
> # This line is to trigger CI in pull request by changing the digest to any other random value; digest: 1096
> ```
> 
> cc @GoGim1

I think it is more like a workaround rather than a solution 🤣

**Comment by tisonkun** [comment]
Fair enough. It's possible to implement this feature with label changed.
