### ISSUE TITLE
Executing test client: I/O error reading reply.

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#676]
Report: https://github.com/apache/incubator-kvrocks/runs/7060886256?check_suite_focus=true

**Comment by PragmaTwice** [comment]
and https://github.com/apache/incubator-kvrocks/runs/7052214974?check_suite_focus=true

**Comment by tisonkun** [comment]
cc @ShooterIT since you ported these tests into Kvrocks, would you like to investigate the root cause of this error? It seems far more general to debug without more backgorund.

**Comment by ShooterIT** [comment]
copy that, i will have a look.

**Comment by ShooterIT** [comment]
> Report: https://github.com/apache/incubator-kvrocks/runs/7060886256?check_suite_focus=true

This may be resolved by #688 

> and https://github.com/apache/incubator-kvrocks/runs/7052214974?check_suite_focus=true

I don't find its clue🙃

**Comment by PragmaTwice** [comment]
another example: https://github.com/apache/incubator-kvrocks/runs/7093289052?check_suite_focus=true

**Comment by tisonkun** [comment]
Closed as invalid anymore. Also, we are migrating tests to Go cases and will fix further issues there https://github.com/apache/incubator-kvrocks/issues/811 potentially.
