### ISSUE TITLE
Exclude unstable branch while canceling previous workflows

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

![image](https://user-images.githubusercontent.com/20042607/175820242-e318efaa-3b18-4cfa-a235-ec3caba21e10.png)

As shown in the figure above, the retrying workflow was canceled due to a new commit.
We may retry the kvrocks ci action of some commits in the unstable branch. 
At this time, if the unstable branch can only run one workflow at the same time, it will cause some trouble.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
I don't think this is a big deal. Always we focus on the latest version and it's fine if only the nightly version passes CI.

If you want to debugging an unstable test, you may open a branch on fork or send a draft pull request.

**Comment by PragmaTwice** [comment]
> I don't think this is a big deal. Always we focus on the latest version and it's fine if only the nightly version passes CI.
> 
> If you want to debugging an unstable test, you may open a branch on fork or send a draft pull request.

In fact, there is another situation. 

For example, if two commits are merged into the unstable branch within a short time interval, the workflow of the previous commit will be canceled, and the actions status of the previous commit will display a ❌.

This can lead users to think that our unstable branch will often fail, which may not be what we expected, and this situation may be more serious than the one above.

**Comment by tisonkun** [comment]
@PragmaTwice since we require every PR should be up-to-date before merge, actually we can skip running CI in `unstable` branch.

See also [Apache Pulsar's CI settings](https://github.com/apache/pulsar/blob/6c715e08c67c40221c8c08cbe0b31d3a6aa1bf32/.github/workflows/pulsar-ci.yaml):

```yaml
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - branch-*
```

**Comment by PragmaTwice** [comment]
> @PragmaTwice since we require every PR should be up-to-date before merge, actually we can skip running CI in `unstable` branch.
> 
> See also [Apache Pulsar's CI settings](https://github.com/apache/pulsar/blob/6c715e08c67c40221c8c08cbe0b31d3a6aa1bf32/.github/workflows/pulsar-ci.yaml):
> 
> ```yaml
> on:
>   pull_request:
>     branches:
>       - master
>   push:
>     branches:
>       - branch-*
> ```

Good idea, actually I think maybe we can use another workflow on unstable branch to build and test kvrocks with more environment and build options than the current workflow trigger by PRs.

**Comment by tisonkun** [comment]
@PragmaTwice it sounds like something similar to "MergeCI" in TiDB project. However, I'd prefer running tests as early as possible instead of running less tests and fix bugs later.
