### ISSUE TITLE
Review build docker image CI task which takes more than 2 hours to finish

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#691]
@git-hulk @ShooterIT @PragmaTwice Perhaps we can move build and test tasks from daily CI to per PR CI. They take less than half hour to finish. While building docker image takes more than 2 hours to finish and I'm curious why.

_Originally posted by @tisonkun in https://github.com/apache/incubator-kvrocks/issues/689#issuecomment-1169606788_

**Comment by tisonkun** [comment]
> @git-hulk @ShooterIT @PragmaTwice Perhaps we can move build and test tasks from daily CI to per PR CI. They take less than half hour to finish. While building docker image takes more than 2 hours to finish and I'm curious why.

Maybe it is due to that we use QEMU to simulate an arm64 environment, and I think that is slow.

_Originally posted by @PragmaTwice in https://github.com/apache/incubator-kvrocks/issues/689#issuecomment-1169609906_

@PragmaTwice thanks for your input. Another approach is still run more Build and Test tasks every day but separate docker job into another workflow.

_Originally posted by @tisonkun in https://github.com/apache/incubator-kvrocks/issues/689#issuecomment-1169611332_

Another thing is that since we build the nightly version of the docker image we can automatically publish it to some registries like the docker hub, e.g. some tags like `nightly`, `nightly-20220629`.

And I also think building docker image in CI triggered by PRs is unnecessary (maybe an arm evironment is useful, but a docker environment is not necessary for build and test).

_Originally posted by @PragmaTwice in https://github.com/apache/incubator-kvrocks/issues/689#issuecomment-1169614450_

> Another thing is that since we build the nightly version of the docker image we can automatically publish it to some registries like the docker hub, e.g. some tags like `nightly`, `nightly-20220629`.
> 
> And I also think building docker image in CI triggered by PRs is unnecessary (maybe an arm evironment is useful, but a docker environment is not necessary for build and test).

Good point that we can push the `nightly` docker image, latest image need to wait for the new release is too slow for most users.

_Originally posted by @git-hulk in https://github.com/apache/incubator-kvrocks/issues/689#issuecomment-1169619824_

**Comment by git-hulk** [comment]
The QEMU was introduce in PR: https://github.com/apache/incubator-kvrocks/pull/550, maybe we can move other jobs to per CI from daily CI except the QEMU docker image.

**Comment by PragmaTwice** [comment]
> Another thing is that since we build the nightly version of the docker image we can automatically publish it to some registries like the docker hub, e.g. some tags like `nightly`, `nightly-20220629`.

I will open a seperate issue for this : )

**Comment by PragmaTwice** [comment]
For the arm related issue, I wonder whether we can find a (native) arm64 enviroment on other CI platforms like Circle CI, which maybe more fast than the QEMU way. Any comments? @git-hulk @tisonkun

**Comment by git-hulk** [comment]
This sounds good to me, it's really frustrated to debug the daily CI now.

**Comment by tisonkun** [comment]
@PragmaTwice That's possible. You may start a discussion on dev@ and we'll ask ASF INFRA team to enable related integration.

**Comment by PragmaTwice** [comment]
> @PragmaTwice That's possible. You may start a discussion on dev@ and we'll ask ASF INFRA team to enable related integration.

Thanks, I will start a discussion later.

**Comment by tisonkun** [comment]
@PragmaTwice @git-hulk I write a patch to separate daily CI and run daily CI iff `needs-daily-ci` labeled. You may give it a look https://github.com/apache/incubator-kvrocks/pull/695.

For ARM64 issue, I'm actually wonder whether we should build an image on ARM64.
