### ISSUE TITLE
Enhancement: trying to reduce calling to `GetCurrentTime()` when not neccessary

### ISSUE THREAD

**Issue by mapleFU** [apache/kvrocks#708]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

`Metadata::TTL()` and `Metadata::Expired()` will call `rocksdb::Env::Default()->GetCurrentTime(&now)` every time we called it. rocksdb's `GetCurrentTime` will ask time on OS, and mostly it will be a vdso call and may take about 10ns to get the current time.

But sometimes we don't need to call it here. If `expire == 0`, just return without `GetCurrentTime` is ok.

By the way, I'm confused that when would `expire` less than 0? Can some one helps me find out why?

### Solution

remove `GetCurrentTime` when not neccessary.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@mapleFU `expire` should be never less than 0, so it's good to reduce the `GetCurrentTime` function call when expire is zero.

**Comment by PragmaTwice** [comment]
Solved in #709.
