### ISSUE TITLE
Build docker image with Travis CI

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

#550 introduces a CI task to build docker image, especially including build on ARM64 which is simulated via QEMU. This task generally takes more than 2 hours to complete and we currently have to run it daily in a dedicate job.

GitHub Actions support only x86 arch at the moment, and among CI platforms ASF provides, Travis CI seems a good fit to run CI tasks on other arches including ARM64. [I ask INFRA how to configure Travis CI settings](https://issues.apache.org/jira/browse/INFRA-23444), and the answer is directly pushing a `.travis.yml` file to the root path.

IIRC @git-hulk @PragmaTwice show your interests in this topic before, you may take a look and give it a try. I may find sometime later this month to give it a try if nobody moves forward.

cc @foxdalas as the original author of #550.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
Perhaps useful references:

* https://docs.travis-ci.com/user/docker/
* https://docs.travis-ci.com/user/installing-dependencies/
* https://docs.travis-ci.com/user/languages/cpp/

**Comment by PragmaTwice** [comment]
https://docs.travis-ci.com/user/cron-jobs/

Seems cron jobs in Travis CI can only be set on web UI rather than `.travis.yml`, which maybe more hard since we have no permission to access Travis web UI of the Apache org.

**Comment by tisonkun** [comment]
@PragmaTwice currently, we run docker build daily due to it's slow. If using travis we can finish the task within an hour, we can run the task per PR. For cron settings, you can comment at the JIRA ticket, asking the best practice from INFRA team.

**Comment by PragmaTwice** [comment]
Thanks. I think it maybe unnecessary to build docker images for every commit in a PR: we've fully tested them in other workflows. I think we can consider building docker images for each new commit in the unstable branch and release it as a nightly version (of course we can do some pruning when releasing to ensure that only one nightly image is released per day)

**Comment by tisonkun** [comment]
> building docker images for each new commit in the unstable branch and release it as a nightly version

That's possible. Actually SkyWalking provides such features along with GitHub Packages (https://github.com/orgs/apache/packages?repo_name=skywalking). Also they support build on ARM64 arch while doesn't involve Travis CI dependency. It should be worth to investigate.

cc @kezhenxu94 could you share some background how SkyWalking implements the workflow here?

**Comment by kezhenxu94** [comment]
Personally I'd prefer GitHub Actions over Travis CI as GHA is integrated smoothly in terms of development experience, and you don't need to ask Apache infra team to provide token and configure them in Travis CI (this is usually forbidden by infra team for the sake of security).

> Thanks. I think it maybe unnecessary to build docker images for every commit in a PR: we've fully tested them in other workflows.

I agree we don't need to build Docker images in every commit **in a PR**, not to say pushing/publishing to GitHub Container Registry, ghcr,

> I think we can consider building docker images for each new commit in the unstable branch and release it as a nightly version (of course we can do some pruning when releasing to ensure that only one nightly image is released per day).

In SkyWalking, we build and push a Docker image for every commit in the `master` branch, tagged with the commit hash as well as the `latest` tag, so we'd recommend testers (not users) to use the `:latest` tag when they want to try something new, or help to test the latest codes.

Also, to build multi-arch Docker images, you actually don't need an ARM-arch machine, by leveraging qemu and Docker build kit you can cross build Docker images for all architectures https://github.com/apache/skywalking/blob/47cc2f7bb99fefda37a3adcc85206e1743d32757/.github/workflows/publish-docker.yaml#L55-L58

And to just build for every commit in `master` branch, just set the `on` condition to `branch.master` so the workflow won't be triggered in PR commits

https://github.com/apache/skywalking/blob/47cc2f7bb99fefda37a3adcc85206e1743d32757/.github/workflows/publish-docker.yaml#L19-L22

All the works 👆 can be done on your own, without asking apache infra team to configure tokens, which is impossible in Travis CI.

**Comment by kezhenxu94** [comment]
I think you already have the workflow https://github.com/apache/incubator-kvrocks/blob/c094ea46ae500169dcc3e9b3b28ee6c47ea098bc/.github/workflows/release.yaml#L82-L94 so you only need to add a trigger condition when pushed to main branch.

**Comment by tisonkun** [comment]
@kezhenxu94 the main argument about using QEMU for kvrocks is that it takes over 2 hours to complete, while I can see that the SkyWalking job take ~20 mins to complete. I have no idea yet how can kvrocks build behaves so different. Perhaps jar files are platform-agnostic so that you can simply copy the generated file into the image, while we should build kvrocks from scratch on ARM64 platform - each inst emitted by QEMU and it's slow.

**Comment by kezhenxu94** [comment]
From [the logs](https://github.com/apache/incubator-kvrocks/runs/7206849766?check_suite_focus=true#step:6:4651) I can see the time in building ARM Docker image dominates (~2 hours), and [the time in building AMD image is about 20 minutes](https://github.com/apache/incubator-kvrocks/runs/7206849766?check_suite_focus=true#step:6:4150). I remember it indeed takes longer time to build ARM compared to AMD when I tried to build ARM Docker images for apache/pulsar, which includes some C++ codes for their C++ client.

> Perhaps jar files are platform-agnostic so that you can simply copy the generated file into the image

I agree this might be the main reason

**Comment by PragmaTwice** [comment]
In this workflow run https://github.com/apache/incubator-kvrocks/runs/7206849766?check_suite_focus=true, we can see

build kvrocks on native amd64: 1161.3s ~ 20 min
build kvrocks on QEMU arm64 : 7678.7s ~ 2h 8min

more than x6 times longer in QEMU simulation, it is frustrating 😢

**Comment by git-hulk** [comment]
I'm wondering whether builds the arm64 only in QMEMU can reduce the cost time or not, and
build the amd64 in previous way.

**Comment by foxdalas** [comment]
You can use cross-compiling and just copy binary inside arm-based container. It will be faster

**Comment by PragmaTwice** [comment]
> You can use cross-compiling and just copy binary inside arm-based container. It will be faster

Thanks. I think it is a greate idea, but I do not know if it will be more complicated than the travis ci way.

Maybe need some trying.

**Comment by tisonkun** [comment]
You can review #724 for an attempt.
