### ISSUE TITLE
set command is inconsistent with redis 

### ISSUE THREAD

**Issue by caipengbo** [apache/kvrocks#727]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.0.6

### Minimal reproduce step

```
kvrocks:6666> set key value ex 1000 px 2
OK

kvrocks:6666> set key value ex 1000xyz
OK
```
But in redis:
```
redis:6379> set key value ex 1000 px 2
(error) syntax error

redis:6379> set key value ex 1000xyz
(error) value is not an integer or out of range
```

### What did you expect to see?

The set command should be the same as [redis](https://redis.io/commands/set/).

### What did you see instead?

Can set new data using incorrect syntax.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Has something in common with #456.


```
set key value ex 1000xyz
```
I think this is because we are using functions like `stoi` directly without using parse techniques for error handling.

I proposed a unified abstraction in #598 to better parse redis commands and solve all these problem.  But I haven't taken the time to implement them.

**Comment by caipengbo** [comment]
> I proposed a unified abstraction in https://github.com/apache/incubator-kvrocks/issues/598 to better parse redis commands and solve all these problem. But I haven't taken the time to implement them.I proposed a unified abstraction in https://github.com/apache/incubator-kvrocks/issues/598 to better parse redis commands and solve all these problem. But I haven't taken the time to implement them.

Yes, it may be a big change, and it may take a long time.  

However, `set` command is a very common command, and I thought it would be a simple matter to fix it first.
