### ISSUE TITLE
Test case failed occasionally in `test/unit/expire.tcl` 

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#742]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Check expire at test case failed occasionally, we should fix it to make the CI happy.

```
*** [err]: EXPIREAT - Check for EXPIRE alike behavior in tests/unit/expire.tcl
Expected '1[345]' to equal or match '16'
Error: Process completed with exit code 1.
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
```
*** [err]: PERSIST can undo an EXPIRE in tests/unit/expire.tcl
Expected '50 1 -1 foo' to equal or match '49 1 -1 foo'
```

Another failure in `expire.tcl`: https://github.com/apache/incubator-kvrocks/runs/7450339994?check_suite_focus=true

**Comment by git-hulk** [comment]
Thanks @PragmaTwice, also fixed it by add some tolerant range.
