### ISSUE TITLE
The atoi exception was not caught

### ISSUE THREAD

**Issue by Ranxy** [apache/kvrocks#766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

There is some code in the project as follows
```cpp
try {
        slot_ = atoi(args[2].c_str());
        dst_node_id_ = args[3];
      } catch (std::exception &e) {
        return Status(Status::RedisParseErr, errValueNotInterger);
      }
```
However `atoi` does not throw exceptions, so perhaps we should use `std::stoi` to replace these.

### Solution

Replace `atoi` to `std::stoi`

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Good catch, I think we can use `Util::OctalStringToNum` to replace the `atoi` which also can check the min/max boundary.
