### ISSUE TITLE
[feature] Support key expire listener

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/kvrocks#769]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Support key expire listener.

```
192.168.3.228:6666> config set notify-keyspace-events AE
(error) CONFIG SET 'notify-keyspace-events' error: Unsupported CONFIG parameter: notify-keyspace-events
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by w4096** [comment]
@liangyuanpeng   kvrocks doesn't support keyspace notify yet.

**Comment by git-hulk** [comment]
> @liangyuanpeng kvrocks doesn't support keyspace notify yet.

It should be NOT easy to implement this feature for Kvrocks since
its data are kept in disk, so we have no way to figure out which entries
are expired except scanning the DB.

**Comment by tisonkun** [comment]
Closed as no clear plan and the author doesn't propose a design.
