### ISSUE TITLE
Report a failure fast if `CMAKE_OSX_DEPLOYMENT_TARGET` unset on MacOS

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#776]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

See also https://github.com/apache/incubator-kvrocks/commit/341a989d75783d8dad76bbd5a4473dd345472337#r80998035.

cc @PragmaTwice @xiaobiaozhao 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tanruixiang** [comment]
Hi. I am using MacBook M1. According to https://github.com/apache/incubator-kvrocks/commit/341a989d75783d8dad76bbd5a4473dd345472337#r80998035, If I replace `${CMAKE_OSX_DEPLOYMENT_TARGET}` with `11.0`, The compilation can be successful. I am not very familiar with cmake. Do you have time to repair it? I noticed that you don't have an apple device to test. I can compile and test for you. @PragmaTwice

**Comment by PragmaTwice** [comment]
> Hi. I am using MacBook M1. According to [341a989#r80998035](https://github.com/apache/incubator-kvrocks/commit/341a989d75783d8dad76bbd5a4473dd345472337#r80998035), If I replace `${CMAKE_OSX_DEPLOYMENT_TARGET}` with `11.0`, The compilation can be successful. I am not very familiar with cmake. Do you have time to repair it? I noticed that you don't have an apple device to test. I can compile and test for you. @PragmaTwice

Hi @tanruixiang, actually you can directly pass the option to cmake, e.g. `cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.3 ..`, `MACOSX_DEPLOYMENT_TARGET=10.3 cmake ..` or `./x.py build  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.3` rather than modifying cmake files.

If you want to try to fix this problem, you can add an `if ... else ...` to CMakeLists, i.e. when it is currently in macos and `CMAKE_OSX_DEPLOYMENT_TARGET` is not configured, an error should be reported and the user will be reminded to configure it.

**Comment by tanruixiang** [comment]
> > Hi. I am using MacBook M1. According to [341a989#r80998035](https://github.com/apache/incubator-kvrocks/commit/341a989d75783d8dad76bbd5a4473dd345472337#r80998035), If I replace `${CMAKE_OSX_DEPLOYMENT_TARGET}` with `11.0`, The compilation can be successful. I am not very familiar with cmake. Do you have time to repair it? I noticed that you don't have an apple device to test. I can compile and test for you. @PragmaTwice
> 
> Hi @tanruixiang, actually you can directly pass the option to cmake, e.g. `cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.3 ..`, `MACOSX_DEPLOYMENT_TARGET=10.3 cmake ..` or `./x.py build -DCMAKE_OSX_DEPLOYMENT_TARGET=10.3` rather than modifying cmake files.
> 
> If you want to try to fix this problem, you can add an `if ... else ...` to CMakeLists, i.e. when it is currently in macos and `CMAKE_OSX_DEPLOYMENT_TARGET` is not configured, an error should be reported and the user will be reminded to configure it.

The current error report is like this `Makefile:320: *** missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY.  Stop.`
As a new user, I will be a little confused about this error report. Can we update readme and note that MacOS needs to use the command you gave? Or if `MACOSX_DEPLOYMENT_TARGET` does not exist, give a default value(like 11.0 before).

**Comment by PragmaTwice** [comment]
My current plan was narrated above:
> If you want to try to fix this problem, you can add an if ... else ... to CMakeLists, i.e. when it is currently in macos and CMAKE_OSX_DEPLOYMENT_TARGET is not configured, an error should be reported and the user will be reminded to configure it.

If you want to specify a default value, maybe you need to investigate how to specify a valid (and proper) default value for various macos version (10.x, 11, ...) that mac users are currently using, e.g. if you specify 11.0 then you need to know the behavior when macos10 users build the repo.

**Comment by git-hulk** [comment]
I also found this issue on M1, but I'm wondering if we should make the LuaJIT as our default Lua VM.

**Comment by tanruixiang** [comment]
@PragmaTwice @git-hulk Thank you for your reply. Do you think we need to indicate in readme that MacOS needs to use the instructions @PragmaTwice  provide?
Let me share my thoughts as a new user. When I encountered a compilation error on MacOS, I gave up using MacOS directly. The docker installation Ubuntu image is used instead. If there is a MacOS build version in readme, I think I can use it more happily.
```
$ git clone https://github.com/apache/incubator-kvrocks.git
$ cd incubator-kvrocks
$ ./x.py build # `./x.py build -h` to check more options;
               # especially, `./x.py build --ghproxy` will fetch dependencies via ghproxy.com.
# macOS 
./x.py build -DCMAKE_OSX_DEPLOYMENT_TARGET = Appropriate version
```

**Comment by tisonkun** [comment]
Thanks for your contribution and fixing this issue :)
