### ISSUE TITLE
Expose some stats in RocksDB Perf Context and IO Stats Context 

### ISSUE THREAD

**Issue by mathspanda** [apache/kvrocks#783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Stats in Perf Context or IO Stat Context are useful to pinpoint some performance issues of redis commands.
For example, Counters `internal_delete_skipped_count` could illustrate why `zrangebyscore`  is so slow if there is too many tombstones.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@mathspanda Thanks for your report, `internal_delete_skipped_count ` makes a lot sense, would you like to contribute it?

**Comment by chrisxu333** [comment]
Hi @git-hulk , if nobody is working on this, can I take over?

**Comment by git-hulk** [comment]
@chrisxu333 Thank you!

**Comment by mapleFU** [comment]
https://github.com/apache/kvrocks/pull/1902

As mentioned here, maybe compaction-cpu-time can also be added here.

**Comment by chrisxu333** [comment]
@git-hulk As I'm thinking, this exposure of rocksdb perf and io stats would incur additional costs, so we maybe need a toggle to control it? Also what would be the proper way of displaying such stats, I'm thinking include them inside the result of info command?

**Comment by chrisxu333** [comment]
> @git-hulk As I'm thinking, this exposure of rocksdb perf and io stats would incur additional costs, so we maybe need a toggle to control it? Also what would be the proper way of displaying such stats, I'm thinking include them inside the result of `info` command?

**Comment by git-hulk** [comment]
Hi @chrisxu333 

Yes, I didn't think through this issue. It's not only about how to display the information but also how to collect that perf information since we don't enable them by default.

**Comment by chrisxu333** [comment]
> Hi @chrisxu333
> 
> Yes, I didn't think through this issue. It's not only about how to display the information but also how to collect that perf information since we don't enable them by default.

Sounds good I'll try to figure out a design :)

**Comment by chrisxu333** [comment]
Hi @git-hulk and @PragmaTwice , I've opened a pr for this issue. Please help review :)
