### ISSUE TITLE
CMake error building on Fedora 35

### ISSUE THREAD

**Issue by torwig** [apache/kvrocks#792]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

Unstable branch: fac42b092810f7273385cd57e881c5e4b91e1158
OS: Fedora 35

### Minimal reproduce step

Clone repo.

mkdir build
cd build
cmake ../

### What did you expect to see?

No errors

### What did you see instead?

```
CMake Error at /usr/lib64/cmake/GTest/GTestTargets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: GTest::gtest;GTest::gtest_main

  Targets not yet defined: GTest::gmock;GTest::gmock_main

Call Stack (most recent call first):
  /usr/lib64/cmake/GTest/GTestConfig.cmake:42 (include)
  /usr/share/cmake/Modules/FindGTest.cmake:187 (find_package)
  build/_deps/snappy-src/CMakeLists.txt:40 (find_package)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Many thanks to @torwig. We can add the `Fedora` OS as well if you know how to do that. ❤️

**Comment by torwig** [comment]
@git-hulk I don't think that I know how to do that. I guess Fedora is very similar to Red Hat, so this issue is rather an exception than the rule, so maybe Fedora doesn't need a separate section/build/etc.

**Comment by git-hulk** [comment]
Thanks, @torwig.
Sorry that I didn't claim the context clearly. What I mean is we can run the build and test on Fedora to aware the similar build error in the future. Like we have done in Ubuntu/macOS with different modes in [GitHub Actions](https://github.com/apache/incubator-kvrocks/blob/unstable/.github/workflows/kvrocks.yaml). But I think it's ok to fix the build error only.

**Comment by aleksraiden** [comment]
Reproduced at Debian 11 too

`-- Looking for sysconf
-- Looking for sysconf - found
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/GTest/GTestTargets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: GTest::gtest;GTest::gtest_main

  Targets not yet defined: GTest::gmock;GTest::gmock_main

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/GTest/GTestConfig.cmake:42 (include)
  /usr/local/share/cmake-3.24/Modules/FindGTest.cmake:194 (find_package)
  build/_deps/snappy-src/CMakeLists.txt:40 (find_package)
`
