### ISSUE TITLE
Unexpected behavior in configuration parsing

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

In kvrocks.conf

```
somekey1 = value # comment
somekey2 = "value x" # comment
```

### What did you expect to see?

The parsed items:
```
{"somekey1": "value", "somekey1": "value x"}
```

### What did you see instead?

The parsed items:
```
{"somekey1": "value # comment", "somekey1": "\"value x\" # comment"}
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Good catch, Redis also not support inline comment and I think it'll be better if we can support.
