### ISSUE TITLE
Use clang-format and clang-tidy instead of cpplint and cppcheck

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#800]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

clang-tidy is described in #602.

clang-format is currently the de facto standard of C++ code formatting.

It has lots of benefits, like:
- currently, cpplint reports some format error, but it can hardly automatically fix the code. So we need check errors in CI, and manually fix them one by one. But in clang-format, we can format code to a consistent style with just one command. And we can even add the auto-fix phase to CI (lots of projects do so). That is a huge convenience for developers. 
- we cannot control the version of cpplint well: it has different report in different version for same code. So different report in local and CI, it is unacceptable.
- cpplint cannot handle some detail of C++ language well. clang-format uses Clang AST and every powerful compiler technology in Clang. C++ is a super complicated language, no one can handle the syntax and semantics in different C++ standard well, except compilers like GCC or Clang. It is the core reason why cpplint and cppcheck failed to become great tools (recently cppcheck supports to use libClang instead of its own toy parser and type/semantics checker).

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tanruixiang** [comment]
By the way, I get the same result with clang14 which is the default version of macos. The latest clang is 15. If you can be sure that the result of 15 is the same, maybe there is no need to make judgments here. I think at least we can give a warning here and give the recommended clang version. Direct RuntimeError seems a bit inappropriate.@PragmaTwice 
https://github.com/apache/incubator-kvrocks/blob/unstable/x.py#L140

**Comment by PragmaTwice** [comment]
> By the way, I get the same result with clang14 which is the default version of macos. The latest clang is 15. If you can be sure that the result of 15 is the same, maybe there is no need to make judgments here. I think at least we can give a warning here and give the recommended clang version. Direct RuntimeError seems a bit inappropriate.@PragmaTwice https://github.com/apache/incubator-kvrocks/blob/unstable/x.py#L140

There are some difference (may not be encountered often) in format result between different version of clang-format. So I recommand developers use the same version of clang-format as in github actions.

You can install a clang-format 12 or download from the URL provided in the message.

I think it can be a warning, but developers may become angry when they format the code but still fail in the CI :rofl:

**Comment by tanruixiang** [comment]
> There are some difference (may not be encountered often) in format result between different version of clang-format. So I recommand developers use the same version of clang-format as in github actions.
> 
> You can install a clang-format 12 or download from the URL provided in the message.
> 
> I think it can be a warning, but developers may become angry when they format the code but still fail in the CI 🤣

At least on clang-14 the result is the same. Will clang-format be forward compatibility? If it doesn't then it's reasonable to throw an error.🤔

**Comment by PragmaTwice** [comment]
I can confirm there is some difference since I had some experience with this problem in [Oneflow](https://github.com/Oneflow-Inc/oneflow). Maybe there is currently no such code in kvrocks that might trigger compatibility issues for clang-format. I will change this message to warning.
