### ISSUE TITLE
Can't run only unixsocket, without any TCP.

### ISSUE THREAD

**Issue by aleksraiden** [apache/kvrocks#805]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

In local env, when we configure fro maximal performance, we want use only unixsocket, without any TCP. 
If I comment bind and port options and uncomment unixsocket, after start, kvrocks try to bing localhost:6666 port, ignoring disable option. In other hands, Redis works very well :)

### Solution

Not trying to bind TCP if both options are disabled (bind and port)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by aleksraiden** [comment]
Update: if we have one another instance kvrocks with TCP, second server instance with commented options not runned with message: main.cc:293] Could not create server TCP since the specified port[6666] is already in use

**Comment by torwig** [comment]
If everyone is OK with it, I'll try to resolve this issue.

**Comment by git-hulk** [comment]
Thanks to @aleksraiden and @torwig, I think we can do this since no objection.

**Comment by aleksraiden** [comment]
After little bit more deep investigation, we improve config check and comparability with Cluster mode. So, if you are turn on cluster or replication settings, you can't run without TCP. 
Thanks to @torwig

**Comment by git-hulk** [comment]
> After little bit more deep investigation, we improve config check and comparability with Cluster mode. So, if you are turn on cluster or replication settings, you can't run without TCP. Thanks to @torwig

Yes, exactly. This is really a good point.
