### ISSUE TITLE
redis-cli --pipe syntax error 

### ISSUE THREAD

**Issue by dirkpetersen** [apache/kvrocks#807]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

kvrocks unstable 40989fc26dc4229bd9f797c14eaa4df07574f47e
ubuntu 22.04

### Minimal reproduce step

```
root@localhost:~# cat /tmp/text1.txt
set zzzap zzzzzzzzzzzzzzzzznologin
set vv zzzzzzzzzzzzzzzzpsbinnologin
```

```
root@localhost:~# cat /tmp/text1.txt | redis-cli --pipe --verbose
```

### What did you expect to see?

This is with redis or keydb 

```
root@localhost:~# cat /tmp/text1.txt | redis-cli -h xx.79.179.186 --pipe --verbose
All data transferred. Waiting for the last reply...
Last reply received from server.
errors: 0, replies: 2
```

### What did you see instead?

root@localhost:~# cat /tmp/text1.txt | redis-cli --pipe --verbose
All data transferred. Waiting for the last reply...
ERR syntax error
Last reply received from server.
errors: 1, replies: 1

### Anything Else?

> redis-cli --version
redis-cli 6.0.16

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
Hello @dirkpetersen, many thanks for your feedback.

The root cause is that Kvrocks's inline protocol didn't support the `\r\n` separator. Will align this with Redis behavior and it only works like below:

```
❯ echo "set a 1\r\nset b 2\r\n" > pipes.txt
❯ cat pipes.txt
set a 1
set b 2

❯ cat pipes.txt | redis-cli -p 6666 --pipe --verbose
All data transferred. Waiting for the last reply...
Last reply received from server.
errors: 0, replies: 2
```
