### ISSUE TITLE
Tracking issue for moving TCL tests to Go cases

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#811]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

See also https://github.com/apache/incubator-kvrocks/pull/806.

### Cases

* [x] #829
* [x] #995
* [x] #841
* [x] #842
* [x] #814
* [x] #815
* [x] #816
* [x] #817
* [x] #818
* [x] #819
* [x] #820
* [x] #821
* [x] #822
* [x] #823
* [x] #824
* [x] #855
* [x] #856
* [x] #857
* [x] #861
* [x] #889
* [x] #890
* [x] #851
* [x] #860
* [x] #864
* [x] #872
* [x] #812
* [x] #945
* [x] #946
* [x] #947
* [x] #948
* [x] #949
* [x] #950

### Fixture

* [x] #813

**Comment by tisonkun** [comment]
Closed as done. @vmihailenco You may notice now we have a "compatibility tests set" for interacting Kvrocks with go-redis :)

**Comment by vmihailenco** [comment]
Hope go-redis will serve you well :)
