### ISSUE TITLE
Move TCL test unit/type/list to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#816]

**Comment by suica** [comment]
I would like to migrate all list test cases. Please assign this issue to me :)

**Comment by tisonkun** [comment]
@suica Assigned. Go ahead! It seems a large file, you can do it in several steps - be careful :)

**Comment by tisonkun** [comment]
@IoCing would you like to take a look at this issue? You may do it in several minor steps and even part of it does help :)

**Comment by IoCing** [comment]
@tisonkun ok , i would like to
