### ISSUE TITLE
Move TCL test unit/type/set to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#819]

**Comment by tanruixiang** [comment]
I'd like to do this.

**Comment by tisonkun** [comment]
@tanruixiang Assigned. Go ahead!

**Comment by tanruixiang** [comment]
Hi. I'm not very familiar with go. How to use go to pass the value exceeding Int64 in int ？Do we just need to pass it in the form of a string(I found that kvrocks should not implement large numbers, and automatically convert this to a string)?
```
    test "SADD an integer larger than 64 bits" {
        create_set myset {213244124402402314402033402}
        #assert_encoding hashtable myset
        assert_equal 1 [r sismember myset 213244124402402314402033402]
        assert_equal {1} [r smismember myset 213244124402402314402033402]
    }
```

**Comment by PragmaTwice** [comment]
> Hi. I'm not very familiar with go. How to use go to pass the value exceeding Int64 in int ？Do we just need to pass it in the form of a string(I found that kvrocks should not implement large numbers, and automatically convert this to a string)?
> 
> ```
>     test "SADD an integer larger than 64 bits" {
>         create_set myset {213244124402402314402033402}
>         #assert_encoding hashtable myset
>         assert_equal 1 [r sismember myset 213244124402402314402033402]
>         assert_equal {1} [r smismember myset 213244124402402314402033402]
>     }
> ```

I think maybe there is no difference between string and integer here, i.e. you can use string here. cc @git-hulk

**Comment by git-hulk** [comment]
> > Hi. I'm not very familiar with go. How to use go to pass the value exceeding Int64 in int ？Do we just need to pass it in the form of a string(I found that kvrocks should not implement large numbers, and automatically convert this to a string)?
> > ```
> >     test "SADD an integer larger than 64 bits" {
> >         create_set myset {213244124402402314402033402}
> >         #assert_encoding hashtable myset
> >         assert_equal 1 [r sismember myset 213244124402402314402033402]
> >         assert_equal {1} [r smismember myset 213244124402402314402033402]
> >     }
> > ```
> 
> I think maybe there is no difference between string and integer here, i.e. you can use string here. cc @git-hulk

Yes, exactly.
