### ISSUE TITLE
Move TCL test unit/type/zset to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#820]

**Comment by IoCing** [comment]
i would like to do it !

**Comment by tisonkun** [comment]
@IoCing assigned. Go ahead!

**Comment by tisonkun** [comment]
@IoCing any progress here? You may do it in several minor steps as I'm doing for https://github.com/apache/incubator-kvrocks/issues/824.

**Comment by IoCing** [comment]
@tisonkun sorry ，i just finished it

**Comment by tisonkun** [comment]
Cool!

**Comment by tisonkun** [comment]
Closed by #988.
