### ISSUE TITLE
Move TCL test unit/type/bitmap to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#823]

**Comment by ryuusama09** [comment]
I would like to work on it !

**Comment by tisonkun** [comment]
@ryuusama09 Thanks for your participation! Assigned.

Go ahead and you can take a looks at existing examples.

**Comment by ryuusama09** [comment]
> 

hi  , can you provide a link to project documentation , and a bit more understanding on what exactly needs to be done here

**Comment by tisonkun** [comment]
You can read the pull request https://github.com/apache/incubator-kvrocks/pull/810 and https://github.com/apache/incubator-kvrocks/pull/806 for example.

For locally verifying, run:

```
GO_CASE_WORKSPACE=./workspace KVROCKS_BIN_PATH=../../build/kvrocks go test -v ./...
```

... under `tests/gocase`.

**Comment by tisonkun** [comment]
Inactive assigner. Unassign and release the opportunity.

**Comment by tanruixiang** [comment]
Hi. I'd like to do this. ~By the way, is `bitop`'s support in our plan? If the difficulty is moderate, I am willing to develop this command.~ I found that `bittop` has been implemented, but the wiki is not updated. [kvrocks's wiki](https://github.com/apache/incubator-kvrocks/wiki/Support-Commands)

**Comment by git-hulk** [comment]
Hi @tanruixiang, You can just do the identical migration which means only replacing those bitmap tcl cases with Go. Can also take a look at a look at other PRs if you don't know how
to do that.

**Comment by tisonkun** [comment]
> but the wiki is not updated

@tanruixiang we should gradually migrate the document to our docsite https://kvrocks.apache.org/. You can find the source code at: https://github.com/apache/incubator-kvrocks-website. You're welcome to make a contribution on this topic if you find this doc is also missing on the docsite.

**Comment by tanruixiang** [comment]
> Hi @tanruixiang, You can just do the identical migration which means only replacing those bitmap tcl cases with Go. Can also take a look at a look at other PRs if you don't know how to do that.

Ok. In fact I've done several PRs to migrate from tcl to go. I was just wondering if I could do something different. Do you have any advice? Of course, please assign this task to me.

**Comment by git-hulk** [comment]
@tanruixiang I saw your PRs, thanks again. I misunderstood what you mean. 😆
