### ISSUE TITLE
Move TCL test unit/type/stream to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#824]

**Comment by aleksraiden** [comment]
@tisonkun maybe some script error, because a lot of identical issue created?

**Comment by tisonkun** [comment]
@aleksraiden No. If you take a closer look, they're similar issues for different test case.

**Comment by aleksraiden** [comment]
@tisonkun Oh yes, you are right, sorry, my mistake. Maybe I need to sleep ))

**Comment by tisonkun** [comment]
@aleksraiden I'll handle them as a relax, haha. If you have some spare time or want to write some trivial patches for relaxation, welcome to comment at any of them and I'll assign you :)
