### ISSUE TITLE
[BUG] Should read the multiple blocking pushed element

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#831]
The following test can pass if set `KVROCKS_BIN_PATH` to `redis-server`.

https://github.com/apache/incubator-kvrocks/blob/dbd968b47a08184b3a0b6492f28f9ba8edf6d11b/tests/gocase/unit/protocol/regression_test.go#L58-L63

We should figure out the cause and to fix it.

**Comment by git-hulk** [comment]
This's a bug in blocking pop, let's me handle it.

**Comment by git-hulk** [comment]
I found the root cause is the secondary blocking command has been read into the connection but didn't run since the NO read event was triggered again. I need some time to fix it since we can't force running read callback directly.
