### ISSUE TITLE
Move TCL test unit/expire to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#856]

**Comment by maochongxin** [comment]
I'd like to work on it, can assign to me :)

**Comment by tisonkun** [comment]
@maochongxin assigned. Go ahead!

**Comment by tisonkun** [comment]
Inactive. Unassign to release the seat.

**Comment by maochongxin** [comment]
Sorry for the delay. I have finished the coding and will finish it as soon as possible
#955 
> Inactive. Unassign to release the seat.

**Comment by tisonkun** [comment]
Closed by #955. Thank you @maochongxin!
