### ISSUE TITLE
Complete and beautify the kvrocks website

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#859]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

What you can do for [kvrocks.apache.org](https://kvrocks.apache.org/) (repo: [apache/incubator-kvrocks-website](https://github.com/apache/incubator-kvrocks-website)):
- Fix outdated paragraphs and typos in the documentation
- Beautify the typography and color scheme of the website
- Complete unfinished documents or add new ones

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chewitt1** [comment]
Hi can I work on this issue?

**Comment by PragmaTwice** [comment]
> Hi can I work on this issue?

@chewitt1  Sure! Since it is more like a general / tracking issue, feel free to open more concrete issues to this repo or create PRs to incubator-kvrocks-website.

**Comment by chewitt1** [comment]
Ok thank you! I will do that

**Comment by chewitt1** [comment]
Hi, I just wanted update and say I unfortunately will not be able to help with this issue at this time.

**Comment by PragmaTwice** [comment]
> Hi, I just wanted update and say I unfortunately will not be able to help with this issue at this time.

That's all right. Welcome to participate in kvrocks when you have time in the future.

**Comment by tisonkun** [comment]
Closed as information delivered.

We don't open a generic issue like this. Only file issues if we have concrete actionable tasks for improving the website.
