### ISSUE TITLE
Ci results are random, and the same code may succeed or fail

### ISSUE THREAD

**Issue by tanruixiang** [apache/kvrocks#867]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

[tison's pr](https://github.com/apache/incubator-kvrocks/pull/865) and [my pr](https://github.com/apache/incubator-kvrocks/pull/858)  both seem to have this problem.

### Minimal reproduce step

You can view it through my [PR](https://github.com/apache/incubator-kvrocks/pull/858) history.
If you have permission, you can reproduce it by restarting the CI.

### What did you expect to see?

There was no randomness in CI results.

### What did you see instead?

Ci results are random

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
These failures seem all to `scripting.tcl`. Since we're migrating tests, we can revisit all those tests.

If you found failures for other test cases, please point in out.

**Comment by tisonkun** [comment]
Closed to be covered as https://github.com/apache/incubator-kvrocks/issues/872. This issue doesn't have a clear target in description.
