### ISSUE TITLE
Move TCL test unit/scripting to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#872]
Be aware that current scripting tests are unstable. See also https://github.com/apache/incubator-kvrocks/issues/867.

**Comment by tanruixiang** [comment]
[list_test.go](https://github.com/apache/incubator-kvrocks/actions/runs/3061992524/jobs/4942482133) is also unstable.

**Comment by tisonkun** [comment]
@tanruixiang can you provide run reports?

**Comment by tisonkun** [comment]
OK I see it.

**Comment by tisonkun** [comment]
@vmihailenco it seems after Kvrocks tests migrated to go-redis, some cases fail with:

```
    list_test.go:203: 
        	Error Trace:	/home/runner/work/incubator-kvrocks/incubator-kvrocks/tests/gocase/unit/type/list/list_test.go:203
        	Error:      	Received unexpected error:
        	            	read tcp 127.0.0.1:55526->127.0.0.1:45695: i/o timeout
        	Test:       	TestZipList/ziplist_implementation:_value_encoding_and_backlink
```

when under stress. What's the best practice go-redis retry to set up a reasonable timeout in this case?

**Comment by vmihailenco** [comment]
There is a `MaxRetries` options and it seems to be enabled by default - https://github.com/go-redis/redis/blob/master/options.go#L61-L69

What Read/WriteTimeout do you use?

**Comment by tisonkun** [comment]
@vmihailenco I think the first time we even disable retry https://github.com/apache/incubator-kvrocks/pull/869 to try to address this flaky test. The reason then is we may reduce the workload caused by retries. But it seems we need to extend the retry time and timeout interval. However, always increasing waiting interval and retry time seems not a good idea...

Would you suggest a suitable config here?

**Comment by vmihailenco** [comment]
>Would you suggest a suitable config here?

Looks like you are using the default config which has Read/WriteTimeout = 3 seconds. It should work just fine, but you can try to increase the timeout. Nothing else comes to mind.
