### ISSUE TITLE
Add support for RESP3

### ISSUE THREAD

**Issue by usrtax** [apache/kvrocks#880]
https://redis.io/commands/hello/
```
redis.setresp(3)
```

https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md
RESP3 is an updated version of RESP v2, which is the protocol used in Redis starting with roughly version 2.0 (1.2 already supported it, but Redis 2.0 was the first version to talk only this protocol). The name of this protocol is just RESP3 and not RESP v3 or RESP 3.0.

for example use in lua

```
local function my_hgetall(keys, args)
  redis.setresp(3)
  local hash = keys[1]
  local res = redis.call('HGETALL', hash)
  res['map']['_last_modified_'] = nil
  return res
end
```

**Comment by infdahai** [comment]
BTW, we can split the task to many functions and support the resp3 protocol gradually.

We can give a tracking issue based on different types from [resp3.md](https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md) currently.

Could I ask your advice? @torwig @PragmaTwice @git-hulk

**Comment by git-hulk** [comment]
> We can give a tracking issue based on different types from [resp3.md](https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md) currently.

Sure, it's good to separate sub-tasks by the data type, but we need to offer a unified way to determine whether to use RESP3 or not like the encoding: https://github.com/apache/incubator-kvrocks/blob/f557255cec8d4f43cf63144b712c71026bc9320e/CMakeLists.txt#L34. And should NOT enable it before all data types are supported RESP3.
