### ISSUE TITLE
Support Hrange command

### ISSUE THREAD

**Issue by tanruixiang** [apache/kvrocks#894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

According to [kvrocks 3.0 roadmap](https://github.com/apache/incubator-kvrocks/projects/2#card-81014194), add hrange command.

### Solution

Since kvrocks uses rocksdb as the storage engine, keys are ordered in sstable. So we can easily provide a range query command for hash.
We give the following command:
hrange hashkey $start $end [LIMIT $number]
For the specified hashkey, We will get the kv-pair with the kv-pair's key located in [start, stop) interval in the hash. If the limit is set, at most limit kv pairs will be returned.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by caipengbo** [comment]
It would be nice to explain the syntax of the hrange command in this PR, not only to make it easier to read the code, but also to migrate the syntax to a document (website) in the future.
