### ISSUE TITLE
 Is it appropriate to change StartServer to a factory that returns the Server interface? 

### ISSUE THREAD

**Issue by ColinChamber** [apache/kvrocks#915]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

I will submit a PR about save-rdb, which needs to start Redis server to do some integration tests. Kvrocks2redis can also use that. And some tests can also be written as

-  `require.EqualValues(t, rdb.Get(ctx, "foo").Val(), kdb.Get(ctx, "foo").Val()))`

### Solution

func StartServer(t testing.TB, st ServerType, configs map[string]string) IServer { 
...
}

srvRedis := util.StartServer(t, util.TypeRedis ,map[string]string{})
srvKvrocks := util.StartServer(t, util.TypeKvrocks ,map[string]string{})

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
I think if the code of `StartServer` can be reused well for both kvrocks and redis, they can be implemented in one function. If it is just a dispatch, but the two parts of the code need to be completely separately implemented, then I think it is better to implement it as two functions `StartKvrocksServer` and `StartRedisServer`, and then you can implement a function like `StartServer` to do a dynamic dispatch. cc @tisonkun

**Comment by ColinChamber** [comment]
Thanks for your guidance. I've tried several things.  #920

**Comment by tisonkun** [comment]
See also:

* https://github.com/apache/incubator-kvrocks/pull/920#issuecomment-1265418310
* https://github.com/apache/incubator-kvrocks/pull/920#issuecomment-1265422735
