### ISSUE TITLE
PING returns PONG if no argument is provided, otherwise return a copy of the argument as a bulk.

### ISSUE THREAD

**Issue by ColinChamber** [apache/kvrocks#926]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable

### Minimal reproduce step

ping message

### What did you expect to see?

message

### What did you see instead?

wrong number of arguments

### Anything Else?

[redis ping](https://redis.io/commands/ping/)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
wow, it refreshes my knowledge.😃

**Comment by ColinChamber** [comment]
I haven't used Kvrocks for a long time. I can only do some boring PR first. 😃 However, there are indeed applications that add parameters to ping, such as celery.
