### ISSUE TITLE
Can not build use x.py

### ISSUE THREAD

**Issue by 17998384** [apache/kvrocks#927]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

2.1.0

### Minimal reproduce step

The following error is displayed when using./x.py build

### What did you expect to see?

I want the build to succeed

### What did you see instead?

```[x@xx incubator-kvrocks-2.1.0]$ ./x.py build
  File "./x.py", line 59
    """
      ^
SyntaxError: invalid syntax
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Which python version are you using? We support only python 3+.

**Comment by 17998384** [comment]
> Which python version are you using? We support only python 3+.
I use python version is 3.4

**Comment by PragmaTwice** [comment]
I will try to reproduce it with python 3.4. You can use more recent version to build it, such as python 3.9 or 3.10. Or you can try x.py in the unstable branch.

**Comment by 17998384** [comment]
> I will try to reproduce it with python 3.4. You can use more recent version to build it, such as python 3.9 or 3.10. Or you can use x.py in the unstable branch.

OK，I think I know what the problem is. Strings starting with f are only supported after python3.6. Thank you for answering my question

**Comment by 17998384** [comment]
This can be resolved using python3.6 or higher

**Comment by 17998384** [comment]
This can be resolved using python3.6 or higher

**Comment by PragmaTwice** [comment]
Good catch! Maybe we should add a notice or something for users to limit the minimum version of python. cc @tisonkun @git-hulk

**Comment by tisonkun** [comment]
@PragmaTwice perhaps read the version by `platform.python_version()` or `sys.version_info`, failed if version not match. Then the script is self-explained.
