### ISSUE TITLE
Some `return` is missing in redis_metadata.cc

### ISSUE THREAD

**Issue by xumingbo** [apache/kvrocks#929]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

Latest commit [73092dc](https://github.com/apache/incubator-kvrocks/commit/73092dc4a5e4f87411133efdcf10b393dd8f9ae9) on Aug 17

### Minimal reproduce step

in redis_metadata.cc

in rocksdb::Status ListMetadata::Decode(const std::string &bytes) 
line 282
   if (input.size() < 12) rocksdb::Status::InvalidArgument(kErrMetadataTooShort);

Should be:
if (input.size() < 12) **return** rocksdb::Status::InvalidArgument(kErrMetadataTooShort);

same error at line 287

### What did you expect to see?

if (input.size() < 12) **return** rocksdb::Status::InvalidArgument(kErrMetadataTooShort);

### What did you see instead?

if (input.size() < 12) rocksdb::Status::InvalidArgument(kErrMetadataTooShort);

### Anything Else?

same issue on line 282 and 287

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Good catch! Thanks. Are you willing to submit a PR?

**Comment by aleksraiden** [comment]
I try to fix this

**Comment by xumingbo** [comment]
Also:at line 325  if (input.size() < 12) {
    rocksdb::Status::InvalidArgument(kErrMetadataTooShort);
  }

Regards,
Bo Xu
    On Thursday, September 29, 2022 at 12:16:07 AM PDT, Aleks Lozovyuk ***@***.***> wrote:  
 
 


I try to fix this

**Comment by torwig** [comment]
@xumingbo Pull request also fixes line 325
