### ISSUE TITLE
Github deprecated Ubuntu-18.04 in CI builds.

### ISSUE THREAD

**Issue by aleksraiden** [apache/kvrocks#941]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

See [GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)

### Solution

So, maybe we can:

- start to migrate on next version of Ubuntu base images (20.04)
- add Ubuntu 22.04 as second images into matrix

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by aleksraiden** [comment]
Also, tcl will be upgraded to 8.6 (default in Ubuntu 20.04 and above)

**Comment by aleksraiden** [comment]
I have tested it in private fork, all builds and tests passed OK. Trying to add Ubuntu 22.04 into matrix

**Comment by aleksraiden** [comment]
At now, a default ubuntu-latest images changed to 20.04, so cpplint not working now. In cooperation with  @torvig working to fix them

**Comment by PragmaTwice** [comment]
I also noticed the problem, feel free to open a PR!

**Comment by tanruixiang** [comment]
> At now, a default ubuntu-latest images changed to 20.04, so cpplint not working now. In cooperation with @Torvig working to fix them

I noticed that there has been an [issue](https://github.com/apache/incubator-kvrocks/issues/800) proposing to replace cpplint with `clang-*`, raised by @PragmaTwice .  If you have time, you can try using `clang-*` by the way to solve this problem.

**Comment by PragmaTwice** [comment]
> I noticed that there has been an [issue](https://github.com/apache/incubator-kvrocks/issues/800) proposing to replace cpplint with `clang-*`, raised by @PragmaTwice . If you have time, you can try using `clang-*` by the way to solve this problem.

Switching to `clang-*` can be a work involving so many code changes and discussions, I suggest we can remain cpplint in this PR if you want to keep the changes minimal. And it may take the focus away from the content of this issue and make it more difficult to merge.

But feel free to try replacing the current cpplint and cppcheck with `clang-*` in other PRs.

**Comment by PragmaTwice** [comment]
You can try to modify the current flags used in cpplint or cppcheck here: https://github.com/apache/incubator-kvrocks/blob/unstable/x.py#L119-L137

**Comment by aleksraiden** [comment]
@torwig could we doing here? I will prepare a PR with updated Ubuntu, but cpp* is on your side

**Comment by torwig** [comment]
@aleksraiden Sure, I'll help you.

**Comment by aleksraiden** [comment]
All task are done, except use Ubuntu 22, maybe this is too much for us, ci perform too long in this way. 

Some troubles with tcl test on macos-11, try to rebuild.  

Awesome @torwig fix all files, currently we are still used cpplint/check (v1.6.1) not clang.
