### ISSUE TITLE
Move TCL test integration/slotimport to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#946]

**Comment by tisonkun** [comment]
@git-hulk @ShooterIT may I ask how the CRC16 table is generated? I don't want to hard code the table once more..

**Comment by PragmaTwice** [comment]
https://github.com/lammertb/libcrc/blob/master/src/crc16.c#L124 here?

**Comment by git-hulk** [comment]
@git-hulk @ShooterIT may I ask how the CRC16 table is generated? I don't want to hard code the table once more..

https://redis.io/docs/reference/cluster-spec/ This doc explained how Redis calculates the CRC16. `go-redis` also implements this function but it's an internal function: https://github.com/go-redis/redis/blob/27f0addeb2e6997bdd2faa1b48f6a989f83c4751/internal/hashtag/hashtag.go#L65

**Comment by tisonkun** [comment]
```c++
    // 3) port
    auto parse_result = ParseInt<int>(fields[2], NumericRange<int>{1, 65535 - kClusterPortIncr - 1}, 10);
    if (!parse_result) {
      return Status(Status::ClusterInvalidInfo, "Invalid cluster node port");
    }
    int port = *parse_result;
```

Why cluster node port must be in `[1, 55534]`?

**Comment by git-hulk** [comment]
This should be unnecessary for Kvrocks, coz we don't need the extra cluster port. cc @ShooterIT @caipengbo @ChrisZMF

**Comment by tisonkun** [comment]
@git-hulk thank you! The next question is that when kill a "cluster-enable: yes" server, it cannot exit properly but:

```
Log file created at: 2022/10/09 11:21:41
Running on machine: chenzilis-MacBook-Pro-2.local
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
E20221009 11:21:41.602181 3879347 main.cc:69] ======= Ooops! kvrocks 999.999.999 @a8e06c7 got signal: Abort trap: 6 (6) =======
E20221009 11:21:41.603391 3879347 main.cc:76] 1   libsystem_platform.dylib            0x00000001a597f4a4 _sigtramp + 56: _sigtramp
E20221009 11:21:41.603444 3879347 main.cc:76] 2   libsystem_pthread.dylib             0x00000001a5967ee0 pthread_kill + 288: pthread_kill
E20221009 11:21:41.603477 3879347 main.cc:76] 3   libsystem_c.dylib                   0x00000001a58a2340 abort + 168: abort
E20221009 11:21:41.603511 3879347 main.cc:76] 4   libc++abi.dylib                     0x00000001a5922b08 _ZN10__cxxabiv130__aligned_malloc_with_fallbackEm + 0: __cxxabiv1::__aligned_malloc_with_fallback()
E20221009 11:21:41.603543 3879347 main.cc:76] 5   libc++abi.dylib                     0x00000001a5912834 _ZL28demangling_terminate_handlerv + 52: demangling_terminate_handler()
E20221009 11:21:41.603569 3879347 main.cc:76] 6   libc++abi.dylib                     0x00000001a5921ea4 _ZSt11__terminatePFvvE + 20: std::__terminate()
E20221009 11:21:41.603595 3879347 main.cc:76] 7   libc++abi.dylib                     0x00000001a5921e2c _ZSt9terminatev + 44: std::terminate()
E20221009 11:21:41.603726 3879347 main.cc:76] 8   kvrocks                             0x00000001043f6b58 _ZN11SlotMigrateD2Ev + 108: SlotMigrate::~SlotMigrate()
E20221009 11:21:41.603857 3879347 main.cc:76] 9   kvrocks                             0x00000001043ead70 _ZN6ServerD2Ev + 624: Server::~Server()
E20221009 11:21:41.604001 3879347 main.cc:76] 10  kvrocks                             0x000000010441a694 main + 1760: main
E20221009 11:21:41.604032 3879347 main.cc:78] 11  dyld                                0x000000010530508c start + 520
```

Although we can simply ignore the error, do you have idea on this case?

**Comment by git-hulk** [comment]
@tisonkun It's caused by the migrate didn't terminate the internal thread before destroying. Will create an issue to track.

**Comment by ShooterIT** [comment]
> Why cluster node port must be in [1, 55534]?

In redis cluster mode, it needs extra cluster port for gossip, and its default number is `listen port + 10000`. so i add this check. but now this cluster port is configurable, so i think we just check if it is right port.

**Comment by tisonkun** [comment]
@ShooterIT Included in https://github.com/apache/incubator-kvrocks/pull/966/files#diff-a4e8a56bf7d9d0e658d90784eab42c809b59dd142ee4ae1dafa54d5d657d688d, please take a look :)
