### ISSUE TITLE
Move TCL test integration/rsid_psync to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#949]

**Comment by amoghrajesh** [comment]
@tisonkun i would like to work on this. Can you point me where to get started and assign the issue to me?

**Comment by tisonkun** [comment]
@amoghrajesh assigned. Go ahead!

**Comment by amoghrajesh** [comment]
@tisonkun can you point me to a getting started guide or explain to me what the issue is?

**Comment by tisonkun** [comment]
You can take a look at other similar issues in #811 while migrating integration tests can be more complex than unit tests.

If you don't know what's the issue here, I suggest you unassign yourself instead - don't pick up something beyond your ability at the moment.

**Comment by amoghrajesh** [comment]
Un assigning myself and releasing the opportunity.
