### ISSUE TITLE
Support `GetEX` command

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#960]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

Redis supports the `GetEX` command since 6.2.0. We can follow-up as well since this command can benefit users if they want to extend or reduce the expire time when touching.

### Solution

Implement the command described in: https://redis.io/commands/getex/

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by maochongxin** [comment]
Can I try it on ? #961

**Comment by git-hulk** [comment]
> Can I try it on ? #961

Assigned, thank you!
