### ISSUE TITLE
[bug] kvrocks2redis should not lowercase all lines when reading configuration files 

### ISSUE THREAD

**Issue by manchurio** [apache/kvrocks#964]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

![image](https://user-images.githubusercontent.com/82277001/194734491-d922e926-37aa-43e9-906d-636f86290462.png)

Cannot connect to the server when the password contains uppercase letters

### Minimal reproduce step

```
# kvrocks <kvrocks_ip> <kvrocks_port> [<kvrocks_auth>]
kvrocks 127.0.0.1 6666 Pass
```

### What did you expect to see?

connect to the server successfully

### What did you see instead?

invalid password

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by torwig** [comment]
@manchurio Good catch!
