### ISSUE TITLE
Move TCL test unit/tls to Go case

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#995]

**Comment by tisonkun** [comment]
@PragmaTwice could you spend some time taking care of the TLS tests?

**Comment by PragmaTwice** [comment]
Sure.

**Comment by tisonkun** [comment]
go-redis's TLS config: https://redis.uptrace.dev/guide/go-redis.html#using-tls

**Comment by tisonkun** [comment]
https://github.com/tisonkun/incubator-kvrocks/tree/tls-tests

Here is a prototype that you can make use of. Although, TLS config is a bit complex that I cannot handle it soon :(

**Comment by PragmaTwice** [comment]
Thanks! I will try to use these patches.
